### ISSUE TITLE
[Feature]: Developer can create a task using the Korifi API shim

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1017]
### Background

**As a** developer
**I want** to run tasks using the Korifi API shim
**So that** I can execute one-off workloads just like I do on CF-on-VMs

### Acceptance Criteria

**GIVEN** `app1` exists in `org1` and `space1`
**AND** `droplet1` is the current droplet for `app1`
**AND** `dev1` is a `SpaceDeveloper` in `space1`
**AND** `dev2` is *not* a `SpaceDeveloper` in `space1`
**AND** `mgr` is a `SpaceManager` in `space1`
- **WHEN I** make the following request to our shim API:
  ```
  POST /v3/apps/<app1-guid>/tasks HTTP/1.1
  Authorization: ...
  Content-type: application/json
  ```
  ```json
  { 
    "command": "echo hello"
  }
  ```
  **THEN I** get the following response:
  ```
  HTTP/1.1 201 Created
  Content-type: application/json
  ```
  ```json
  {
    "guid": "d5cc22ec-99a3-4e6a-af91-a44b4ab7b6fa",
    "name": "d5cc22ec-99a3-4e6a-af91-a44b4ab7b6fa",
    "command": "echo hello",
    "relationships": {
      "app": {
        "data": {
          "guid": "<app1-guid>"
        }
      }
    },
    "links": {
      "self": {
        "href": "https://<shim-domain>/v3/tasks/d5cc22ec-99a3-4e6a-af91-a44b4ab7b6fa"
      },
      "app": {
        "href": "https://<shim-domain>/v3/apps/<app1-guid>"
      }
    }
  }
  ```
  **AND I** see a `Pod` in namespace `<space1-guid>` has executed the command `"echo hello"` using the same image as `app1`
- **WHEN I** try to do the same as `dev2` or `mgr`
  **THEN I** get the following response:
  ```
  HTTP/1.1 403 Forbidden
  Content-Type: application/json
  ```
  ```json
  {
    "errors": [
      {
        "code": 10003,
        "title": "CF-NotAuthorized",
        "detail": "You are not authorized to perform the requested action"
      }
    ]
  }
  ```

### Dev Notes

* `name` should be autogenerated for now - reusing the GUID should be fine.

**Comment by georgethebeatle** [comment]
As discussed I raised PR #1190 to strip all fields that are not necessary for this story. I tested that task creation works with only a small fraction of all the API response fields as specifies by cf api docs. This story should be changed to reflect that and follow on stories should be spawned to drive the introduction of the rest of the fields
