### ISSUE TITLE
[Chore]: Cleanup gke container registry

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#1019]
### Background

When we set up our Concourse pipeline we chose to push ci related images to the gke image registry, because of ease of use from within gke, security and proximity. However our CI pipeline is producing a large amount of images and no one is cleaning them up, which means our bill with gke will grow bigger and bigger over time for no reason.

We need some mechanism of cleaning up old versions of images that we no longer need.

### Action to take

There are a couple of paths on the registry that we are pushing to
- ci: here go the CI images that coucourse uses to run jobs as well as the korifi api and controller images. We generally need only the latest version of any of these to be able to run our pipelines, so we can delete older ones. Depending on what the `gcloud cli` is capable of we might delete all but the latest or maybe all whose age is more than a week or some other period. We should be careful when dealing with CI images since they are pushed only when we modify their Dockerfiles. So we cannot simply delete everything older than a week. It should be safe to delete everything older than a certain age and do this on a timer in concourse.
- pr-e2e-images: These are the images of test apps that the e2e tests pushed to korifi. We can simply delete all of them older than a week or even a day, since they will never be needed again. We can delete all of these either after each test run or on cluster destruction or any other convenient place.
- We have the intention of pushing some long running apps on top of korifi, such as `postfacto` and `pairup`. If we do that it will likely be on a dedicated acceptance cluster, which will put the images in a yet another top level path in the container registry. We should explicitly exclude this path from the cluster, because there is no easy way to determine what's being used and deleting even an old image might break a long running app. The acceptance cluster might or might not be a fact when we get to this chore, so this is just a warning.

### Impact

We have a lower gke bill

### Dev Notes

We can use this script for inspiration: https://gist.github.com/ahmetb/7ce6d741bd5baa194a3fac6b1fec8bb7

**Comment by kieron-dev** [comment]
Status:
* Added `clean-gcp-artifact-registry` task to the run-e2es jobs (main and pr).
  - This deletes all packages in the `pr-e2e-images` repository, apart from the one called `kpack/beta` which is associated with the kpack ClusterBuilder

To do:
* Delete old tags of `kpack/beta`
  - This might be tricky as the artifact registry does not store timestamps. Maybe keeping latest and the lexicographically latest date tag would do the trick?
* Delete old tags in the `ci` repository. Same problem as above.

Ref:
`gcloud artifacts packages ...` and `gcloud artifacts tags ...`

**Comment by kieron-dev** [comment]
Today's lesson is use `gcloud artifacts docker ...`. Then you get timestamps and things.

The story is complete. Work done:
- delete all pr-e2e-images images, apart from the one called kpack/beta, after each e2e run.
- delete all korifi-api, korifi-controllers, korifi-kpack-image-builder images in the ci repository older than 24 hours after each e2e run
- delete gcloud and ci images in the ci repository older than one hour after creating a new ci image
