### ISSUE TITLE
[Bug]: Non-clean korifi deployment using kapp should not fail

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#1027]
### What happened?

So far we are mainly doing clean deploys of korifi, either on a fresh kind cluster or we are doing an undeploy before we deploy. The latter is what our PR [pipeline](https://ci.cf-k8s.cf/teams/main/pipelines/pr-e2e/jobs/run-e2es/) is doing.

Sometimes however the undeploy will fail for various reasons and in these cases the next deployment is doomed to fail with an error like this: https://ci.cf-k8s.cf/teams/main/pipelines/pr-e2e/jobs/run-e2es/builds/45#L624ade13:128:131

```
kapp: Error: Applying update namespace/cf-k8s-controllers-system (v1) cluster:
  Updating resource namespace/cf-k8s-controllers-system (v1) cluster:
    API server says: admission webhook "namespaces.hnc.x-k8s.io" denied the request: namespaces "cf-k8s-controllers-system" is forbidden: cannot remove tree label "cf-k8s-controllers-system.tree.hnc.x-k8s.io/depth" in namespace "cf-k8s-controllers-system"; these can only be managed by HNC (reason: Forbidden)
```

What happens here is the following:
1. `kapp deploy` is creating the `cf-k8s-controllers-system` namespace
2. HNC labels the namespace
3. The second `kapp deploy` is trying to create the namespace again, but does not know about the HNC label, so it effectively tries to remove it
4. The HNC webhook blocks the label removal

If you use `kubectl` this error does not occur, because `kubectl` ignores the labels and annotations when you apply an existing object

### What you expected to happen

I can kapp deploy korifi without having to first undeploy it.

### Acceptance Criteria

GIVEN I `kapp deploy` korifi
WHEN I `kapp deploy` korifi again a few minutes later
THEN I do not get any errors

### How to reproduce it (as minimally and precisely as possible)

1. `kapp deploy` korifi
2. wait for HNC to label the system namespace
3. `kapp deploy` korifi again

### Environment

Revision of codebase: main
Cloud provider or hardware configuration: any

**Comment by gcapizzi** [comment]
@georgethebeatle do you think this is still valid now that we use Helm?
