### ISSUE TITLE
[Feature]: Developer can cancel a task using the Korifi API shim

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1041]
### Background

**As a** developer
**I want** to run tasks using the Korifi API shim
**So that** I can execute one-off workloads just like I do on CF-on-VMs

### Acceptance Criteria

**GIVEN** a task `task1` with `state: "RUNNING"`
**AND** `droplet1` is the current droplet for `app1`
**AND** `dev1` is a `SpaceDeveloper` in `space1`
**AND** `dev2` is *not* a `SpaceDeveloper` in `space1`
- **WHEN I** make the following request to our shim API:
  ```
  POST /v3/tasks/<task1-guid>/actions/cancel HTTP/1.1
  Authorization: ...
  Content-type: application/json
  ```
  **OR I** make the following request to our shim API:
  ```
  PUT /v3/tasks/<task1-guid>/cancel HTTP/1.1
  Authorization: ...
  Content-type: application/json
  ```
  **THEN I** get the following response:
  ```
  HTTP/1.1 202 Accepted
  Content-type: application/json
  ```
  ```json
  {
    "guid": "<task1-guid>",
    "sequence_id": 202005041656123,
    "name": "<task1-guid>",
    "command": "echo hello",
    "state": "CANCELING",
    "memory_in_mb": 1024,
    "disk_in_mb": 1024,
    "result": {
      "failure_reason": null
    },
    "droplet_guid": "<droplet1-guid>",
    "created_at": "2016-05-04T17:00:41Z",
    "updated_at": "2016-05-04T17:00:42Z",
    "relationships": {
      "app": {
        "data": {
          "guid": "<app1-guid>"
        }
      }
    },
    "links": {
      "self": {
        "href": "https://<shim-domain>/v3/tasks/<task1-guid>"
      },
      "app": {
        "href": "https://<shim-domain>/v3/apps/<app1-guid>"
      },
      "cancel": {
        "href": "https://<shim-domain>/v3/tasks/<task1-guid>/actions/cancel",
        "method": "POST"
      },
      "droplet": {
        "href": "https://<shim-domain>/v3/droplets/<droplet1-guid>"
      }
    }
  }
  ```
  **AND** the task execution is interrupted
- **WHEN I** try to do the same as `dev2`
  **THEN I** get the following response:
  ```
  HTTP/1.1 404 Not Found
  Content-Type: application/json
  ```
  ```json
  {
    "errors": [
      {
        "code": 10010,
        "detail": "Task not found. Ensure it exists and you have access to it.",
        "title": "CF-ResourceNotFound"
      }
    ]
  }
  ```
- **WHEN I** try to do the same as `mgr`
  **THEN I** get the following response:
  ```
  HTTP/1.1 403 Forbidden
  Content-Type: application/json
  ```
  ```json
  {
    "errors": [
      {
        "code": 10003,
        "title": "CF-NotAuthorized",
        "detail": "You are not authorized to perform the requested action"
      }
    ]
  }
  ```

**GIVEN** a canceled task
**WHEN** the task execution has been interrupted
**THEN I** see the task's `state` is `"FAILED"`

**GIVEN** a `task1` with `state` `"SUCCEEDED"` or `"FAILED"`
**WHEN I** make the following request to our shim API:
```
POST /v3/tasks/<task1-guid>/actions/cancel HTTP/1.1
Authorization: ...
Content-type: application/json
```
**THEN I** get the following response:
```
HTTP/1.1 422 Unprocessable Entity
Content-type: application/json
```
```json
{
  "errors": [
    {
      "code": 10008,
      "detail": "Task state is (SUCCEEDED|FAILED) and therefore cannot be canceled",
      "title": "CF-UnprocessableEntity"
    }
  ]
}
```

**GIVEN** a task
**WHEN I** [get the task](https://github.com/cloudfoundry/korifi/issues/1022) or [list the task](https://github.com/cloudfoundry/korifi/issues/1037)
**THEN I** see a `cancel` link in the response:
```json
"links": {
  "self": {
    "href": "https://<shim-domain>/v3/tasks/<task1-guid>"
  },
  "app": {
    "href": "https://<shim-domain>/v3/apps/<app1-guid>"
  },
  "cancel": {
    "href": "https://<shim-domain>/v3/tasks/<task1-guid>/actions/cancel",
    "method": "POST"
  },
  "droplet": {
    "href": "https://<shim-domain>/v3/droplets/<droplet1-guid>"
  }
}
```

**Comment by kieron-dev** [comment]
TODO: https://github.com/cloudfoundry/korifi/blob/9635314eff2f9366a4254ba7f35af93c0564c8f0/controllers/webhooks/cf_validation_errors.go#L23

Should that include the cryptic error type? CF only prints the message normally.
