### ISSUE TITLE
[Bug]: CFRoutes are not updated when CFDomain is updated

### ISSUE THREAD

**Issue by Birdrock** [cloudfoundry/korifi#1092]
### What happened?

When the CFDomain was updated with a new domain, the CFRoute did not update. It maintained the domain that was represented by the CFDomain when it was created. Restarting the controller-manager pods resulted in the the CFRoute updating and propagating that to the corresponding HTTPProxy.

### What you expected to happen

* Expected the CFRoute to be updated with the CFDomain changes.
* Expected a new HTTPProxy when the CFRoute reconciles.

### Acceptance Criteria

GIVEN CFDomain & CFRoute
WHEN I change the CFDomain
THEN I the CFRoute update & a new HTTPProxy is created

### How to reproduce it (as minimally and precisely as possible)

1. `cf push` an application
2. Create new CFDomain
3. Update `korifi_api_config.yaml` field `defaultDomainName` to point to the newly created CFDomain
4. Create new certs for the new domain
5. Update `korifi-workloads-ingress-cert` with new certs
6. Deploy with `kustomize`
7. Inspect CFRoute
8. URI should reflect new domain, but does not

### Environment

Revision of codebase: 11f02d4175a9f6d4e8e3e765219fdbf613cc394e

**Comment by tcdowney** [comment]
@Birdrock since we don't support updating an existing `CFDomain` and have a [webhook that blocks it](https://github.com/cloudfoundry/korifi/blob/78b8694b3bc368adf6862e10391d36b2a19f368e/controllers/webhooks/networking/cfdomain_validator.go#L105) we can close this right?

Or was this issue related to something with the `defaultDomainName` config property not behaving correctly?

**Comment by gcapizzi** [comment]
Same for https://github.com/cloudfoundry/korifi/issues/1093 which also assumes `CFDomain` as mutable.

**Comment by gcapizzi** [comment]
I just tried to redeploy Korifi after changing the `defaultDomainName` and, correctly, installation will fail as the `create-app-domain` post-install job fails with an `ImmutableFieldError`. I will close this story and #1093 unless anyone has any objections!
