### ISSUE TITLE
Basic app logs

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1096]
Provide app developers with basic logs through existing CF interfaces (in priority order, in case we need to split this work into a later epic):

* Staging logs during the build phase of `cf push`
* Stream of app logs (staging and running) via `cf logs`
* Best-effort recent app logs via `cf logs --recent`

Metric stories are split into #778.

**Comment by acosta11** [comment]
Work for the epic has been completed. Closing.
