### ISSUE TITLE
[Chore] Improve directories naming

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#1110]
While working on https://github.com/cloudfoundry/korifi/issues/1091 we realised that there are few directories that have weird names and is probably worth renaming:

* `api/apis` has nothing to do with API, instead it contains HTTP handlers. Maybe we can rename this to `api/handlers`
* `controllers/apis` has nothing to do with API, it contains CRDs. It does not match the kubebuilder default crd directory name either. Therfore we could
  a) rename it to `controllers\crds` to reflect it contains CRDs
  b) rename it to `controllers\api` to match the kubebuilder convention

**Comment by tcdowney** [comment]
For what it's worth, the Kubebuilder convention for multiple API groups is to have it be `apis`. They recommended that naming in this doc we followed:
https://book.kubebuilder.io/migration/multi-group.html

That said we no longer have multiple groups like `services.`, `workloads.` etc. so I think it's fine to rename it back to `api`. Just wanted to share why it was that way.
