### ISSUE TITLE
[Feature]: Operator can install Korifi without needing HNC

### ISSUE THREAD

**Issue by julian-hj** [cloudfoundry/korifi#1112]
### Background

**As an** Operator
**I want** fewer dependencies
**So that** I can more easily run Korifi

### Acceptance Criteria

**GIVEN** I have docker and kind installed
**WHEN I** use the `deploy-on-kind.sh` script
**THEN I** see that HNC no longer gets installed
**AND I** can still use the product to create orgs and spaces and `cf push`

### Dev Notes

* A separate story will cover the updates to installation instructions.
* #769 covers the spike work we did to try this out. That work did not include watching existing roles, rolebindings, and secrets to propagate changes. It also didn't include the finalizer we will need to delete namespaces when a CFOrg or CFSpace gets deleted.
* Proposed implementation is covered in more detail in [this proposal document](https://docs.google.com/document/d/1AVZPcoOphbWU8tVJ2gM7UkEC0EvHaki6scWgp8DuCDY/edit#)
* Consider switching Eirini namespaced roles to a ClusterRole so that we don't have to propagate them. We will still need the rolebinding to be created in new namespaces, but shouldn't need to watch for updates.
* We will need to watch the root namespace for the appearance of new RoleBindings

**Comment by clintyoshimura** [comment]
Changes that need to be done:

- Orgs
  - [ ] Propagation of resources at creation time
  - [ ] Propagation of added/changed/deleted resources
  - [ ] Finalizer deletion of managed namespaces  

- Spaces
  - [ ] Propagation of resources at creation time
  - [ ] Propagation of added/changed/deleted resources
  - [ ] Finalizer deletion of managed namespaces  
 
 - [ ] remove installing HNC from `deploy-on-kind` script
 - [ ] Remove code that waits for HNC in API
 - [ ] Remove code that waits for HNC in tests

**Comment by clintyoshimura** [comment]
In order to switch the eirini roles to ClusterRoles we may need to make changes to eirini-controller. That might be more appropriate to do as a separate story.

**Comment by julian-hj** [comment]
A/C passed
