### ISSUE TITLE
[Feature]: Running Processes generate RunWorkload resources instead of LRPs

### ISSUE THREAD

**Issue by matt-royal** [cloudfoundry/korifi#1145]
### Blockers/Dependencies

#1234 

### Background

**As a** developer who wants to extend korifi
**I want** running processes to be managed via RunWorkload resources
**So that** I can use them as an extension point to implement different run workflows

### Acceptance Criteria

**GIVEN** a korifi installation on a k8s cluster
**WHEN I** start a running app (e.g. via `cf push`)
**THEN I** should see that a RunWorkload resource is created
**AND** eventually the process information returned from the shim should show that all instances of the process are running (e.g. via `cf app`)
**AND** I should be able to curl the app's URL and get a response (assuming it's an http app)
**WHEN I** scale the process' instances up or down
**THEN** eventually the process information returned from the shim should show that all instances of the process are running (e.g. via `cf app`)
**AND** when I look at the README, INSTALL, and korifi website
**THEN** I no longer find references to Eirini installation.

### Dev Notes

Handle `RunWorkload` in the same way we handle eirini `LRP` resources. In other words, if we would delete one LRP and create another upon scale, then do the same with `RunWorkload`

When this story is complete, the `korifi/api` and `korifi/controllers` directories should contain no references to eirini resources, packages, etc.

Note that this story completely removes the dependency on Eirini, since we are inlining it in the other code. Install-dependencies scripts should no longer install Eirini.

**Comment by akrishna90** [comment]
We were not be able to completely remove references to `eirini` bcos it is now being used to run [`tasks` in `korifi`](https://github.com/cloudfoundry/korifi/issues?q=is%3Aopen+is%3Aissue+label%3ATasks).
