### ISSUE TITLE
[Chore]: Write e2e test to validate that app environment is being set effectively

### ISSUE THREAD

**Issue by matt-royal** [cloudfoundry/korifi#1146]
This description was EDITED as the story seems to be done. The instructions below cover what is left to be done as a chore

We already seem to have a [test](https://github.com/cloudfoundry/korifi/blob/d03b3dffb5343e830f31fe2d951d20d5a3d29c25/tests/e2e/apps_test.go#L387-L416) that attempts to validate that by setting an env var, restarting the app and then getting the env var, but this test does not seem to be doing the right thing, as it is getting the env vars from the api and not from the running app. 

Testing the env endpoint makes sense, but does not require app restart and is potentially a better fit for an api unit test

This test should be reworked to push an app that can dump its effective environment, like [this one](https://github.com/emalm/cf-acceptance-tests/tree/cf-k8s-node/assets/node)

**Comment by clintyoshimura** [comment]
We will need to enable the e2e test that was removed as part of the the preceding issue:
https://github.com/cloudfoundry/korifi/pull/1222/files#diff-862c21f893b8783a8b6ceaf31c991167437eed916f4c9e10974fdbd09bb6cabaL306
In order to pass, we have to update the get app environment handler to return the vcap services secret ref. Currently the env is populated on the runtime workload but no longer exposed as plaintext by the api.

**Comment by acosta11** [comment]
After https://github.com/cloudfoundry/korifi/commit/f0c1505948d99b3586ae0582892220f3ffa2c76d made it to `main`, the RunWorkload env is configured appropriately with secret references, so the remaining scope is only E2E testing with a custom app that dumps its env to an api client. We will circle back and reprioritize that testing enhancement once higher priority issues get finished this week.

**Comment by gcapizzi** [comment]
This is effectively a chore now, as the user-facing bits have been completed, so I'm moving this to the chores column.

**Comment by akrishna90** [comment]
We noticed that assets folder contained zips for apps that were being deployed in e2e tests. Having it this way would be hard to maintain as there wouldn't be a way to keep track of changes to zip. Matt brought up a great point about not maintaining out own version and instead just vendir-ing required apps from CATS.

Action Plan:
- [x] update `vendir.yml` to sync the required apps
- [ ] update `SynchronizedBeforeSuite` in e2e suite tests with a helper func that zips these apps to a tmpdir
- [ ] update the tests to looks for zips in the new tmpdir
- [ ] add the new test for fetching env variables from app
