### ISSUE TITLE
INSTALL.md references missing configuration files

### ISSUE THREAD

**Issue by nathanweeks** [cloudfoundry/korifi#1154]
A couple configuration files in the INSTALL.md may be misnamed or missing:

https://github.com/cloudfoundry/korifi/blob/9a2e8c8b1d27fb11cec8ea94efb4a5069453a6b3/INSTALL.md?plain=1#L48-L54

The only YAML file in the repo that has `kpackImageTag` is `kpack-image-builder/config/base/controllersconfig/kpack_build_controllers_config.yaml` ; is that the intended file?

https://github.com/cloudfoundry/korifi/blob/9a2e8c8b1d27fb11cec8ea94efb4a5069453a6b3/INSTALL.md?plain=1#L56-L62

Should this be `api/config/base/apiconfig/korifi_api_config.yaml`?

**Comment by nathanweeks** [comment]
Thanks for the clarification! Other than the extensions on those two files being `.yml` in the Korifi 0.1.0 release tarball instead of `.yaml` as listed in the INSTALL.md, they're both there as advertised.

**Comment by gcapizzi** [comment]
Thanks @nathanweeks, good catch! I have opened #1162 to fix them.
