### ISSUE TITLE
[Chore] Flatten the `controllers/controllers` Directory

### ISSUE THREAD

**Issue by davewalter** [cloudfoundry/korifi#1176]
### Background

When we switched to a multi-group setup for our controllers, we introduced sub-directories of `controllers/controllers` based on the group names. Now that we have switched everything to `korifi.cloudfoundry.org`, new controllers that we add using `kubebuilder` will be added to `controllers/controllers`. We should move all the existing controllers to this location for consistency.

### Action to take

Move all the existing controllers to `controllers/controllers`.

### Impact

Make the code easier to maintain.

**Comment by georgethebeatle** [comment]
Is this still relevant? We are no longer using kubebuilder directly. As controllers grow in number maybe grouping them semantically giving them som structure?

**Comment by davewalter** [comment]
If we don't think it is causing us any pain, I think we can go ahead and close it.
