### ISSUE TITLE
[Chore]: Release tarball should include `INSTALL.md`

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1199]
### Background

The `INSTALL.md` on our `main` branch is now broken for our `v0.1.0` release, as we don't install HNC anymore. This is normal, as it should track the code in `main`, but it's a bit misleading for people trying to install the release.

I have [added a warning](https://github.com/cloudfoundry/korifi/pull/1198) to the file and a correct link to the [release notes](https://github.com/cloudfoundry/korifi/releases/tag/v0.1.0), but it would help if we could just include the right version of the file in the tarball.

Ideally it would be great to fix the existing tarball too, it shouldn't be a problem as we're just adding a Markdown file.

### Action to take

* Change the release pipeline to include `INSTALL.md` in the released tarball.
* Manually fix the `v0.1.0` tarball to include the **correct version** of the file.

### Impact

This should make it a lot less likely for people to accidentally try to use the wrong installation instructions and fail.

**Comment by kieron-dev** [comment]
I've put the historically correct INSTALL.md file in the 0.1.0 release tarball and fixed the script.
