### ISSUE TITLE
[Explore]: Supporting Pod Security in Kubernetes 1.25

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1202]
### Background

Kubernetes 1.25 [will remove `PodSecurityPolicy`](https://kubernetes.io/docs/concepts/security/pod-security-policy/), which we are still using. The [Pod Security admission controller](https://kubernetes.io/docs/concepts/security/pod-security-admission/) is its designated replacement, and we should migrate to it.

The new Pod Security admission controller works via [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/) that can be applied at the namespace level. The [`restricted`](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted) standard seems to fit the [Eirini `PodSecurityPolicy`](https://github.com/cloudfoundry/eirini-controller/blob/b2865ef7e7be705eb9f814e03b07e400277536eb/deployment/helm/templates/workloads/app-rbac.yml#L40-L73), but we should take a deeper look at what adopting it would imply.

### Acceptance Criteria

One or more stories/chores to migrate Korifi from `PodSecurityPolicy` to the Pod Security admission controller. Keep in mind that we need to do this for both `LRP`s/`RunWorkload`s and `Task`s.

### Timebox

No timebox

### Dev Notes

* [Migrate from PodSecurityPolicy to the Built-In PodSecurity Admission Controller](https://kubernetes.io/docs/tasks/configure-pod-container/migrate-from-psp)
  - This provides a list of things to check before doing the switch - **important**!
* [Pod Security Standards](https://kubernetes.io/docs/concepts/security/pod-security-standards)
* [Pod Security Admission](https://kubernetes.io/docs/concepts/security/pod-security-admission/)

**Comment by kieron-dev** [comment]
We tried annotating a cf space namespace with the labels:
```
pod-security.kubernetes.io/audit=restricted
pod-security.kubernetes.io/enforce=restricted
```

This enables pod security at the highest restricted level on the namespace.

Then we attempted to push an app. The kpack logs show that the security policy requires certain policies to be set on the pod spec, namely:
```
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault # or Localhost
```

We hacked a kpack build-pod spec and proved that adding these to the container and all init containers allowed the pod to be created.

**Comment by kieron-dev** [comment]
We applied the above change by copying the release yaml (foo.yml) to korifi/dependencies/kpack-release-0.5.2.yaml and deploying korifi on kind. We also made the artifact registry public. This will be deleted after this explore.

Now the kpack build succeeds, but the statefulset fails to create its pods:
```
Events:
  Type     Reason        Age                   From                    Message
  ----     ------        ----                  ----                    -------
  Warning  FailedCreate  86s (x16 over 4m10s)  statefulset-controller  create Pod cf-proc-4b3daf83-3e6f-479f-a91e-7f6d57eb-97d6eb2e8e-0 in StatefulSet cf-proc-4b3daf83-3e6f-479f-a91e-7f6d57eb-97d6eb2e8e failed error: pods "cf-proc-4b3daf83-3e6f-479f-a91e-7f6d57eb-97d6eb2e8e-0" is forbidden: violates PodSecurity "
restricted:latest": unrestricted capabilities (container "opi" must set securityContext.capabilities.drop=["ALL"])
```

**Comment by kieron-dev** [comment]
We changed korifi to set the appropriate labels on cf-space namespaces:
```
diff --git a/controllers/controllers/workloads/shared.go b/controllers/controllers/workloads/shared.go
index 95db433..5110f2e 100644
--- a/controllers/controllers/workloads/shared.go
+++ b/controllers/controllers/workloads/shared.go
@@ -56,6 +56,8 @@ func createOrPatchNamespace(ctx context.Context, client client.Client, log logr.
                for key, value := range labels {
                        namespace.Labels[key] = value
                }
+               namespace.Labels["pod-security.kubernetes.io/enforce"] = "restricted"
+               namespace.Labels["pod-security.kubernetes.io/audit"] = "restricted"
                return nil
        })
        if err != nil {
```

and eirini to set the appropriate container security context:
```
diff --git a/k8s/stset/lrp_to_statefulset.go b/k8s/stset/lrp_to_statefulset.go
index b8015a3eb..6c961695e 100644
--- a/k8s/stset/lrp_to_statefulset.go
+++ b/k8s/stset/lrp_to_statefulset.go
@@ -107,6 +107,9 @@ func (c *LRPToStatefulSet) Convert(statefulSetName string, lrp *eiriniv1.LRP, pr
                        Ports:           ports,
                        SecurityContext: &corev1.SecurityContext{
                                AllowPrivilegeEscalation: &allowPrivilegeEscalation,
+                               Capabilities: &corev1.Capabilities{
+                                       Drop: []corev1.Capability{"ALL"},
+                               },
                        },
                        Resources:      getContainerResources(lrp.Spec.CPUWeight, lrp.Spec.MemoryMB, lrp.Spec.DiskMB),
                        LivenessProbe:  livenessProbe,
```

And we can successfully push dora and curl its endpoint.

**Comment by kieron-dev** [comment]
To complete, we need to:
* {Talk to / write a story to talk to} kpack team about setting container security contexts on their build-pods so they support the restricted context. Or perhaps allow the level to be configurable
* Write a story to accept a pod security level in korifi config, and apply that on cf-space namespaces
* Write a story to accept a pod security level in eirini-controller, and apply the appropriate container security context to make workload pods work in that context
* Write a story to apply the restricted pod security level to korifi controlled namespaces (-api, -controllers, ...).

**Comment by danail-branekov** [comment]
> {Talk to / write a story to talk to} kpack team about setting container security contexts on their build-pods so they support the restricted context. Or perhaps allow the level to be configurable
https://github.com/pivotal/kpack/issues/972
