### ISSUE TITLE
[Feature]: New tasks should request the same CPU as their associated app

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1203]
### Background

**As a** developer
**I want** to run tasks
**So that** I can execute one-off workloads

### Acceptance Criteria

- **WHEN I** create a task
  **THEN I** I see the task pod has a [CPU request](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) matching the one of the associated app's [`web` process](https://v3-apidocs.cloudfoundry.org/version/3.122.0/index.html#processes) (`spec.containers[].resources.requests.cpu` should be equal on the task pod and the app pod)

### Dev Notes

* `eirini-controller` [currently ignores](https://github.com/cloudfoundry/eirini-controller/blob/b2865ef7e7be705eb9f814e03b07e400277536eb/k8s/jobs/task_to_job.go) the [`cpuWeight` field on `Task`](https://github.com/cloudfoundry/eirini-controller/blob/b2865ef7e7be705eb9f814e03b07e400277536eb/pkg/apis/eirini/v1/task.go#L45), so we'll have to fix that for this to work.

**Comment by kieron-dev** [comment]
@gcapizzi - I've found the following in the [cf v3 api docs for procfiles](https://v3-apidocs.cloudfoundry.org/version/3.122.0/index.html#procfiles):
> #### Web process
> `web` is a [special process type](https://v3-apidocs.cloudfoundry.org/version/3.122.0/index.html#web-process-type) that is required for all applications. The `web` `PROCESS_TYPE` must be specified by either the buildpack or the Procfile.

It is that web process that gets the memory specified using `-m` in the CF CLI. When pushing dora, the other worker process takes the default 1GB memory even if another value is specified on the command line.

So, is it reasonable for this story to calculate the task CPU from the memory used by the `web` process?

**Comment by gcapizzi** [comment]
@kieron-dev oh! Yes absolutely, it totally makes sense! I have updated acceptance to reflect this.
