### ISSUE TITLE
[Feature]: Removing the admin role from a user does not remove admin privileges in orgs and spaces

### ISSUE THREAD

**Issue by kieron-dev** [cloudfoundry/korifi#1204]
### What happened?

1. Create a user
2. Assign that user the cf-admin role by creating a role binding in the root `cf` namespace to the cluster role `korifi-controllers-admin`
3. See that the rolebinding is propagated to existing orgs and spaces so that the new user has admin privileges in all orgs and spaces.
4. Remove the admin role from the new user by deleting the rolebinding in the `cf` namespace
5. See that the rolebindings are not deleted in the orgs and spaces, so the user still has admin privileges in all orgs and spaces.

Note that this also applies to setting a user as an org-manager, and then unsetting that role.

### What you expected to happen

When a rolebinding has been propagated to descendent org and space namespaces, deletion of the rolebinding in the original namespace should also propagate to the descendent org and space namespaces.

### Acceptance Criteria

GIVEN there exists a user with a rolebinding to the korifi-controllers-admin role in the `cf` namespace
AND there are some existing orgs and spaces
WHEN I remove admin privileges from the user by deleting the rolebinding in the `cf` namespace
THEN propagated rolebindings for that user in the orgs and spaces are also deleted
AND
GIVEN there exists a user with a rolebinding to the OrgManager role in some org
WHEN I remove the rolebinding for that user in the org namespace
THEN propagated OrgManager rolebindings for that user are removed from the spaces in that org.

### How to reproduce it (as minimally and precisely as possible)

E.g. against a local KinD deployment
```
cf api https://localhost --skip-ssl-validation
cf login # as cf-admin
cf create org org1
cf create space -o org1 space1
./scripts/create-new-user jim
kubectl -n cf create rolebinding jim-admin --user jim --clusterrole korifi-controllers-admin
# see the 'jim-admin' rolebinding copied to the namespaces for org1 and space1
kubectl -n cf delete rolebinding jim-admin
# see the copied 'jim-admin' rolebindings have not been deleted from the org1 and space1 namespaces
```

### Anything else we need to know?

If 'jim' was an ordinary user before being made admin, there would be a default-root-ns rolebinding in the cf namespace, and this is sufficient for significant mischief to be made with the remaining admin rolebindings via the cf CLI or by curling the API.

### Environment

Revision of codebase: e93439eb98e8438761a5be2529eaf5aba06af583
Kubernetes version (use `kubectl version`):
Cloud provider or hardware configuration:
Others:

### Dev Notes
- How about secrets? Maybe we don't expect secrets to get deleted?
- As of right now, `cf unset-org-role` doesn't work through the CLI, since we get a 404 when the CLI calls the API to look up the user. So this isn't testable via cli. Maybe we want to make a separate story for that action?

**Comment by julian-hj** [comment]
I'm wondering if we could manage this by adding a finalizer to the root level rolebinding when we get notified about its creation. That might allow us to get notified about its disposition before it's totally gone and we can no longer find out what it was, and maybe would mean we don't have to inspect the entire tree each time a rolebinding gets deleted.

**Comment by kieron-dev** [comment]
It would definitely be an efficient way. It might suffer from a race where a space is created during the finalisation, and a new copy of the thing we are trying to delete is created and not deleted by the finalisation code. And then nothing would trigger its deletion while the new space exists.

**Comment by julian-hj** [comment]
A/C passed
