### ISSUE TITLE
[Feature]: App Developer can request a "random route" via their app manifest

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/korifi#1206]
### Background

CF app manifests support a `random-route` config option that does the following:

> Creates a random route for the app if true; if routes is specified, if the app already has routes, or if no-route is specified, this field is ignored regardless of its value

It will use the same default apps domain that the `default-route` flag uses, just with a semi-random word as the `host` portion of the route.

A lot of the cf-sample / demo apps that people use have the `random-route` property set. Currently these apps won't get a route assigned when pushed which is unfortunate. These sample apps don't usually use the `default-route` property because other demo apps are likely squatting on the same route (e.g. if you push an app named `app` it is likely another demo app already has the `app.example.com` domain in use).

**As an** App Developer who doesn't care about the app's actual route (e.g. when experimenting or giving a demo)
**I want** to be able to use the `random-route` option in my manifest
**So that** I can get a route assigned to my app that won't collide with other routes deployed on the cluster

---

### Acceptance Criteria

All of these scenarios use an app with a manifest like this declaring `random-route` enabled.

```
--- 
applications: 
- name: dora
  random-route: true
```

---

### App doesn't have a route mapped to it

**GIVEN** I have an app `dora` _without_ a route mapped to it
**WHEN I** `cf push` with the manifest above
**THEN I** get a "random" route assigned like this:

```
$ cf push dora
Pushing app dora to org org / space space as admin...
Applying manifest file /Users/tdowney/go/src/github.com/cloudfoundry/cf-acceptance-tests/assets/dora/manifest.yml...

Updating with these attributes...
  ---
  applications:
+ - name: dora
    random-route: true
Manifest applied

...

name:              dora
requested state:   started
routes:            dora-unexpected-meerkat-gw.weed-wasp.capi.land
...
```

---

### App already has a route mapped to it

**GIVEN** I have an app `dora` _WITH_ a route mapped to it
**WHEN I** `cf push` with the manifest above
**THEN I** do not get a new random route assigned and the old route continues to be mapped to the app

---

### The `--no-route` CLI flag is specified

**GIVEN** I have an app `dora` _without_
**WHEN I** `cf push --no-route` with the manifest above using the `--no-route` flag
**THEN I** do not get a new random route assigned and no route is assigned to the app

```
$ cf push dora --no-route
Pushing app dora to org org / space space as admin...
Applying manifest file /Users/tdowney/go/src/github.com/cloudfoundry/cf-acceptance-tests/assets/dora/manifest.yml...

Updating with these attributes...
  ---
  applications:
+ - name: dora
    no-route: true
    random-route: true
Manifest applied

...
name:              dora
requested state:   started
routes:
last uploaded:     Wed 08 Jun 14:27:23 MDT 2022
stack:             cflinuxfs3
buildpacks:
	name             version   detect output   buildpack name
	ruby_buildpack   1.8.54    ruby            ruby
```

---

### Dev Notes

* https://v3-apidocs.cloudfoundry.org/version/3.117.0/index.html#the-manifest-schema
* Reuse the logic from Cloud Controller
  * The list in CCNG's `AdjectiveNounGenerator` has been sanitized to not produce any potentially offensive route names
  * https://github.com/cloudfoundry/cloud_controller_ng/blob/main/lib/cloud_controller/random_route_generator.rb
  * https://github.com/cloudfoundry/cloud_controller_ng/blob/main/lib/cloud_controller/adjective_noun_generator.rb
* Do we handle the `no-route` property already? If not are we ok with layering it on the part about ignoring `random-route` if its present in this story? `no-route` in general has some more complicated behavior so we'd probably want an explicit one for the rest of that (see https://www.pivotaltracker.com/n/projects/966314/stories/154816070).

**Comment by clintyoshimura** [comment]
We have an additional acceptance criteria for having a default route and random route set at the same time:
### App has default-route and random-route both set to true

**GIVEN** I have an app `dora` _WITH_ default-route and random-route set to true in the manifest
**WHEN I** `cf push` with the manifest
**THEN I** get an UnprocessableEntity error
