### ISSUE TITLE
[Chore]: Introduce onboarding and offboarding issue templates for EMEA

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1211]
### Background

Let's make it easy to onboard and offboard someone who plans to pair with us in EMEA. We can take inspiration from Eirini's [onboarding](https://www.pivotaltracker.com/n/projects/2172361/stories/171856898) and [offboarding](https://www.pivotaltracker.com/n/projects/2172361/stories/172204797) Tracker template stories.

It's important that no entries in the checklist bypass the [CFF requirements for roles](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md).

### Impact

Two new issue templates for EMEA onboarding and offboarding.

**Comment by georgethebeatle** [comment]
Not relevant right now due to low staffing
