### ISSUE TITLE
[Feature]: kubectl user can run an image via RunWorkload (redux)

### ISSUE THREAD

**Issue by matt-royal** [cloudfoundry/korifi#1233]
### Background

**As a** kubectl user
**I want** to be able to run workloads by creating a RunWorkload resource
**So that** developers have an example of how to extend korifi with an alternative workflow

This story is analogous to #1002, which added `BuildWorkload`. 

### Acceptance Criteria

**GIVEN** a korifi deployment (installed with the `korifi/scripts` tooling)
**WHEN I** use kubectl to list deployments
**THEN I** see a dedicated deployment for the `statefulset-runner`

---

**WHEN I** use kubectl to create a `RunWorkload` resource
**THEN I** see that there is a running StatefulSet for the image I specified, with the correct number of replicas, resource requests and limits, ports, liveness and readiness probes, and with the following environment variables set in the same way that eirini-controller does
  - `POD_NAME`
  - `CF_INSTANCE_IP`
  - `CF_INSTANCE_GUID`
  - `CF_INSTANCE_INTERNAL_IP`
 
**WHEN I** use kubectl to describe the `RunWorkload`
**THEN I** see that `status.readyReplicas` matches `spec.instances`

---

**WHEN I** change the `spec.instances` on the `RunWorkload`
**THEN I** see that the `StatefulSet` for that workload has been updated to reflect the change
**WHEN I** use kubectl to describe the `RunWorkload`
**THEN I** see that `status.readyReplicas` matches `spec.instances`

---

**WHEN I** change the `spec.version` on the `RunWorkload`
**THEN I** see that all of the StatefulSet's Pods have been replaced with new Pods (i.e. a full "restart")

---

**WHEN I** delete the `RunWorkload`
**THEN I** see that the StatefulSet has been deleted

---

**WHEN I** examine the `korifi` repository
**THEN I** see a directory at `korifi/statefulset-runner`, which contains a kubebuilder project that does not depend on any files from the rest of the repo

### Dev Notes

This is a replacement for #1065, where we attempted to inline `eirini` as `korifi/statefulset-runner`. The structure of eirini proved too different from our own, and we decided as a team to reimplement its relevant features from scratch (though feel free to take code from eirini where it feels right).

The goal of this story is **minimal feature parity**, and includes:
- Adding a new `RunWorkload` to `korifi/controllers` that's modeled off of Eirini's LRP with some removed fields and small changes (see example below)
- Adding a new kubebuilder sub-project at `korifi/statefulset-runner`, which reconciles `RunWorkload` resources to `statesfulset` resources like Eirini does. This sub-project should not rely on any of the files or configuration from the rest of the codebase and should have its own Makefile. Look at the structure of `korifi/kpack-image-builder` for inspiration.
  - Here are some files in eirini that currently do the translation:
    - https://github.com/cloudfoundry/eirini-controller/blob/master/k8s/reconciler/lrp.go
    - https://github.com/cloudfoundry/eirini-controller/blob/master/k8s/stset/desire.go
    - https://github.com/cloudfoundry/eirini-controller/blob/master/k8s/stset/update.go
- **This eirini-controller behavior will be out of scope for this story**:
  - Setting `CF_INSTANCE_INDEX` on individual pods
  - Creating PodDisruptionBudgets for each StatefulSet
  - Registering Events with the k8s API
  - Exposing statistics via Prometheus
  
  Here's a DRAFT CRD definition in Go for the new resource's spec:

```go
  type RunWorkloadSpec struct {
	// +kubebuilder:validation:Required
	Version     string `json:"version"`
	// +kubebuilder:validation:Required
	Image           string           `json:"image"`
	Command         []string         `json:"command,omitempty"`
	// deprecated: Env is deprecated. Use Environment instead
	Env         []corev1.EnvVar `json:"env,omitempty"`
	Health      Healthcheck       `json:"health"`
	Ports       []int32           `json:"ports,omitempty"`
	// +kubebuilder:default:=1
	Instances int   `json:"instances"`
	MemoryMB  int64 `json:"memoryMB"`
	// +kubebuilder:validation:Minimum:=1
	// +kubebuilder:validation:Required
	DiskMB int64 `json:"diskMB"`
	// +kubebuilder:validation:Format:=uint8
	CPUWeight              uint8             `json:"cpuWeight"`
  }

  type Healthcheck struct {
	Type     string `json:"type"`
	Port     int32  `json:"port"`
	Endpoint string `json:"endpoint"`
	// +kubebuilder:validation:Format:=uint8
	TimeoutMs uint `json:"timeoutMs"`
  }
```

**Comment by tcdowney** [comment]
Maybe now we can rename `MemoryMB` and `DiskMB` to be `MiB` since that's what they are actually using.

**Comment by acosta11** [comment]
After reviewing the BuildWorkload files w/ Julian, I realize we may not want to use the `ext` group, instead just continuing to use `korifi` like the rest of our resources.

**Comment by julian-hj** [comment]
This story is "complete" with some caveats:

- We don't install the statefulsetrunner controller manager by default yet. You have to run `make docker-build` and kind side load the image and then run `make deploy`
- We don't run any of the tests yet in our PR checks. These should be added to our CI in GitHub like the kpack-image-builder was. (i.e. make a new target in the makefile, and then hit that target from GitHub actions)
