### ISSUE TITLE
[Chore]: Fix the usages of Eventually with nested Expect statements to align with Ginkgo's recommendation

### ISSUE THREAD

**Issue by clintyoshimura** [cloudfoundry/korifi#1240]
### Background

According to [Ginkgo's documentation on asynchronous testing](https://onsi.github.io/ginkgo/#patterns-for-asynchronous-testing), when an Expect is used inside an Eventually, a Gomega instance should be passed into the function. The code's usage of Eventually is inconsistent currently.

### Action to take

Fix any instance of Eventually blocks with nested Expects to pass in a Gomega instance to use. ie)
```
Eventually(func(g Gomega) {
    model, err := client.Find(1138)
    g.Expect(err).NotTo(HaveOccurred())
    g.Expect(model.Reticulate()).To(Succeed())
    g.Expect(model.IsReticulated()).To(BeTrue())
    g.Expect(model.Save()).To(Succeed())
}).Should(Succeed())
```

### Impact

This may help with testing inconsistencies and flakes.

**Comment by julian-hj** [comment]
Looking at the docs, inside an eventually loop: `Expect` and `g.Expect` have different meanings.

`Expect` means that a mismatch will cause the test to fail.
`g.Expect` means that the `Eventually` condition isn't met yet and we should keep trying.

So, there are some cases where we still want the first behavior. For example:
```
					Eventually(func() []korifiv1alpha1.CFProcess {
						Expect(
							k8sClient.List(context.Background(), &processList, client.InNamespace(space.Name)),
						).To(Succeed())
						return processList.Items
					}).Should(HaveLen(2))
```

In this case, we are just using `Expect` for error handling, and if we get an error here, we really do want to treat is as a failure and not re-try.

We'll review the uses of Eventually in the code, but we don't think we want to use `Gomega` in all cases.

**Comment by julian-hj** [comment]
Here's an example where we thought the `g.Expect` would give us a cleaner test:
```
Eventually(func() string {
	updatedCFApp := &korifiv1alpha1.CFApp{}
	err := k8sClient.Get(context.Background(), types.NamespacedName{Name: cfAppGUID, Namespace: namespace}, updatedCFApp)
	if err != nil {
		return ""
	}
	return string(updatedCFApp.Status.ObservedDesiredState)
}).Should(Equal(string(cfApp.Spec.DesiredState)))
```
can be rewritten as
```
Eventually(func(g Gomega) {
	updatedCFApp := &korifiv1alpha1.CFApp{}
	g.Expect(k8sClient.Get(context.Background(), types.NamespacedName{Name: cfAppGUID, Namespace: namespace}, updatedCFApp)).To(Succeed())
	g.Expect(updatedCFApp.Status.ObservedDesiredState).To(Equal(cfApp.Spec.DesiredState))
}).Should(Succeed())
```

**Comment by matt-royal** [comment]
> Eventually(func() []korifiv1alpha1.CFProcess {
> 	Expect(
> 		k8sClient.List(context.Background(), &processList, client.InNamespace(space.Name)),
> 	).To(Succeed())
> 	return processList.Items
> }).Should(HaveLen(2))

You can rewrite this case more succinctly as...

```golang
Eventually(func() ([]korifiv1alpha1.CFProcess, error) {
    err := k8sClient.List(context.Background(), &processList, client.InNamespace(space.Name))
    return processList.Items, err
}).Should(HaveLen(2))
```

Eventually and Consistently will fail if any argument after the first is anything other than zero-value. You can read more about it here under "Category 2": https://pkg.go.dev/github.com/onsi/gomega#Eventually

I personally find the distinction between `Expect` and `g.Expect` to be subtle and easy to miss, so I'd prefer that we just agree to always use `g.Expect`. For cases where the Eventually should fail immediately, we can either use the multiple-return-value option above or find other ways to cause an instant failure.

**Comment by danail-branekov** [comment]
Lets fix those case by case as we work on the code
