### ISSUE TITLE
[Chore]: Migrate pairup and postfacto to the eirini acceptance environment

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#1250]
### Background

We are using pairup and postfacto as an integral part of our daily work. These apps are still running on eirini infrastructure on top of cf-for-k8s. This means we still need to maintain an old acceptance environment, which is a waste

### Action to take

- Migrate pairup and postfacto to the korifi acceptance environment
- Setup some uptime monitor such as https://www.statuscake.com/
- Tear down unneeded eirini infrastructure

### Impact

We reduce out overall cost of maintainance by retiring old infrastructure

**Comment by kieron-dev** [comment]
I had a look at doing uptime checks in GCP. It's really easy: https://console.cloud.google.com/monitoring/uptime?project=cf-on-k8s-wg. After I added it, it also offered to check SSL cert validity, so I turned that on too. You can see that in the alerts tab.
