### ISSUE TITLE
[Feature]: Developer can run tasks on a Korifi configured with a private image registry

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1387]
### Background

**As a** developer
**I want** to run tasks
**So that** I can execute one-off workloads

### Acceptance Criteria

**GIVEN** my Korifi uses a private image registry
**AND** an app is running on it
**WHEN I** run a task for the app
**THEN I** I see it working

### Dev Notes

Eirini's `Task` currently needs registry credentials to be [provided explicitly](https://github.com/cloudfoundry/eirini-controller/blob/232989342fc55a21407777969ae02e6b6f380634/deployment/helm/templates/core/task-crd.yml#L182-L187) instead of via a `Secret` reference, which is how we store our registry credentials.

We could choose to:
1. change Eirini to simplify the implementation on the Korifi side and set the ground for the switch to `TaskWorkload`, or
1. leave Eirini unchanged and extract the credentials from the `Secret` in the `CFTask` controller.

**Comment by kieron-dev** [comment]
## Clarification

- Currently eirini-controller has a config option `registry_secret_name`. This value is added to the `imagePullSecrets` of all pods (tasks and lrps)
    - The korifi deployment scripts set this to correspond with the registry secret which is created in the `cf` namespace and propagated down to all spaces
    - This is the only way task pods get the image pull secret from korifi at the moment
- However, the process controller sets image pull secrets on the app workload resource
    - This is the source of truth for the stateful set runner
    - The value actually comes from the API config, which is injected into the package handler, making its way onto the build status via the package spec.
- When we have the task workload resource, this should behave the same, fetching the image pull secrets from the build (droplet) status.
- We can simulate this for the intermediate eirini-controller solution by stopping setting the default image pull secret on the eirini-controller, and only using the image pull secret set on the eirini task
    - This means possibly removing eirini-controller code, unless we can get away with not setting that config value
    - And the korifi task controller should always set the image pull secrets from the droplet status onto the eirini-controller task (and on the task workload, once it exists)
