### ISSUE TITLE
[Feature]: Developer can run tasks on a Korifi deployed without Eirini

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1407]
### Background

**As an** operator
**I want** to replace Korifi's task runner
**So that** I can customise the way my system runs tasks

### Acceptance Criteria

**WHEN** I install Korifi following the [installation instructions](https://github.com/cloudfoundry/korifi/blob/main/INSTALL.md)
**THEN I** see the instructions don't include an [`eirini-controller` installation step](https://github.com/cloudfoundry/korifi/blob/main/INSTALL.md#eirini-controller)
**AND I** see they include a `job-task-runner` installation step
**AND I** can perform [any task operation](https://github.com/cloudfoundry/korifi/issues?q=is%3Aissue+label%3ATasks) successfully

### Dev Notes

* This is about swapping out `eirini-controller` and its `Task` resource for the new `job-task-runner` and `TaskWorkload`.
* Once this is done, we should also replace `eirini-controller` with `job-task-runner` in our docs and scripts.

**Comment by kieron-dev** [comment]
Note: the work is probably complete in the issues/1407-use-job-task-workload-runner branch, but e2e fails because of #1490
