### ISSUE TITLE
[Chore]: Rename RunWorkload to AppWorkload

### ISSUE THREAD

**Issue by matt-royal** [cloudfoundry/korifi#1416]
### Background

We introduced the `RunWorkload` before Task support was added to korifi, so there was no ambiguity about what was "running". This is no longer the case now that we have two types of run workloads, with `TaskWorkload` incoming (see the [Task Epic](https://github.com/cloudfoundry/korifi/issues/897)). Renaming the `RunWorkload` will remove this ambiguity.

### Action to take

Rename the `RunWorkload` to `AppWorkload` and make no other CRD changes. Update any code that uses the `RunWorkload` type.

Also rename the label used for this Epic ("Build and Run Workloads") to match the new resource name.

### Impact

This will give us a less ambiguous name for the workload backing CFApp/CFProcess. It might be considered a breaking change, but to our knowledge no one else has built on top of the `RunWorkload` so far and its interface is not documented publicly.

**Comment by matt-royal** [comment]
We've had some discussion about alternative names to `AppWorkload`. The main advantages of this name are that it's relatively short and easy to say and type. The downside is that it `AppWorkload` is really tied to a `CFProcess` more than a `CFApp`, so the name is slightly incorrect. That said, Processes belong to Apps, so these are actually workloads for an App, even if an App can have more than 1 at a time. In practice, most Apps only have 1 Process anyway.

If you have alternative naming proposals, please chime in via comments.

**Comment by gcapizzi** [comment]
The only sensible alternative I can think of is using `LongRunningWorkload` for `RunWorkload` and `OneOffWorkload` for `TaskWorkload`:
- they state very clearly their purpose and what they do;
- they are abstracted from any CF/Korifi concept;
- they're not that bad to use in conversation?

**Comment by matt-royal** [comment]
I agree with you on the first two points, @gcapizzi, but both of those names are long to type and to say so I'd rather not use them.
