### ISSUE TITLE
[Chore]: Reduce complexity of controller Reconcile functions

### ISSUE THREAD

**Issue by acosta11** [cloudfoundry/korifi#1437]
### Background

We now have a few instances of Code Climate warnings for breaching complexity thresholds in controller Reconcile functions. To continue getting warnings about excessive complexity, explore how we might refactor some of the common resource lifecycle code to minimize complexity outside of the business logic of the function and return to below the threshold.

### Action to take

Explore some refactors to reduce complexity of Reconcile functions.

### Impact

Reduce the complexity of the Reconcile functions below the configured threshold so we can catch excessive increases in complexity in the future.

### Dev Notes

Consider:
- Helper functions for resource lifecycle concerns like finalizers and owner refs
- Helper functions for fetching related resources required for reconcile and subsequent error cases when those fetches fail

**Comment by danail-branekov** [comment]
We have had a couple of rounds on controllers refactoring, e.g. introducing the `PatchingReconciler`, refactoring cforg/cfspace controllers, etc. Code climate currently does not report issues on controllers, therefore closing
