### ISSUE TITLE
[Feature]: Assign ServiceAccount for application pods

### ISSUE THREAD

**Issue by akrishna90** [cloudfoundry/korifi#1484]
### Blockers/Dependencies

NA

### Background

We have missed setting `ServiceAccountName` in the pod spec template when converting `AppWorkloads` into `StatefulSets` or `TaskWorkloads` into `Job`s. Kubernetes is currently assigning `default` ServiceAccount(SA) to application pods. Using `default` SA to run pods is not very desirable when running on OpenShift like environments, where you would need to bind SA to SCCs(Security Context Constraints).

**As a** Kubernetes operator
**I want** to see application pods use a serviceAccount other than `default`
**So that** I can define SCCs on OpenShift like environments. 

### Acceptance Criteria

**GIVEN** I have Korifi installed
**WHEN I** `cf push` an app
**AND I** inspect the pods
**THEN I** see pods using a custom SA

**GIVEN** I have Korifi installed
**AND I** have pushed an app
**WHEN I** `cf run-task` on the app
**AND I** inspect the task pods
**THEN I** see pods using a custom SA

### Dev Notes

- we should define a new ServiceAccount. It could be named something like `korifi-app` or `korifi-workloads`
- we may want to add configurable logic to the space controller so that we don't have to hard code service account creation (like we do with kpack-service-account today).

**Comment by gcapizzi** [comment]
Hi @akrishna90! Would this entail adding a new `serviceAccountName` field to `AppWorkload` or would it be a config parameter for the `statefulset-runner` which would get directly injected in the `StatefulSet`? Whichever way we go, we should do the same for `TaskWorkload`s. Shall we expand this story to do that?

**Comment by akrishna90** [comment]
Yeah! We should definitely do the same with `TaskWorkload`. Please feel free expand this story to capture the additional scope. We haven't `IPM'd` this story yet.  I can't remember if we had a discussion on implementation details.

**Comment by gcapizzi** [comment]
Done!

**Comment by tcdowney** [comment]
It might make sense to put this on the `*Workload` objects. That aligns with the kpack model, but then again we might not need that level of flexibility.

```
apiVersion: kpack.io/v1alpha2
kind: Build
metadata:
  name: sample-build
spec:
  tags:
  - sample/image
  serviceAccountName: service-account
```

**Comment by gcapizzi** [comment]
Also: how does this interact with #1492? Do we want service accounts to me mounted in our pods at all?
