### ISSUE TITLE
[Chore]: Add AppWorkload.spec.buildRef

### ISSUE THREAD

**Issue by matt-royal** [cloudfoundry/korifi#1525]
### Background

To support the idea of a combined builder-runner component (as opposed to separate deployments to reconcile BuildWorkload and AppWorkload), we need to provide a way to link the AppWorkload to the CFBuild that generated its image.

### Action to take

- Add the same `spec.buildRef` field to `AppWorkload` that exists on `BuildWorkload`
- Change the CFProcess controller to set this field on `AppWorkload`

### Impact

After this change, alternative build+run implementations will be able to connect a BuildWorkload and AppWorkload together based on their namespace and `spec.buildRef` fields.

**Comment by gcapizzi** [comment]
It sounds wrong to have the lower level resources (`AppWorkload`/`BuildWorkload`) depend on the higher level ones (`CFBuild`): how does this work? Does the `buildRef` have to be a `CFBuild` or is it more of a duck type?

**Comment by matt-royal** [comment]
@gcapizzi `buildRef` is a direct reference to a CFBuild in the same namespace. The goal in adding this was to have a single field to link Build and AppWorkloads from the same "origin" so that they can be connected easily by a combined builder+runner. There may be a better way to do this, though, that doesn't directly link to a higher level resource, like you mentioned. 

When I was first writing this, I had it as a `buildWorkloadRef`, but then I saw that `BuildWorkload` already had `buildRef` so I went with that. `BuildWorkload.metadata.name`. That would also allow us to remove the `buildRef` field on the `BuildWorkload`, since we clearly weren't using it before (it was empty in practice). What do you think?

**Comment by gcapizzi** [comment]
Definitely much better for `AppWorkload` to refer to `BuildWorkload` as at least they're at the same level of abstraction. Question: if it's just correlation we're after, can't we just have some sort of correlation id? Maybe as a label/annotation?

**Comment by matt-royal** [comment]
A correlation ID could work, but I'm not sure I see a benefit to making it more abstract when the link we want to establish is that the AppWorkload is running the output of a specific BuildWorkload.

RE labels and annotations, I've generally avoided using them in a "load bearing" way, since they're not a codified part of a CRD that we can easily validate (short of a validating webhook)

**Comment by gcapizzi** [comment]
The problem I see is that this link is not necessary something runners and builders will want to establish most of the times, as they're usually separate and decoupled implementations - if a specific implementation does, then I'd rather see that solved via metadata.

**Comment by matt-royal** [comment]
While not every implementation will use the field, it will be essential information for those that do. If we change the label format or stop including it, those implementations will break without warning. If we keep that information in the spec, then it can be required in the schema and schema changes will be advertised through the CRD.

**Comment by danail-branekov** [comment]
I might be a bit late to the party, but having a reference to the build workload in the app workload spec sounds weird to me. From my point of view, as a kubectl user, I should be able to get any object's spec, use the same namespace and a different name in the metadata, and as a result get a valid appliable yaml. In other words, my understanding of the spec is 'input args to create an object'.
Now having the buildworkload reference in the spec violates this understanding as an app workload created the way above would simply not be related to that build workload.

Having said this, I feel that the right place for this reference is the app workload status, rather than its spec. Then controllers that find this reference important  could set a 'valid' condition on the app workload, and controllers that do not care would do nothing.

**Comment by matt-royal** [comment]
@danail-branekov The goal here is to help the runner identify which BuildWorkload build the image used in this AppWorkload, for cases when the builder and runner coordinate or are the same component. The reconciler owns the status field and korifi only ever sets metadata and spec fields. Given that, this information can't live on the status field.

Given the lack of agreement on this, I'm going to revert the merge commit for the PR that implemented this chore. A hypothetical builder-runner may be able to do the correlation based on the image URL alone, so we may not end up needing this feature. I'll write up a new issue and solicit feedback if that proves not to be true.
