### ISSUE TITLE
[Bug]: Install instructions don't work on kind

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1552]
### What happened?

Trying to follow the [install instructions](https://github.com/cloudfoundry/korifi/blob/main/INSTALL.md) on kind won't work. In particular, [ingress](https://kind.sigs.k8s.io/docs/user/ingress/) needs to be configured properly. Also, we should instruct people on how to properly use a local container registry.

### What you expected to happen

I expect to see instructions in our `INSTALL.md` specifying the right thing to do to install Korifi on kind. We don't want to advertise `deploy-on-kind.sh` (at least not yet), but provide reasonable instructions.

### Acceptance Criteria

GIVEN I have kind installed on my machine
WHEN I follow the instructions in `INSTALL.md` to install Korifi
THEN I see it working

### How to reproduce it (as minimally and precisely as possible)

Try to install Korifi on kind following `INSTALL.md`.

### Anything else we need to know?

[Slack thread](https://cloudfoundry.slack.com/archives/C0297673ASK/p1661178931841559) reporting the issue.

**Comment by georgethebeatle** [comment]
It was discussed that this bug should wait for the distribution work which is planned for next release, because it will greatly influence what the readme looks like.
