### ISSUE TITLE
[Chore]: Use "builderName" and "runnerName" instead of "ReconcilerName"

### ISSUE THREAD

**Issue by matt-royal** [cloudfoundry/korifi#1621]
### Background

We've had considerable conversation about the current design of the `AppWorkload` and `BuildWorkload` resources and how reconcilers are mapped/assigned to workloads. See...
- https://docs.google.com/document/d/1JdRenrvYrzn3YbDKoZoqbZV4OuJeKs72q5-Y1usiV6I/edit?disco=AAAAeUOXHTg
- https://cloudfoundry.slack.com/archives/C0297673ASK/p1660670574172819

For now, it seems that the best path forward is to keep the same general design, but change the naming to better abstract these relationships.

### Action to take

* Rename the `AppWorkload.spec.reconcilerName` spec property to `runnerName`
* Rename the `BuildWorkload.spec.reconcilerName` spec property to `builderName`
* Rename the `BuildReconcilerInfo` CRD to `BuilderInfo`
* Rename the various `appReconciler` config values in korifi to `runnerName`
* Rename the various `buildReconciler` config values in korifi to `builderName`
* Update logic in `korifi`, `kpack-image-builder` and `statefulset-runner` to use these updated names

### Impact

The general design will be the same, but hopefully these new names are more cohesive and feel less like visible implementation details.

**Comment by davewalter** [comment]
After talking with Matt, we came up with an alternate set of new names to avoid explicitly calling out the reconciler (implementation) name in the resource configuration:

* Rename the `AppWorkload.spec.reconcilerName` spec property to `runnerName`
* Rename the `BuildWorkload.spec.reconcilerName` spec property to `builderName`
* Rename the `BuildReconcilerInfo` CRD to `BuilderInfo`
* Rename the various `appReconciler` config values in korifi to `runnerName`
* Rename the various `buildReconciler` config values in korifi to `builderName`

We also talked about the possibility of allowing operators and application developers to choose a different builder and runner implementation per org/space/app. If we decide to implement something like this, it is possible that these fields could need to be renamed again or even become obsolete, so we may want to hold off on renaming them until we have explored this possibility.

**Comment by matt-royal** [comment]
I think that @davewalter 's suggestion is better than the original contents of the story, so I'm going to swap them in. Here are the original actions for posterity:

- Change `AppWorkload.spec.reconcilerName` to `workloadClassName`
- Change `BuildWorkload.spec.reconcilerName` to `workloadClassName`
- Rename the `BuildReconcilerInfo` CRD to `BuildWorkloadClass`
- Rename the various `buildReconciler` config values in `korifi` to `buildWorkloadClassName`
- Rename the various `appReconciler` config values in `korifi` to `appWorkloadClassName`
- Update logic in `korifi`, `kpack-image-builder` and `statefulset-runner` to use these updated names
