### ISSUE TITLE
[Feature]: Specifying non-default buildpack via legacy manifest key fails

### ISSUE THREAD

**Issue by matt-royal** [cloudfoundry/korifi#1633]
### Blockers/Dependencies

#1632 

### Background

**As a** user of deprecated CF manifest field `applications[].buildpack`
**I want** to receive a clear error when I specify any value other than `"default"` or `"null"`
**So that** I know that only buildpack auto-detect is supported

### Acceptance Criteria

**GIVEN** a deployment of korifi and an existing, targeted space
**WHEN** I apply the manifest below via `cf apply-manifest`
**THEN** I see an error message explaining that only buildpack auto-detection is supported

---

**WHEN** I update the manifest to set `default` for the buildpack
**AND** I apply it again
**THEN** I see no error

---

**WHEN** I update the manifest to set `"null"` for the buildpack
**AND** I apply it again
**THEN** I see no error

---

Here's the manifest contents

```yaml
applications:
- name: my-app
  buildpack: paketo-buildpacks/java
```

### Dev Notes

Most of the work for this was done in #1171 and #1632. All that remains is the following:

- Add the `buildpack` field to the manifest payload struct
- Change the buildpack struct's `ToMessage` method to convert `buildpack` into `buildpacks` on the message. If the value is `default` or `null`, then leave `buildpacks` as empty.

**Comment by kieron-dev** [comment]
Note, you need to go a bit beyond `apply-manifest` to see the error. A `cf push` is sufficient, as is an `apply-manifest` to an existing pushed app followed by `cf restage`. This is because the error is triggered in the kpack-image-builder, which is only invoked when a buildworkload is reconciled, and `apply-manifest` alone will not cause that.
