### ISSUE TITLE
[Bug]: Cannot list CFOrgs created as admin user

### ISSUE THREAD

**Issue by adamfowleruk** [cloudfoundry/korifi#1710]
### What happened?

When using cf create-org the CFOrg entry is created in the cf namespace, but a cf o call does not list any of those created.

### What you expected to happen

The org to be listed if successfully created by the same user.

### Acceptance Criteria

GIVEN An admin user accessing cf on k8s
WHEN I call cf create-org and then interact with the new org
THEN I can successfully list, target, and create spaces in the org

### How to reproduce it (as minimally and precisely as possible)

❯ cf create-org MyOrg
Creating org MyOrg as kubernetes-admin...
OK

TIP: Use 'cf target -o "MyOrg"' to target new org
❯ cf target -o MyOrg
Organization 'MyOrg' not found.
FAILED
```sh
❯ cf o
Getting orgs as kubernetes-admin...

No orgs found.
❯ kubectl get CFOrg -n cf
NAME                                          DISPLAY NAME   AGE
cf-org-47ca075f-302a-4339-ad4b-d017b24d164f   MyOrg          15s
cf-org-fe4d0d21-9169-4995-9c5a-972a2dc34059   test           82m
❯ cf create-org MyOrg2
Creating org MyOrg2 as kubernetes-admin...
OK

TIP: Use 'cf target -o "MyOrg2"' to target new org
❯ kubectl get CFOrg -n cf
NAME                                          DISPLAY NAME   AGE
cf-org-47ca075f-302a-4339-ad4b-d017b24d164f   MyOrg          26s
cf-org-8d192488-d31a-420b-a405-f83bf25c89df   MyOrg2         4s
cf-org-fe4d0d21-9169-4995-9c5a-972a2dc34059   test           82m
❯ cf o
Getting orgs as kubernetes-admin...

No orgs found.
```

### Anything else we need to know?

Using an EKS IAM user with username of format `adam.fowler@CLUSTERNAME.REGION.eksctl.io` which worked fine to install korifi.

Originally used a `cf-admin` user as the admin username, but changed post installation to my username as I could not admin the install with that service account. Can successfully cf login and execute cf create-org. Using `cf` namespace. Have validated correct roles have been applied.

### Environment

Revision of codebase:
Kubernetes version (use `kubectl version`):
- Client Version: v1.25.2
- Kustomize Version: v4.5.7
- Server Version: v1.22.13-eks-15b7512
Cloud provider or hardware configuration: EKS with IAM linking enabled
Others:

**Comment by adamfowleruk** [comment]
Also occurs on the new 0.3.0 release. Here's the output:-

```sh
cf create-org MyOrg
Creating org MyOrg as ...
Organization 'MyOrg' already exists.
OK

❯ cf o
Getting orgs as ...

No orgs found.

```

I noticed it said getting orgs as <blank>... so I installed the whoami plugin.

Also when I install the whoami plugin I get this:-

```sh
Installing plugin Whoami Plugin...
OK

Plugin Whoami Plugin 0.2.0 successfully installed.
❯ cf whoami
FAILED
Nobody is logged in
FAILED
Interesting - you are logged in, but your username is empty. Mysterious!
You are logged in as  at https://api.aws.12factor.xyz
```

This appears to be a mismatch between IAM Users in EKS and the concept of the default cf-admin install user which karifi seems unable to fetch as an identity, even though this cf-admin user in IAM successfully installed Korifi. (I did a full reinstall).

Help greatly appreciated as I'm at a hackathon with 75 people who may need to use this in the morning UK time!!! Thanks.

**Comment by adamfowleruk** [comment]
It seems v0.3.0 is also failing to create new orgs fully. cf create-orgs is hanging but CFOrg is created and the namespace, but no role bindings in the namespace. Can't fine any other errors except this from the korifi-api pod:-

```
{"level":"error","ts":1664394149.6585557,"logger":"Org Handler","msg":"Failed to create org","correlation-id":"a32d83d6-7828-4617-b0d7-8cc7f53cf786","Org Name":"MyNewOrg","error":"cf org did not get Condition `Ready`: 'True' within timeout period 120000 ms","stacktrace":"[code.cloudfoundry.org/korifi/api/apierrors.LogAndReturn](http://code.cloudfoundry.org/korifi/api/apierrors.LogAndReturn)\n\t/workspace/api/apierrors/errors.go:35\[ncode.cloudfoundry.org/korifi/api/handlers.(*OrgHandler).orgCreateHandler](http://ncode.cloudfoundry.org/korifi/api/handlers.(*OrgHandler).orgCreateHandler)\n\t/workspace/api/handlers/org_handler.go:67\[ncode.cloudfoundry.org/korifi/api/handlers.(*AuthAwareHandlerFuncWrapper).Wrap.func1](http://ncode.cloudfoundry.org/korifi/api/handlers.(*AuthAwareHandlerFuncWrapper).Wrap.func1)\n\t/workspace/api/handlers/auth_aware_handler.go:81\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\[ncode.cloudfoundry.org/korifi/api/handlers.(*AuthenticationMiddleware).Middleware.func1](http://ncode.cloudfoundry.org/korifi/api/handlers.(*AuthenticationMiddleware).Middleware.func1)\n\t/workspace/api/handlers/authentication_middleware.go:66\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\[ngithub.com/gorilla/handlers.loggingHandler.ServeHTTP](http://ngithub.com/gorilla/handlers.loggingHandler.ServeHTTP)\n\t/go/pkg/mod/github.com/gorilla/handlers@v1.5.1/logging.go:47\[ncode.cloudfoundry.org/korifi/api/handlers.HTTPLogging.Middleware.func1](http://ncode.cloudfoundry.org/korifi/api/handlers.HTTPLogging.Middleware.func1)\n\t/workspace/api/handlers/http_logging_middleware.go:28\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\[ncode.cloudfoundry.org/korifi/api/handlers.CorrelationIDMiddleware.Middleware.func1](http://ncode.cloudfoundry.org/korifi/api/handlers.CorrelationIDMiddleware.Middleware.func1)\n\t/workspace/api/handlers/correlation_id_middleware.go:30\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2109\[ngithub.com/gorilla/mux.(*Router).ServeHTTP](http://ngithub.com/gorilla/mux.(*Router).ServeHTTP)\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2947\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1991"}
{“level”:“info”,“ts”:1664394149.6586468,“logger”:“Org Handler”,“msg”:“handler returned error”,“correlation-id”:“a32d83d6-7828-4617-b0d7-8cc7f53cf786",“error”:“cf org did not get Condition `Ready`: ‘True’ within timeout period 120000 ms”}
```

**Comment by danail-branekov** [comment]
Hey @adamfowleruk ,

I saw on that [slack thread](https://cloudfoundry.slack.com/archives/C0297673ASK/p1664388419208329) that you seem to have figured org creation out. If that is sorted out, can we close the issue?

Regarding the [cf whoami](https://github.com/jtuchscherer/whoami-plugin) plugin - we never thought about cf plugins support - I will open a separate issue about that. For the time being you could use the `/whoami` endpoint - it is not part of the CF API but we implemented it for our own purposes:

```
❯ cf curl /whoami
{"name":"cf-admin","kind":"User"}
```

**Comment by adamfowleruk** [comment]
I have figured it out, but I think we need to change this to a documentation bug and keep it open. I'll happily send a PR about this for the Install.MD file on Monday but it will vex anyone else on EKS as it's a very specific 'fix'. 

For others' benefit, and until the docs PR is issued by me, you need to use the full URN for the new 'cf-admin' user in all fields, even though it can theoretically be mapped with a shorthand of the user in EKS. CF doesn't seem to like that. i.e. ADMIN_USERNAME is the URN, and there needs to be a specific 'username' field (not in the docs) with the URN, and the EKS mapUsers need this explicitly too.

**Comment by danail-branekov** [comment]
@adamfowleruk Are you still up to PR-ing the install guide change?

**Comment by gcapizzi** [comment]
It looks like we need a generic explore about running Korifi on EKS. The way they integrate their own IAM user management with Kubernetes [looks quite involved](https://docs.aws.amazon.com/eks/latest/userguide/add-user-role.html) and it leverages group bindings, which we don't support at the moment. I will create that explore and close this once I've verified the warning behaviour is correct.
