### ISSUE TITLE
[Bug]: Docs: Install.md mentions job runner yaml which doesn't exist

### ISSUE THREAD

**Issue by adamfowleruk** [cloudfoundry/korifi#1711]
### What happened?

Minor niggle. In the Install.md it mentions `kubectl apply -f korifi-job-task-runner.yml` but this file isn't in the 0.2.0 release tgz.

### What you expected to happen

The file to exist and do something, or the instruction in the install guide to be removed.

### Acceptance Criteria

GIVEN the install.md
WHEN I follow the instructions
THEN I don't see file does not exist messages for files the instructions tell me to use

### How to reproduce it (as minimally and precisely as possible)

Default install of Korifi using 0.2.0 release tgz

### Environment

Revision of codebase: 0.2.0 release tgz
Kubernetes version (use `kubectl version`): N/A
Cloud provider or hardware configuration: N/A
Others:

**Comment by danail-branekov** [comment]
@adamfowleruk the `INSTALL.md` document on the main branch is a living document which is supposed to reflect installing the current dev branch. That is why we have the following disclaimer on top:

```
Make sure you are using the correct version of these instructions by using the link in the release notes for the version you're trying to install
```

The installation guide for the 0.2.0 release is [here](https://github.com/cloudfoundry/korifi/blob/c41166c7fd4a201ba10c3ebc2c23d4724ae0ac39/INSTALL.md), it does not mention  `korifi-job-task-runner` at all.

Please feel free to reopen the issue if I did not get you right?

Thanks!
