### ISSUE TITLE
[Chore]: Build docker images conditionally only if the corresponding component directory tree changed. 

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#1725]
### Background

Right now we are always building all docker images of all korifi components regardless of whether the underlying code has changed. This is slow and annoying.

### Action to take

Make the build of each component conditional by calculating a stable sha of its corresponding directory tree. Here's a way of doing this from a script: https://stackoverflow.com/questions/545387/linux-compute-a-single-hash-for-a-given-folder-contents

We can check if the current version of the code has already been build by simply listing all docker images and looking for the calculated sha. Persistence has been done for us.

### Impact

Deploying korifi becomes quicker.

**Comment by danail-branekov** [comment]
A useful bash oneliner to get all the files a component needs:

```bash
export COMPONENT=api
go list -f '{{ join .Deps "\n" }}' ./$COMPONENT | grep korifi | sort | uniq | sed -e 's|code.cloudfoundry.org/korifi/||g'
```

Produces

```
api/actions
api/actions/manifest
api/actions/shared
api/apierrors
api/authorization
api/config
api/correlation
api/handlers
api/payloads
api/presenter
api/repositories
api/repositories/conditions
api/repositories/registry
controllers/api/v1alpha1
controllers/config
controllers/controllers/shared
controllers/controllers/workloads
controllers/controllers/workloads/env
controllers/webhooks
controllers/webhooks/services
tools
tools/k8s
```


Or, if we want to exclude `$COMPONENT` directory from the list:

```bash
export COMPONENT=api
go list -f '{{ join .Deps "\n" }}' ./$COMPONENT | grep korifi | grep -vE "$COMPONENT" | sort | uniq | sed -e 's|code.cloudfoundry.org/korifi/||g'
```

produces

```
controllers/config
controllers/controllers/shared
controllers/controllers/workloads
controllers/controllers/workloads/env
controllers/webhooks
controllers/webhooks/services
tools
tools/k8s
```

We could use that output to pipe it to the hashing utility

**Comment by georgethebeatle** [comment]
Looks like the builds are already properly cached by helm with the new distro format, so the chore is obsolete!
