### ISSUE TITLE
[Chore]: Deploy egg apps periodically

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#1730]
### Background

Right now we have two egg apps - postfacto and pairup, that are deployed once and not touched until a breaking change forces us to redeploy acceptance. This happens rather rarely and it is very probable that the app won't be able to be pushed. It could be an app change or a platform change. As these apps are more realistic than the simple hello-world apps that we use for testing, pushing them more often can provide valuable feedback to the platform. 

### Action to take

Push pairup and postfacto periodically

### Impact

We get more feed back on pushing apps on korifi while at the same time make sure that our pipeline scripts are healty.

**Comment by kieron-dev** [comment]
It might be a good idea to push postfacto and pairup on every push to main. Yet again we had to fix the postfacto deployment yesterday due to changes in the the rails-assets buildpack. It would be good to catch these problems early.
