### ISSUE TITLE
[Feature]: Installer of Korifi can achieve a sensible set of default buildpacks quickly from Korifi docs alone

### ISSUE THREAD

**Issue by adamfowleruk** [cloudfoundry/korifi#1732]
### Blockers/Dependencies

For a seamless quick install on EKS, at least: #1720 #1708 #1710 

### Background

**As a** DevOps platform engineer installing Korifi to support developers
**I want** to install the full range of 'default' buildpacks without trawling external projects' documentation
**So that** my developers can quickly evaluate Korifi

We believe that if we make this task simple and easy to do then this will lead to more rapid, wider Korifi adoption as it shows the main value of Korifi clearly and quickly.

### Acceptance Criteria

**GIVEN** The Install.md file as a starting point
**WHEN I** get to the section of setting up kpack I have a quick start config for all their default buildpacks rather than having to leave the Korifi docs and trawl through kpack et al documentation, and have those buildpacks work with a sample app OOTB via cf push to validate the install
**THEN I** see a working end to end Korifi install much quicker, with less frustration for those evaluating Korifi, leading to lots of happy tweets about how great Korifi is

### Dev Notes

I'll happily add this documentation myself in the coming week once I've tested it. Almost have it configured already.

**Comment by danail-branekov** [comment]
Hey @adamfowleruk 

For the upcoming Korifi release we are planning to introduce a helm chart that has a value to create a sample cluster builder if enabled - `kpack-image-builder.exampleClusterBuilder.create`. We decided to set it to `false` by default but users can always set it to `true` if they want to have it.

Please have a look at the [related chapter in INSTALL.md](https://github.com/cloudfoundry/korifi/blob/main/INSTALL.md#post-install-configuration). Do you think it achieves what you would like to see?

**Comment by gcapizzi** [comment]
I think the new Helm chart in 0.4 achieves exactly this: unless a cluster builder is explicitly configured, the chart will create a [default one](https://github.com/cloudfoundry/korifi/blob/5b44b5b02939f809f859ee2cd1fa5b9a53f6cade/helm/kpack-image-builder/templates/cluster-builder.yaml) using the following buildpacks:

- `paketo-buildpacks/java`
- `paketo-buildpacks/nodejs`
- `paketo-buildpacks/ruby`
- `paketo-buildpacks/procfile`
- `paketo-buildpacks/go`

Closing!
