### ISSUE TITLE
[Chore] Improve patching helm templates in make targets (remove sed-s)

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#1734]
In order to generate helm templates out of the controller-gen output we are executing [a bunch of `sed`s](https://github.com/cloudfoundry/korifi/blob/a893ac339b943f79449e0352987763d7d4b8d2fc/Makefile#L48-L59) in make targets. This is not great as we are kind of implementing our own patching subsystem, we could think of better ways to do that. Maybe we could use `yq` instead, or just apply standard patches

**Comment by georgethebeatle** [comment]
This is already the case
