### ISSUE TITLE
[Chore] Simplify Makefile targets

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#1778]
Currently we have an overwhelming amount of Makefile targets that are hard to maintain and reason about. They build/deploy/undeploy Korifi in various contexts, such as on a remote cluster vs kind, debug enabled or disabled, local vs remote docker registry.

Having in mind that:
a) The Makefile facilitates our development workflow, Korifi users are just going to use the released helm chart and will never run `make`. Having said that, all the targets that are not used in the development flow make no sense.
b) With the newly introduced helm way of installing Korifi, enabling various features is a matter of setting values when running `helm install`, therefore various flavours of deploy targets do not really make sense
c) Helm caching works pretty well thus it makes no difference whether you are deploying a single component or all the components. Therefore it makes no sense to have micro-targets like `deploy-api`, `deploy-controller`, etc.

It seems that people nowadays do not care about those targets as they just use the utility scripts (such as `deploy-on-kind.sh` and `run-tests.sh`) to facilitate their dev work ([related slack discussion](https://cloudfoundry.slack.com/archives/C0297673ASK/p1665505892663779)) rather than running `make` (except for running tests). That means that as long as we keep those scripts working, we can get rid of anything not used.

So I would suggest:

* Makefile should facilitate local development (a.k.a. `hacking`) purposes, i.e. be only targeted towards local development against kind
* The top-level Makefile should have targets the work for all components, below is a proposed list:
  * `manifests` - generates manifests for all components
  * `generate` - runs generation for all components
  * `fmt` - runs fmt on all components
  * `vet` - runs vet on all components
  * `lint` - runs lint on all components
  * `test-api`, `test-controllers`, `test-job-task-runner`, `test-statefulset-runner`, `test-kpack-image-builder`, `test-e2e` - run tests of a single component. It is useful to have them as separate targets in order to run them in parallel in `check-everything`
  * `test-api-controller` - runs tests for `api` and `controllers`. This target is referenced by `check-everything`, I cannot recall why `check-everything` does not run api and controllers tests in parallel, I have a vague memory that there was something about env tests. However, if it turns out that api and controllers tests can be run in parallel, then we do not need this target. They are also useful if you want to run a subset of tests, e.g. just run `api` tests only.
  * `install
* Targets that we do not seem to need:
  * `run-XXX` - I doubt that anyone runs components locally against the cluster these days
  * `docker-build` - I doubt that anyone build docker images for the sake of building them, if anyone wants it, a `kbld` command should do the trick ([example](https://github.com/cloudfoundry/korifi/blob/ade244350529629f752dc8a1de66f55f7aa2e766/scripts/deploy-on-kind.sh#L125-L128))
  * `docker-push` - same as above
  * `install-crds`/`uninstall-crds` - never heard anyone just installing the crds
  * `deploy-XXX`/`undeploy-XXX` - we just use `deploy-on-kind`. Manual deployment/undeployment if needed can be performed via `helm install`/`helm delete`
  * `vendir-update-dependencies` - nowadays dependencies bump is carried out by CI only, we do not need the target for local development. CI could just do whatever the target is running directly
  * enabling debug can be done by setting the `debug` helm value, no need for `xxx-debug` targets

As per nested Makefiles - maybe it makes sense to have parallel set of targets as the ones in the top-level Makefile so that the top-level Makefile delegates to them

**Comment by gcapizzi** [comment]
Couldn't `check-everything.sh` just invoke the `test` target inside the individual components? For `api` and `controllers` it could just run the two one after the other, so there shouldn't be any need for the `test-*` targets?

**Comment by georgethebeatle** [comment]
I would suggest that the top level Makefile has a single `test` target that just runs all tests serially. Then the `check-everything.sh` can only do the parallel run with the tmux splits. 

This way we give external contributors the ability to run all tests, albeit slowly without introducing a dependency to tmux. This is also safer, since parallel runs do sometimes choke the machine and fail weirdly, maybe they are fit only to run on our big cloud stations. And we will still be able to run tests in parallel in splits using `check-everything.sh`

**Comment by danail-branekov** [comment]
> Couldn't check-everything.sh just invoke the test target inside the individual components? For api and controllers it could just run the two one after the other, so there shouldn't be any need for the test-* targets?

I am a bit on the fence regarding `test-XXX` targets. I would be perfectly happy to run `run-tests.sh api` instead of `make test-api`, it is really up to whoever picks the chore. 

I agree that the top-level `make test` makes sense for external contributors.

**Comment by gcapizzi** [comment]
Even just `make -f api/Makefile test` doesn't look bad at all to me!
