### ISSUE TITLE
[Bug]: Source package images and droplet images create multiple dockerhub repositories

### ISSUE THREAD

**Issue by kieron-dev** [cloudfoundry/korifi#1782]
### What happened?

Configure korifi to use dockerhub. This means api configmap `packageRegistryBase` is "index.docker.io/\<username\>", as is kpack-image-builder configmap `kpackImageTag`.

Each source image ends up creating a new dockerhub repository in the form `<username>/<random guid>`. As does each droplet image.

This makes a mess of the dockerhub account and is hard to clean up.

### What you expected to happen

The configmaps should take a [repository](https://docs.docker.com/glossary/#repository) rather than a [registry](https://docs.docker.com/glossary/#docker-registry), and each source-package image should be an image in the configured repository, distinctly tagged. And each droplet image likewise should be a distinctly tagged image in its configured repository.

### Acceptance Criteria

GIVEN korifi configured to push source-package and droplet images to dockerhub
WHEN I push a number of apps
THEN I see all the source-package images in a single repository matching the api configuration
AND I see all the droplet images in another single repository matching the kpack-image-builder configuration

Also I expect this to work on other tested registries: i.e. GCR, Google Cloud Artifact Registry, kind local docker registry.

### How to reproduce it (as minimally and precisely as possible)

See above

### Environment

Revision of codebase:
Kubernetes version (use `kubectl version`):
Cloud provider or hardware configuration:
Others:

### Developer notes
The name generation needs some improvement in these two places:
- https://github.com/cloudfoundry/korifi/blob/c3a594760eea5bfdbe6dc71877ce4776878e1ae3/api/handlers/package_handler.go#L157
- https://github.com/cloudfoundry/korifi/blob/c3a594760eea5bfdbe6dc71877ce4776878e1ae3/kpack-image-builder/controllers/buildworkload_controller.go#L214

**Comment by gcapizzi** [comment]
This was fixed in `v0.5.0`!
