### ISSUE TITLE
[Feature]: API Client can update a route via PATCH /v3/routes/<route-guid>

### ISSUE THREAD

**Issue by davewalter** [cloudfoundry/korifi#181]
### Background

As a client of the API shim
I want to be able to update a Route
So that I can modify the route's properties

### Acceptance Criteria

**TODO**

## Documentation
Document this endpoint in our [API docs](https://github.com/cloudfoundry/cf-k8s-api/blob/main/docs/api.md)

### Dev Notes

* [`Update a route`](https://v3-apidocs.cloudfoundry.org/version/3.107.0/index.html#update-a-route)

**Comment by tcdowney** [comment]
Closing this since we're tackling it as part of the Labels/Annotations epic. See: https://github.com/cloudfoundry/korifi/issues/1446
