### ISSUE TITLE
[Explore]: Dynamic log level setting for korifi components

### ISSUE THREAD

**Issue by julian-hj** [cloudfoundry/korifi#1836]
### Background

Currently, we are hard-coded to produce info level logging and there is no way for a customer to modify log levels.

We would like to be able to:
1. turn up logging for the API shim or a specific controller manager.
1. adjust log levels at run-time without requiring components to restart.

### Acceptance Criteria

This is more a spike than an explore. We should try this out in a single executable, but look at what we can do to share the configmap and the code that watches it so that we can easily port the solution to the rest of the deployments.

Depending on the scope of the changes, we can then follow up with one or more stories to implement.

### Timebox

No timebox

### Dev Notes

There is an example in knative-serving, using [config maps](https://github.com/knative/serving/blob/main/config/core/configmaps/logging.yaml#L43-L78) that are [watched at runtime](https://github.com/knative/pkg/blob/6ce976ce9255359fab375aacf31e6fe628722c57/injection/sharedmain/main.go#L393-L400) to allow dynamic setting of log levels. 

We won't be able to use that code directly, but we could crib from it. We might also consider mounting the configmap and just watching the filesystem, similar to what we are currently doing for the API ingress secret.

**Comment by matt-royal** [comment]
The WIP for this is in `issues/1836`

**Comment by matt-royal** [comment]
The `issues/1836` branch contains our spike of adding a dynamically configurable log level to the API codebase. That implementation does the following
- Adds a `logLevel` key to the config file, which is interpreted as a `zapcore.Level` value (i.e `debug`, `info`, `warn`, etc)
- We adapted the logic we use to dynamically pick up changes to the ingress cert. This uses a file watcher on the config file. Kubernetes automatically updates this file in the container when the configmap changes, but *there can be a delay of up to 2 minutes* on the default configuration. An operator can also "restart" the deployment to trigger it faster if they want.
- Currently we only log at the `error` (i.e `logger.Error()`) and `info` (i.e. `logger.Info()`) levels. We will want to change/add some of our logging to be at the `debug` level via `logger.V(1).Info()`. The operator then can choose to see only errors, errors + info, or errors + info + debug logs.

We learned a great deal about how logr, zapr, and zap think about logging. logr thinks about log levels numerically (the higher the number the more verbose / less important) and zap thinks about them more traditionally (`debug`, `info`, `warn`, `error`, etc.). This means that we will likely end up configuring the verbosity of logs displayed via words (e.g. `debug`), but actually making the logs via numeric levels (e.g. `logger.V(1).Info()`).

Here's a rough mapping between zap's words and logr's levels.


| zap level | logr level | logr code to log at this level |
| --------- | --------- | --------------------------- |
| info (default) | 0 | `logger.Info()` or `logger.V(0).Info()` |
| debug | 1 | `logger.V(1).Info()` |
| error | n/a | `logger.Error()` |
| warn | n/a | not possible to log |
| "trace" (more verbose than debug, not a real zap level, but possible with `zapcore.Level(-2)`) | 2 | `logger.V(2).Info()` |

Useful resources:
- How to configure log verbosity in zapr: https://github.com/go-logr/zapr#increasing-verbosity
- How logr thinks about log levels: https://pkg.go.dev/github.com/go-logr/logr#readme-background
- An example usage of logr: https://github.com/go-logr/logr/blob/master/examples/usage_example.go
