### ISSUE TITLE
[Bug]: v0.4.0 Kind build error 

### ISSUE THREAD

**Issue by awsandy** [cloudfoundry/korifi#1849]
### What happened?

Build of v0.4.0 fails on MACOS 12.6 (apple silicon M1 pro)

Hi trying to build on kind:

export ROOT_NAMESPACE="cf"                                 
export KORIFI_NAMESPACE="korifi-system"
export ADMIN_USERNAME="kubernetes-admin"
export BASE_DOMAIN="vcap.me"
./deploy-on-kind.sh cf
No kind clusters found.
Creating cluster "cf" ...
.......... all looks good .........
Building korifi values file...
/Users/awsandy/odp/aws/sw/korifi/mac/korifi-0.4.0/controllers/bin/controller-gen object:headerFile="controllers/hack/boilerplate.go.txt" paths="./controllers/..."
make -C job-task-runner generate
/Users/awsandy/odp/AWS/sw/korifi/mac/korifi-0.4.0/job-task-runner/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
make -C kpack-image-builder generate
/Users/awsandy/odp/AWS/sw/korifi/mac/korifi-0.4.0/kpack-image-builder/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
make -C statefulset-runner generate
/Users/awsandy/odp/AWS/sw/korifi/mac/korifi-0.4.0/statefulset-runner/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
/Users/awsandy/odp/aws/sw/korifi/mac/korifi-0.4.0/controllers/bin/controller-gen \
		paths=./api/... output:rbac:artifacts:config=helm/api/templates \
		rbac:roleName=korifi-api-system-role
sed -i.bak -e 's/ROOT_NAMESPACE/{{ .Values.global.rootNamespace }}/' helm/api/templates/role.yaml
rm -f helm/api/templates/role.yaml.bak
/Users/awsandy/odp/aws/sw/korifi/mac/korifi-0.4.0/controllers/bin/controller-gen \
		paths="./controllers/..." \
		crd \
		rbac:roleName=korifi-controllers-manager-role \
		webhook \
		output:crd:artifacts:config=helm/controllers/templates/crds \
		output:rbac:artifacts:config=helm/controllers/templates \
		output:webhook:artifacts:config=helm/controllers/templates
sed -i.bak -e '/^metadata:.*/a \ \ annotations:\n    cert-manager.io/inject-ca-from: "{{ .Release.Namespace }}/korifi-controllers-serving-cert"' helm/controllers/templates/manifests.yaml
sed: 1: "/^metadata:.*/a \ \ ann ...": extra characters after \ at the end of a command
make: *** [manifests-controllers] Error 1

Guessing I've missed something ?

Thanks 

### What you expected to happen

Build succeeds without error

### Acceptance Criteria

Advice on how to resolve/troubleshoot

### How to reproduce it (as minimally and precisely as possible)

export ROOT_NAMESPACE="cf"                                 
export KORIFI_NAMESPACE="korifi-system"
export ADMIN_USERNAME="kubernetes-admin"
export BASE_DOMAIN="vcap.me"
./deploy-on-kind.sh cf

### Environment

Revision of codebase: v0.4.0
Kubernetes version (use `kubectl version`):

Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.25.2

Cloud provider or hardware configuration: MAC M1 Pro
Others: MacOS 12.6

**Comment by gcapizzi** [comment]
@danail-branekov shall we use this as an opportunity to switch to [`yq`](https://github.com/mikefarah/yq)? Maybe install it in the `Makefile` like we do with the other tools?

**Comment by gcapizzi** [comment]
@danail-branekov @georgethebeatle we have pushed branch [`issues/1849-fix-makefile`](https://github.com/cloudfoundry/korifi/tree/issues/1849-fix-makefile) to move back to `yq` and fix this. It's rebased on top of [`issues/1778-tidyup-makefile`](https://github.com/cloudfoundry/korifi/tree/issues/1778-tidyup-makefile) so we'll wait for you to create a PR and merge it before doing anything else!
