### ISSUE TITLE
[Chore]: Change our GCloud artifact registry to be multi-region 

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#1866]
There has been cases when pipelines were red because of issues in the datacenter we are running them in. If we switch to multi-region these won't bite us anymore.

**Dev notes**:
https://cloud.google.com/artifact-registry/docs/repositories/repo-locations#location-mr

**Comment by georgethebeatle** [comment]
It looks like this will result in additional cost: https://cloud.google.com/artifact-registry/pricing

We will discuss with the larger team and decide whether the pain is big enough to justify worth the cost

**Comment by kieron-dev** [comment]
For context, we discovered storage costs were about $6, and network costs about $0.13 for a month currently. So we're switching, and don't believe we'll see a massive increase. Possibly more storage costs if we have more replication. But the amounts are tiny.
