### ISSUE TITLE
[Chore]: Assign new issues to korifi project automatically

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#1867]
It turns out that when a new issue is open it does not get added to the project board until someone assigns it to the project. This makes it easy to miss bugs, reported by our users.

We could introduce a time-based concourse job that lists all such issues and adds them to the project from the name of `korifi-bot`

**Comment by gcapizzi** [comment]
[`actions/add-to-project`](https://github.com/actions/add-to-project) seems to be what we need here: it can easily be triggered on new issues and does all the API work for us.
