### ISSUE TITLE
API Client can retrieve a single domain via GET /v3/domains/:guid

### ISSUE THREAD

**Issue by acosta11** [cloudfoundry/korifi#188]
## Why
In support of routes in the CF V3 API, we would like implement read functionality for cf domain resources.

## Blockers
 * The CFDomain custom resource definition should already exist in https://github.com/cloudfoundry/cf-k8s-controllers/
 * We should have decided how we want to handle resource GUIDs/naming. See: [Explore: Determine how we represent CF resource "GUIDs" and name our K8s custom resources #2](https://github.com/cloudfoundry/cf-k8s-api/issues/2)

## Description
As a client of the CF API, I want to be able to retrieve a single CFDomain resource on Kubernetes via the API shim.

The behavior of this endpoint should match the existing behavior of the [`GET /v3/domains/:guid` endpoint](https://v3-apidocs.cloudfoundry.org/version/3.97.0/index.html#get-a-domain) in CF for VMs as closely as possible -- including the [error cases](https://v3-apidocs.cloudfoundry.org/version/3.102.0/index.html#common-errors).

For fields and relationships not included in the CFDomain, include the key but place an empty object in the value.

## Acceptance Scenarios

**GIVEN** I have the API shim running locally
**THEN** I can make perform the following scenarios

---

### Happy Path

**GIVEN** I have applied a CFRoute CR to the cluster (See cf-k8s-controllers samples) and know its "guid"
**WHEN** I make the following request
```
curl "https://api.example.org/v3/domains/[insert-guid-here]" \
  -X GET \
  -H "Authorization: bearer <some-placeholder-token>" \
  -H "Content-type: application/json"
```

**THEN** I get a response that looks like the following

```json
HTTP/1.1 200 OK
Content-Type: application/json

{
  "guid": "3a5d3d89-3f89-4f05-8188-8a2b298c79d5",
  "created_at": "2019-03-08T01:06:19Z",
  "updated_at": "2019-03-08T01:06:19Z",
  "name": "test-domain.com",
  "internal": false,
  "router_group": null,
  "supported_protocols": ["http"],
  "metadata": {
    "labels": { },
    "annotations": { }
  },
  "relationships": {
    "organization": null,
    "shared_organizations": {
      "data": []
    }
  },
  "links": {
    "self": {
      "href": "https://api.example.org/v3/domains/3a5d3d89-3f89-4f05-8188-8a2b298c79d5"
    },
    "route_reservations": {
      "href": "https://api.example.org/v3/domains/3a5d3d89-3f89-4f05-8188-8a2b298c79d5/route_reservations"
    }
  }
}
```
---

### Domain does not exist or cannot be found

**WHEN** I make the following request for an domain that does not exist

```
curl "https://api.example.org/v3/domains/[insert-guid-here]" \
  -X GET \
  -H "Authorization: bearer <some-placeholder-token>" \
  -H "Content-type: application/json"
```

**THEN** I get back the following response

```json
HTTP/1.1 404 Not Found

{
  "errors": [
    {
      "detail": "Domain not found",
      "title": "CF-ResourceNotFound",
      "code": 10010
    }
  ]
}
```

## Dev Notes

* We're not supporting private domains right now so we can leave the fields around "shared private domains" empty. For context these are updated via the share/unshare domain endpoints: https://v3-apidocs.cloudfoundry.org/version/3.112.0/index.html#share-a-domain
*  We may not be able to generate a random domain for the end to end test, instead relying on the existing default domain **guid** in the installation as a subject of the test assertions until we implement the domain create api endpoint

**Comment by gcapizzi** [comment]
This was done as part of #1944, closing!
