### ISSUE TITLE
[Bug]: Created org is invisible to cf CLI

### ISSUE THREAD

**Issue by relistan** [cloudfoundry/korifi#1901]
### What happened?

I successfully created an org from the `cf` cli:

```
cf -v create-org testing
```

This works:

```
... [ snip ] ...

$ RESPONSE: [2022-11-13T15:53:51Z]
HTTP/1.1 201 Created
Content-Type: application/json
Date: Sun, 13 Nov 2022 15:53:51 GMT
Server: envoy
Vary: Accept-Encoding
X-Correlation-Id: f3501d8f-046b-43c2-ae2b-a9611fa44ba9
X-Envoy-Upstream-Service-Time: 25
{
  "created_at": "2022-11-13T15:53:51Z",
  "guid": "cf-org-0405d7e3-44fa-47e2-a52a-834f6d7ed9ba",
  "links": {
    "self": {
      "href": "https://<REDACTED>/v3/organizations/cf-org-0405d7e3-44fa-47e2-a52a-834f6d7ed9ba"
    }
  },
  "metadata": {
    "annotations": {},
    "labels": {}
  },
  "name": "testing",
  "relationships": {},
  "suspended": false,
  "updated_at": "2022-11-13T15:53:51Z"
}


OK
```

I can see the Kubernetes CRD entry:

```
$ kubectl get -n cf CFOrg
NAME                                          DISPLAY NAME   AGE
cf-org-0405d7e3-44fa-47e2-a52a-834f6d7ed9ba   testing        117s
```

When I look at the detail for the entry, it claims the status is `Ready`:

```
$ kubectl get -n cf CFOrg -o yaml
apiVersion: v1
items:
- apiVersion: korifi.cloudfoundry.org/v1alpha1
  kind: CFOrg
  metadata:
    creationTimestamp: "2022-11-13T15:53:51Z"
    finalizers:
    - cfOrg.korifi.cloudfoundry.org
    generation: 1
    name: cf-org-0405d7e3-44fa-47e2-a52a-834f6d7ed9ba
    namespace: cf
    resourceVersion: "159055"
    uid: 8611ccab-c673-4c74-85c2-74556860eab3
  spec:
    displayName: testing
  status:
    conditions:
    - lastTransitionTime: "2022-11-13T15:53:51Z"
      message: ""
      reason: Ready
      status: "True"
      type: Ready
    guid: cf-org-0405d7e3-44fa-47e2-a52a-834f6d7ed9ba
kind: List
metadata:
  resourceVersion: ""
```

**However** the `cf` CLI cannot see the org:

```
$ cf -v orgs

... [snip] ...

RESPONSE: [2022-11-13T15:56:32Z]
HTTP/1.1 200 OK
Content-Type: application/json
Date: Sun, 13 Nov 2022 15:56:32 GMT
Server: envoy
Vary: Accept-Encoding
X-Correlation-Id: 81e5db88-1119-4e1a-8caf-fd7e067eccf6
X-Envoy-Upstream-Service-Time: 5
{
  "pagination": {
    "first": {
      "href": "https://<REDACTED>/v3/organizations?order_by=name"
    },
    "last": {
      "href": "https://<REDACTED>/v3/organizations?order_by=name"
    },
    "next": null,
    "previous": null,
    "total_pages": 1,
    "total_results": 0
  },
  "resources": []
}


No orgs found.
```

### What you expected to happen

I expected to see the org that I just created

### Acceptance Criteria

GIVEN that I have created a CloudFoundry org 
WHEN I call `cf orgs`
THEN I see the org that I have created

### How to reproduce it (as minimally and precisely as possible)

I followed the instructions here: https://github.com/cloudfoundry/korifi/blob/main/INSTALL.md

And then I took the actions described above, as part of the last step in the `INSTALL` guide

### Anything else we need to know?

The `cf` cli is running on Ubuntu 22.04 and was installed with the Debian package manager instructions: https://docs.cloudfoundry.org/cf-cli/install-go-cli.html

### Environment

Revision of codebase: 0.4.0
Kubernetes version (use `kubectl version`):
```
Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.25.3
```
cf version: `8.5.0+73aa161.2022-09-12`
Cloud provider or hardware configuration: Hetzner cloud, `uname -a`: 
```
Linux thor 5.4.0-125-generic #141-Ubuntu SMP Wed Aug 10 13:42:03 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
Others:

**Comment by relistan** [comment]
If I try to create it again, it can tell that it already exists:

```
$ cf -v create-org testing

... [snip] ...
RESPONSE: [2022-11-13T17:35:37Z]
HTTP/1.1 422 Unprocessable Entity
Content-Type: application/json
Date: Sun, 13 Nov 2022 17:35:37 GMT
Server: envoy
Vary: Accept-Encoding
X-Correlation-Id: 1aa1b787-29e3-4241-88a2-78c2677c2e30
X-Envoy-Upstream-Service-Time: 12
{
  "errors": [
    {
      "code": 10008,
      "detail": "Organization 'testing' already exists.",
      "title": "CF-UnprocessableEntity"
    }
  ]
}

Organization 'testing' already exists.
OK
```

**Comment by kieron-dev** [comment]
Hi @relistan,

This looks like the problem where the k8s user doesn't have a CF rolebinding. We generally use normal k8s RBAC for authorization, but orgs are a special case. You can only see them via the API if you have a role binding in the corresponding namespace.

The helm chart takes care of [creating the admin rolebinding in the root namespace](https://github.com/cloudfoundry/korifi/blob/main/helm/korifi/templates/admin-user.yaml), if you pass the correct k8s name for your admin user in the [adminUserName](https://github.com/cloudfoundry/korifi/blob/cccd0b8920e093366eef2d9bd2fbc6ebe57039a9/helm/korifi/values.yaml#L8) value. That rolebinding will be propagated into the org namespace when it's created, and the org will be visible to the admin user.

You will see which k8s user name you're using in the cf cli output, or you could `cf curl /whoami`. I suspect the rolebinding from that to the `korifi-controllers-admin` cluster role in the `cf` namespace is missing or set to the wrong user name.

By the way, in the next release we issue a warning visible in the CLI if the current user doesn't have any CF rolebindings so that people can check their setup: https://github.com/cloudfoundry/korifi/pull/1834.

**Comment by relistan** [comment]
@kieron-dev Thanks! This helps a lot. It appears that the default install instructions create the following binding:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    cloudfoundry.org/propagate-cf-role: "true"
    meta.helm.sh/release-name: korifi
    meta.helm.sh/release-namespace: korifi-system
  creationTimestamp: "2022-11-14T10:13:43Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: default-admin-binding
  namespace: cf
  resourceVersion: "3544"
  uid: ce927288-89e8-4508-8a97-120f4e17ea6a
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: korifi-controllers-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: cf-admin
```

based on the env var ```export ADMIN_USERNAME="cf-admin"```

But when I `cf curl /whoami` I am `{"name":"admin","kind":"User"}`. This mismatch appears to be the problem.

Now that I know what I am looking for thanks to your help, this was [explained in the initial setup](https://github.com/cloudfoundry/korifi/blob/main/INSTALL.md#initial-setup) but the consequences and takeaways weren't clear to me.

I attempted to create a new user role named `cf-admin` on the K8s RBAC side to make it work, but that was not successful. I tried to duplicate the existing RoleBinding and apply it for `admin`, again with no luck.

The thing that fixed it was changing the env var to `ADMIN_USERNAME=admin` and re-running the helm chart with `helm update --install`.

I will sort out the other permissions issues once I've evaluated things.

> By the way, in the next release we issue a warning visible in the CLI if the current user doesn't have any CF rolebindings so that people can check their setup: https://github.com/cloudfoundry/korifi/pull/1834.

That will help people out a lot, I think.

Thanks for your help!
