### ISSUE TITLE
[Bug]: App revision changes unexpectedly

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#1912]
### What happened?

We spotted this issue via a CI flake: 

```
[FAIL] Apps Running Apps Stop the app [It] eventually increments the app-rev annotation

Expected
...............
              "metadata": <map[string]interface {} | len:2>{
                  "labels": <map[string]interface {} | len:1>{
                      "korifi.cloudfoundry.org/app-guid": <string>"a7762d3b-156c-48a1-b1da-b7fe1855be9c",
                  },
                  "annotations": <map[string]interface {} | len:1>{
                      "korifi.cloudfoundry.org/app-rev": <string>"0",
                  },
.............
      to have {key: value} matching
          <map[interface {}]interface {} | len:1>: {
              <string>"metadata": <*matchers.HaveKeyWithValueMatcher | 0xc0001dc900>{
                  Key: <string>"annotations",
                  Value: <*matchers.HaveKeyWithValueMatcher | 0xc0001dc8e0>{
                      Key: <string>"korifi.cloudfoundry.org/app-rev",
                      Value: <string>"1",
                  },
              },
          }
```

It turned out that this flake can be easily reproduced locally by focusing the test and running with UNTIL_IT_FAILS.

According to [this issue](https://github.com/cloudfoundry/korifi/issues/260), the annotation has been introduced in order to filter out terminating pods (because e.g. an app is being restarted) when fetching stats. In order to achieve this
* Pods that belong to the app are annotated with the `app-rev` annotations
* The `app-rev` value is intended to be only bumped when the app stops, so that upon subsequent restart new pods are going to be labeled with the new value ([here](https://github.com/cloudfoundry/korifi/blob/1c2d5b5425a9e48410f4118ba7f0b1a0049488ec/controllers/api/v1alpha1/cfapp_webhook.go#L61-L68))
* When stats are requested, it would list pods that are labeled with the app guid and the `app-rev` ([here](https://github.com/cloudfoundry/korifi/blob/1c2d5b5425a9e48410f4118ba7f0b1a0049488ec/api/repositories/pod_repository.go#L88))

However, with this flake we observe that after a single restart
a) sometimes that value remains 0 (e.g. [here](https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-pr/builds/881.3))
b) sometimes the value is bumped to 2 (e.g. [here](https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/run-e2es-periodic/builds/3198)) 

This means that the CFApp webhook is either missing the update event, or generating extra versions without the app being restarted.

### What you expected to happen

`app-rev` is bumped if and only if the app gets stopped.

### Acceptance Criteria

* The flake above is fixed
* The issue discussed [here](https://github.com/cloudfoundry/korifi/issues/260#issuecomment-991205869) does not occur

### How to reproduce it (as minimally and precisely as possible)

Focus the test and run it wit UNTIL_IT_FAILS, takes ~10 attempts

### Anything else we need to know?

Reconcilers and webhooks in k8s should are not state machines, so reliable ordering of app revisions cannot be implemented with the current approach. Instead, we could leverage immutable fields, such as `CFApp`/`AppWorkload` names to label and find pods. In other words:

1. When the app workload controller creates a pod, it labels it with the `AppWorkload` name (which is generated and unique)
2. When stats are requested, in order to list pods we first find the workloads for an app, then look up pods labeled accordingly
3. When the app is stopped, the workload is deleted, therefore terminating pods would not be listed.

However, we have to keep in mind that if we implement the above suggestion cf apps will need to be  restarted upon korifi update, otherwise their logs and stats would not be obtainable.

**Comment by gcapizzi** [comment]
According to the discussion in yesterday's sync, these are some of the reasons we introduced `app-rev`:
* we were returning logs and stats for terminating pods
* we were reporting terminated pods as running during restarts
  - there might be differences between the way the web process and the other processes are treated during restarts?

Let's think about these when we try to come up with a replacement for `app-rev`.

**Comment by kieron-dev** [comment]
There is a slack thread [here](https://cloudfoundry.slack.com/archives/C0297673ASK/p1669200774387579)

**Comment by georgethebeatle** [comment]
I made some progress, pushed to WIP branch: https://github.com/cloudfoundry/korifi/tree/issues/1912-app-rev
