### ISSUE TITLE
[Bug]: Custom CA docs link broken and missing steps

### ISSUE THREAD

**Issue by laidbackware** [cloudfoundry/korifi#1920]
### What happened?

When following [`using-container-registry-signed-by-custom-ca.md`](https://github.com/cloudfoundry/korifi/blob/ba5e1d1866f3dfb38207ddbf3f9cd9aad336db27/docs/using-container-registry-signed-by-custom-ca.md), it links to a file which no longer exists, with there being multiple deployment.yaml files within the repo. It is also missing the implementation detail.

### What you expected to happen

Assume that [this is the correct file](https://github.com/cloudfoundry/korifi/blob/main/helm/api/templates/deployment.yaml).

The docs should explain how to run the helm install command from the repo rather than the online release, as otherwise updating a file in the repo will not result in any change.

The docs also need to explain how to modify the deployment.yaml file with details of what the expected path needs to be of the secret volume mount. Without this, a user cannot know where to mount.

### Acceptance Criteria

GIVEN I'm using a private CA
WHEN I follow the docs
THEN I am able to update korifi-api without any additional research

### How to reproduce it (as minimally and precisely as possible)

Try to follow [instructions](https://github.com/cloudfoundry/korifi/blob/main/docs/using-container-registry-signed-by-custom-ca.md).

### Environment

Revision of codebase: 0.4.0
Kubernetes version (use `kubectl version`): v1.25
Cloud provider or hardware configuration: k3s
Others:

**Comment by gcapizzi** [comment]
📔 Note to self - see the following issues for context:
* #1192 
* pivotal/kpack#207

**Comment by gcapizzi** [comment]
@laidbackware this should be fixed now! You won't find it in our latest release (`v0.5`) but `v0.6` should not be too far away 🙂
