### ISSUE TITLE
[Explore]: Use app-scoped container repositories 

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#1960]
### Background

In #1884 and #1914 we moved from creating a separate container repository for each package and droplet, to using two single, pre-existing, repositories for packages and droplets.

The previous system would use the package/droplet as the last segment of the repository path, and thus required repositories to be created on demand, when the app was pushed. This doesn't work on Amazon ECR, which requires an existing repository before an image can be pushed. The single repository solution solves this.

Unfortunately, using a single repository for all packages/droplets comes with its own problems:
* it is impossible to tell which images belong to which apps, so it's impossible to garbage collect old images;
* for the same reason, it is impossible to purge all images belonging to an app when it gets deleted;
* any existing garbage collection routine that might be in place will not work as expected on Korifi.

The most natural and idiomatic way of organising container registries would be per-app: each app would get a packages repository and a droplets one. In order to do so, we'll need to create repositories on demand when an app gets pushed. For registries that don't support doing this just by pushing (ECR), we should consider having dedicated code using proprietary APIs.

### Acceptance Criteria

A document/comment(s) describing a strategy to achieve app-scoped container repositories in Korifi.

The user-facing changes we should consider are the following:
* instead of asking for separate repositories, we should ask for a single `containerRegistryBase`;
* repositories will look like `<containerRegistryBase>/<app-guid>-packages` and `<containerRegistryBase>/<app-guid>-droplets`;
    - on Docker, `containerRegistryBase` can be `index.docker.io/<username>`;
    - on GAR it can be `<region>-docker.pkg.dev/<project>/<gar-repo>`;
    - on EKS, `<account-id>.dkr.ecr.<region>.amazonaws.com`.

### Timebox

No timebox

### Dev Notes

* The ECR [`CreateRepository`](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_CreateRepository.html) action should be what we need.
* We will have to inspect `containerRegistryBase` to detect ECR and extract the API endpoint, as it differs per region. See [_Amazon ECR endpoints and quotas_](https://docs.aws.amazon.com/general/latest/gr/ecr.html).

**Comment by danail-branekov** [comment]
Here is the story: https://github.com/cloudfoundry/korifi/issues/1966
