### ISSUE TITLE
[Chore]: Generate resource GUIDs into the repositories instead of handlers

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#197]
### Background

Currently the GUIDs for CF resources are generated in the REST API handlers (for example, [app handler](https://github.com/cloudfoundry/cf-k8s-controllers/blob/af7cac6ca1176c3614de2da3139a9bad06aaeb28/api/apis/app_handler.go#L168), [space handler](https://github.com/cloudfoundry/cf-k8s-controllers/blob/af7cac6ca1176c3614de2da3139a9bad06aaeb28/api/apis/space_handler.go#L58), etc.). This looks a bit weird as those handlers should deal with the HTTP stuff only and GUID generation looks like to be more of a repository concern

### Action to take

new

### Impact

Better code

**Comment by tcdowney** [comment]
This has since been refactored. Example:
https://github.com/cloudfoundry/korifi/blob/78b8694b3bc368adf6862e10391d36b2a19f368e/api/repositories/app_repository.go#L571

Going to go ahead and close. 👍
