### ISSUE TITLE
[Bug]: CFRoute deletion fails

### ISSUE THREAD

**Issue by kieron-dev** [cloudfoundry/korifi#1986]
### What happened?

When you try to delete a CFRoute, the operation fails silently.

If you look at the controller logs, you will see the CFRoute reconciler fails lacking permission to patch contour HTTPProxy status.

### What you expected to happen

The CFRoute finalizer is removing a route from the contour HTTPProxy, and then it persists that update using a Patch utility.

That patch tries to update both spec and status of the HTTPProxy. But we have no business changing the HTTPProxy status, and rightly have no permission set up to do so.

Instead of using the Patch utility, we should use the PatchResource utility which doesn't attempt to update the status.

### Acceptance Criteria

GIVEN I have a route
WHEN I delete that route
THEN I see it is successfully deleted and does not appear in `cf routes`

### How to reproduce it (as minimally and precisely as possible)

In a 'deploy-on-kind' env, for example:
```
cf create-route apps-127-0-0-1.nip.io --hostname foo
cf routes # and see the route
cf delete-route apps-127-0-0-1.nip.io --hostname foo
cf routes # and see the route was not deleted
```

### Anything else we need to know?

This failure is not picked up by any test. Ensure this is covered.

### Environment

Revision of codebase:
Kubernetes version (use `kubectl version`):
Cloud provider or hardware configuration:
Others:

**Comment by tcdowney** [comment]
This was completed in https://github.com/cloudfoundry/korifi/pull/1999, but looking for someone to verify the fix before closing this issue out. I took off the "good first issue" label so that no one picks this up accidentally.

**Comment by julian-hj** [comment]
verified fixed
