### ISSUE TITLE
[Chore]: Factor out common finalizer code from controllers

### ISSUE THREAD

**Issue by kieron-dev** [cloudfoundry/korifi#1987]
### Background

Finalizers can be racy, and can lead to resource that cannot be deleted.

We have seen cases where a resource is deleted before its finalizer has been saved to the resource. This means its finalization never runs and associated resources leak or are inconsistent.

We have also seen the CFOrg controller add a finalizer back into metadata after finalization has successfully completed, leading to a resource that cannot be deleted.

It might be useful to have a single place for handling setting a finalizer in the metadata and calling the finalizer on deletion. This could be a reconciler wrapper, like the Patching Reconciler.

### Action to take

Try to extract metadata finalizer addition and finalizer execution into a wrapper reconciler.

Ensure the finalizer metadata is saved immediately when set.

Ensure the finalizer is called if appropriate, and in that case the finalizer is not re-added.

### Impact

We can be more confident that our resources will not have finalizer problems, and we don't have to solve the same concurrency issues in each reconciler.

**Comment by georgethebeatle** [comment]
We have solved this by adding finalizers in defaulting webhooks.
