### ISSUE TITLE
Explore: use `metadata.generation` in the `korifi.cloudfoundry.org/app-rev` annotation

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#2040]
## Current state

Currently the CFApp CR has a special `korifi.cloudfoundry.org/app-rev` annotation, that is used for two purposes:
- On each reconciliation of a `CFProcess` that is owned by a given `CFApp`, a [cleanup](https://github.com/cloudfoundry/korifi/blob/d35fb626752c9b07c418e049a7f34694f9138789/controllers/controllers/workloads/cfprocess_controller.go#L103) of any `AppWorkload`s with an old app revision is performed. This is how restarting an app works: the API bumps the app revision and this causes old workloads to be replaced by new ones.
- The app revision is also used for [filtering of logs and stats](https://github.com/cloudfoundry/korifi/blob/d35fb626752c9b07c418e049a7f34694f9138789/api/repositories/pod_repository.go#L88), so that the user only seed logs and stats for the latest app revision.

## Problems
- The user experience of the restart operation as of today looks weird. This applies to both the API server and `kubectl` users. In order to do a restart they need to:
  - set the `CFApp.Spec.DesiredState` to `STOPPED`;
  - bump the app revision (this includes int parsing and is error prone);
  - set the `CFApp.Spec.DesiredState` to `STARTED`.
- Incrementing the number in our controllers did not work, as sometimes bumps would not occur.

## Explore Objectives
- Evaluate the usage of the [observed generation pattern](https://alenkacz.medium.com/kubernetes-operator-best-practices-implementing-observedgeneration-250728868792) for setting the contents of the annotation: this would consist in storing `metadata.generation`, which won't result in unitary increments but should be good enough.
- Come up with a better user experience for the restart operation. For example it might boil down to just deleting the `CFProcess`. The controllers will recreate it afterwards.

**Comment by matt-royal** [comment]
Thank you for writing this up, @georgethebeatle. The sub-task about pods feels quite large, and it's also related to the assumption korifi makes that AppWorkloads will be realized as `statefulsets` (e.g. service bindings [explicitly target statefulset](https://github.com/cloudfoundry/korifi/blob/c50940fdc563b36e5f5c6d0a2a8d5e2b5b12cc6a/controllers/controllers/services/cfservicebinding_controller.go#L194-L198) and we [require the `CF_INSTANCE_ID` env var](https://github.com/cloudfoundry/korifi/blob/c50940fdc563b36e5f5c6d0a2a8d5e2b5b12cc6a/api/repositories/pod_repository.go#L193-L214) to determine if an app is healthy). Given that, I'd suggest limiting the scope of this exploration to solving the app revision problem without changing the pods assumption.

It's also worth noting that there are already alternative runners that use the app revision in a load-bearing way so we should try our best to solve the problem without altering the app revision interface (i.e. the annotation).

**Comment by tcdowney** [comment]
@matt-royal what are the requirements for the contents of app revision? Is it sufficient for it to be something unique? We're considering using [`observedGeneration`](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#metadata) which is a monotonically increasing integer.

> generation: a sequence number representing a specific generation of the desired state. Set by the system and monotonically increasing, per-resource. May be compared, such as for RAW (read after write) and WAW (write after write) consistency.

I think it might be a bit weaker than what we've currently have since it will be updated more frequently and might appear to skip values, but feels like it should work?

**Comment by matt-royal** [comment]
Using the value of `observedGeneration` should be fine. The existing use case relies on the `AppWorkload` name + appRevision changing whenever an app is restarted or otherwise changed.

**Comment by gcapizzi** [comment]
There is a problem with the name of the annotation: [app revisions](https://docs.cloudfoundry.org/devguide/revisions.html) are an existing CF concept, and are created only on specific changes to the app (restaged, changes to the environment/start command, rollbacks). CF revisions are identified by GUID but also have an incrementing integer `version` (see the [API docs](https://v3-apidocs.cloudfoundry.org/version/3.130.0/index.html#revisions)).

What shall we do? Deprecate this annotation and replace it with another one? Leave as it is? I feel like revisions are something we might want to support in the future, although that would probably happen via top-level fields and not annotations.

**Comment by gcapizzi** [comment]
Some initial notes:
- `metadata.generation` will be updated by Kubernetes at every change of the `spec`, and for no other reason.
- We can *not* update the value of the annotation at every reconciliation cycle, as that would result in a restart, and `spec.desiredState` is not the only mutable field (e.g. there's `displayName`, we don't want to restart on renames!).
- We can update the value of the annotation every time the app is stopped, by comparing the value of `status.observedDesiredState` (which is the last observed value of `spec.desiredState`) and the current value of `spec.desiredState`: this was the [original strategy](https://github.com/cloudfoundry/korifi/blob/38f10451f4cde1a2361be21873d7c6034aecde72/docs/architecture-decisions/0011-document-cf-restart-implementation.md), we'd just replace incrementing the value with copying `metadata.generation`.
- Adopting the aforementioned strategy in the controller would work, but let's not forget that we should not rely on the reconciler running for every single change: it is possible for the `spec.desiredState` to be set to `STOPPED` and then back to `STARTED` between two reconciliations. In this case, we wouldn't notice that the user had changed the `desiredState` at all.
- One solution would be to wait for a change to `spec.desiredState` to take effect _before_ it's changed again. In other words, to restart an app the user (and our shim) would have to:
    * set `spec.desiredState` to `STOPPED`;
    * wait for the app to stop;
    * set `spec.desiredState` to `STARTED.
- We could make sure to receive every possible change by using a mutating webhook instead.

**Comment by matt-royal** [comment]
Thank you for the thoughtful analysis, @gcapizzi. Your suggested solution (enforce that the app must be fully stopped before starting again) sounds plausible, but I'm unsure if it will work with the current `cf` CLI. Perhaps we need a spike/exploration to add this behavior and see if `cf restart` still works?

There is also still the question of how we replace the revision number in the tas-adapter. There we use the app revision as part of a k8s resource name. This allows us to change immutable fields on the statefulset by changing its name (thus recreating it via kapp) when the app restarts. We could use `observedGeneration` here, though that would lead to unrequested restarts as you mentioned. It isn't clear to me what the alternative to revision number would be for this scenario.

**Comment by gcapizzi** [comment]
@matt-royal 👋 
* I think the waiting would happen in the API, so CLI _should_ be fine. That said, the webhook solution was the one adopted initially (before we moved the logic to the handlers), so I think we can just roll back to that.
* I don't think we're ready to get rid of the `app-rev` annotation. We're changing it to assume the value of `metadata.generation` but *only on restarts*, so any existing consumer should be fine. The only change is in _how_ its value will change (it's going to increase by potentially more than one unit at the time) but not to _when_ it will change. By using `metadata.generation` we hope to avoid the concurrency issues when incrementing the value ourselves.
