### ISSUE TITLE
[Bug]: Unable to Register Korifi as a Cloud Foundry Endpoint in Stratos

### ISSUE THREAD

**Issue by vineethvkumar** [cloudfoundry/korifi#2041]
### What happened?

I have Korifi & Stratos running on Kubernetes but I am unable to Register Korifi as a Cloud Foundry Endpoint in Stratos. 

### What you expected to happen

We should be able to Register Korifi as a Cloud Foundry Endpoint in Stratos.

### Acceptance Criteria

GIVEN I have Stratos & Korifi Setup
WHEN I Register Korifi as Cloud Foundry Endpoint in Stratos
THEN I Should be able to Successfully Register Korifi as a Cloud Foundry Endpoint and Manage Korifi via Stratos

### How to reproduce it (as minimally and precisely as possible)

1. Login to Stratos
2. Navigate to Endpoints
3. Click on Add Endpoint button
4. Select Cloud Foundry as Endpoint Type
5. Enter details of Korifi Endpoint
6. Click Register

### Environment

Revision of codebase:latest

Kubernetes version (use `kubectl version`):
  Client Version: v1.26.0
  Kustomize Version: v4.5.7
  Server Version: v1.25.3

Others: Stratos version : 4.4.0

**Comment by gcapizzi** [comment]
Hi @vineethvkumar! 
As Korifi leverages Kubernetes authentication and authorization, clients need to authenticate differently than with traditional CF. The CF CLI is currently the only client supporting us.

It shouldn't be too hard to add Korifi support to Stratos, as they can already authenticate against Kubernetes. Unfortunately, the project seems to be unmaintained, and it's been [removed](https://github.com/cloudfoundry/community/commit/269e08e102c679709f579b807bc325455fcf1d05) from its working group charter. A [call for maintainers](https://github.com/cloudfoundry/community/issues/226) is still in progress but hasn't resulted in anything concrete yet.

I'm going to close this bug as there's nothing else we can do at the moment. Anyone interested in working on Korifi support for Stratos can get in touch with us and we'll be happy to help.
