### ISSUE TITLE
[Chore]: Add additional app lifecycle tests to the e2e tests

### ISSUE THREAD

**Issue by matt-royal** [cloudfoundry/korifi#2075]
### Background

Several app lifecycle operations are not exercised by any of our tests. Bug here can only be caught through manual acceptance, so nothing blocks regressions.

### Action to take

Add tests for the following scenarios to the e2e tests:
- Push different code to an existing app and verify that the new code is running (including by curling the app)
- Scale up a non-web process on an multi-process app

In addition, there are gaps in our existing app e2e tests. For example, we don't verify that the app is receiving web requests and returning the expected response. This can lead to false positives, such as the API responding "correctly" but the app workload being stopped or unreachable. Add these checks to the existing tests.

### Impact

These new tests and new assertions will avoid a class of regressions around the app lifecycle.

**Comment by clintyoshimura** [comment]
Note: The newly added apps e2e test that queries the /env.json endpoint already verifies the app is receiving web requests and returning the expected response. In addition, the re-push app e2e test in the PR will also verify the app web request response before and after re-push.
