### ISSUE TITLE
[Explore]: Garbage collection

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#2112]
### Background

As a Korifi installation gets older and older, some resources will accumulate without ever being cleaned up. This poses a problem, as the cluster will eventually be filled with unused resources.

Which resources could we clean up?
* **Leaked resources**: resources that only make sense together, should be deleted together. Updating or deleting a resource should never result in its owned resources being leaked.
* **Propagated resources**: a propagated resource should be deleted when the original resource is deleted.
* **Accumulating resources**: things like builds/droplets, packages and tasks can potentially accumulate forever even if they're not used, as they're seldom explicitly deleted. We should have retention policies in place for these resources.

Let's:
* Evaluate if we still have cases of **leaked** or **propagated** resources not being cleanup up properly.
* Establish retention policies for **accumulating** resources:
  - builds/droplets: fixed number, configurable, 5 by default;
  - tasks: evaluate either a fixed number policy or a time-based one (it's 1 month by default on traditional CF).
* Establish if there are other **accumulating** resources that I haven't listed above.

### Acceptance Criteria

A proposal describing what needs to be done to prevent Korifi from silently accumulating resources over time.

### Dev Notes

* [_App Revisions_](https://docs.cloudfoundry.org/devguide/revisions.html)

**Comment by kieron-dev** [comment]
- Root namespace CFUser bindings
  - Create stories for /v3/users endpoints list/create/delete/get
  - Don't worry about permission listing CFOrg in root namespace. It's necessary for kubectl users. Could be restricted better with OPA, for example.
    - Similar for builderinfo & domain, but it's not sensitive information, so needn't be restricted.

- Builds / Droplets / Packages
  - Registry clean up
  - CF on VMs: cron-style clean up
    - https://github.com/cloudfoundry/cloud_controller_ng/blob/main/app/jobs/runtime/prune_completed_builds.rb
    - https://github.com/cloudfoundry/cloud_controller_ng/blob/main/lib/cloud_controller/bits_expiration.rb#L22
    - Runs every night

  - CF cleans up orphan blobs periodically
    - kpack does not delete build images when a build is deleted
    - we could add a finaliser to kpack builds to do that
    - similarly for packages

- Tasks
  - The reconciler already deletes tasks older than a certain age
