### ISSUE TITLE
[Feature]: Improve api validation for cf-manifest deserialization

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#2123]
### Problem

Nowadays we are using the [go playground validator](https://github.com/go-playground/validator) library to validate all our api payloads. It accomodated the use of golang type annotations. Here is an example: https://github.com/cloudfoundry/korifi/blob/33da0adcb496b5d5721eac5c2335847ef203a85f/api/payloads/manifest.go#L11-L57

There are two problems with that:
- In the resulting validation error message all fields are disaplyed in camel case, the way they are defined in the code and not as json (the way the api is defined)
- The error message does not indicate where exactly in the hierarchical structure of the payload did the error occur

Here is what the new messages look like:

```
Applying manifest man.yml in org org1 / space space1 as cf-admin...
DiskQuota must be greater than 0MB
```
Notice how the error talks about `DiskQuota` and not `disk_quota`

Here is what the same warning looks like in old CF:

```
Applying manifest man.yml in org test / space test as admin...
For application 'test-app': Process "web": Disk quota must be greater than 0MB
```

Notice how it becomes clear that the disk quota is for the web process of `test-app`.

### Action to take

Find another way of payload validation or tweak the way we use the current library so that
- The error messages use the json form of the request fields
- When the payload is nested the path to the violating field is clearly communicated

## A/C
**When I** do the thing that makes the error as above
**Then I** see that the error message produces enough context for me to find the specific field that is failing validation. 

# Dev note
After we solve this, we should consider whether or not to generalize the solution to other objects apart from the CF app manifest, but that's not inscope for this story--maybe make another story if we feel that's a good idea.

**Comment by acosta11** [comment]
Task List:
- [ ] Add new validate function to the app_manifest payload
- [ ] Validate tests for behavior and error message output
- [ ] Use that validate function instead of DecodeAndValidateYAMLPayload in the space_manifest handler
