### ISSUE TITLE
[Bug]: Deploy-on-kind script fails with latest code on Mac OS

### ISSUE THREAD

**Issue by vineethvkumar** [cloudfoundry/korifi#2128]
### What happened?

Deploy-on-kind script (./scripts/deploy-on-kind.sh) fails with latest code on Mac OS.

Error:

`Release "korifi" does not exist. Installing it now.
Error: execution error at (korifi/charts/kpack-image-builder/templates/cluster-builder.yaml:35:10): builderRepository is required when clusterBuilderName is unset`

### What you expected to happen

Script should successfully setup korifi on local env.

### Acceptance Criteria

GIVEN I have latest code of Korifi
WHEN I execute deploy-on-kind script
THEN I should see korifi setup on local env

### How to reproduce it (as minimally and precisely as possible)

1. Clone latest code
2. Run ./scripts/deploy-on-kind.sh script

### Anything else we need to know?

This was working fine before, broke with recent updates.

### Environment

Revision of codebase: latest

**Comment by kieron-dev** [comment]
I expect you have a helm charts directory that we removed still in your checked-out source.

Try running `git clean -ffd`, or remove `helm/korifi/charts` (I think that's the one I saw causing problems!)

**Comment by vineethvkumar** [comment]
Thanks @kieron-dev ! Running `git clean -ffd` solved the issue.
