### ISSUE TITLE
[Feature]: App developer can use the `VCAP_APPLICATION` env var

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#2140]
### Background

There are CF apps that rely on the information in the `VCAP_APPLICATION` env var in order to function properly. Currently we do not provide this env var.

**As an** App Developer
**I want** to be able to use the various app attributes in the `VCAP_APPLICATION` env var
**So that** I can get app attributes, such as `guid`, `name`, `cf_app_url`, etc.

### Acceptance Criteria

**GIVEN** I have deployed an app that exposes its environment
- **WHEN I** look at the exposed app environment
  **THEN I** I can see that the `VCAP_APPLICATION` JSON is populated.
- **WHEN** I look at the [app environment](https://v3-apidocs.cloudfoundry.org/#get-environment-for-an-app) on the CF API
  **THEN I** I can see that the `VCAP_APPLICATION` JSON is populated.

Here is an example of a minimal `VCAP_APPLICATION` JSON:

```json
{
  "application_id": "1cf19b09-ff66-43f5-b42e-5f5b0822fa93",
  "application_name": "dora", 
  "cf_api": "https://api.mel-c.korifi.cf-app.com",
  "name": "dora", 
  "organization_id": "c442b06f-50ea-44b7-9c9c-83f278c495e2",
  "organization_name": "org1",
  "space_id": "88d02a93-d592-4668-8413-30dee0449cc1",
  "space_name": "space1"
}
```

### Dev Notes

* We need to expose at least the `cf_api` value, but while we are at it let's expose everything that is trivial to implement, like `application_id`, `application_name`, etc. There is a minimal example above, but feel free to add anything that is a low hanging fruit.
* [`VCAP_APPLICATION` docs](https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html#VCAP-APPLICATION).

**Comment by tcdowney** [comment]
We will want to make sure that the `GET /v3/apps/:guid/env` endpoint returns this as well. I think the [presenter](https://github.com/cloudfoundry/korifi/blob/9445968ace8a0c07ef795b1088110b506dbd5b7f/api/presenter/app.go#L188) is hardcoded to be empty right now.

https://v3-apidocs.cloudfoundry.org/version/3.131.0/index.html#get-environment-for-an-app
