### ISSUE TITLE
[Feature]: cf-admin can get better feedback when creating an org fails

### ISSUE THREAD

**Issue by julian-hj** [cloudfoundry/korifi#2167]
### Background

**As a** operator
**I want** better diagnostics when Korifi is misconfigured
**So that** I can fix it

Specifically, we'd like better error handling for the case where we are trying to make an org, and the registry secret is unavailable. As it stands today when I do this, the operation times out and the API reports a generic 500 error.

### Acceptance Criteria

**GIVEN** a Korifi installation, with the registry secret deleted from the root namespace
**WHEN I** use the cli to create a new org
**THEN I** see that the CForg object has a failure event with a meaningful status that indicates that the secret wasn't available.
**AND I** see a friendly error response from the CLI telling me that my org didn't reconcile after X seconds
**AND**
**WHEN I** use the cli to create a new space
**THEN I** see that the CFspace object has a failure event with a meaningful status that indicates that the secret wasn't available.

### Dev Notes

See discussion below for additional thoughts.

**Comment by akrishna90** [comment]
[Any error that isn't a "ApiError" gets mapped to "UnknownError"](https://github.com/cloudfoundry/korifi/blob/9445968ace8a0c07ef795b1088110b506dbd5b7f/api/routing/handler.go#L58-L80). When the error gets mapped to "Unknown" error, [the details of the error are ignored](https://github.com/cloudfoundry/korifi/blob/9445968ace8a0c07ef795b1088110b506dbd5b7f/api/errors/errors.go#L121-L131). When relevant, we could append some of the description onto the Unknown error's description.
