### ISSUE TITLE
[Feature]: cf CLI User can log in using `cf login -u USERNAME -p PASSWORD` without receiving an error

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/korifi#2195]
### Blockers/Dependencies

* This story will involve a contribution to the CF CLI: https://github.com/cloudfoundry/cli

### Background

Currently when you attempt to log in with the `-u` and `-p` flags you will get an error like this:

```
The argument -p is not supported on Kubernetes
FAILED
```

We should be able to support these parameters in the same way we support the `cf auth` command. The `-u` flag will pick the specified user from the `.kubeconfig` and the `-p` flag will be ignored.

**As a** User of the `cf` CLI
**I want** to be able to use the `-u` and `p` flags when logging in
**So that** I can use my existing workflows and scripts against Korifi

### No flags

**GIVEN** I have configured the CLI to point at a Korifi environment
**WHEN I** `cf login`
**THEN I** am given a list of Kubernetes users to select from the `KUBECONFIG`

### Only -u flag

**GIVEN** I have configured the CLI to point at a Korifi environment
**WHEN I** `cf login -u <user-name>`
**THEN I** am logged in non-interactively for the given user (same behavior as `cf auth`)

### Both -u and -p flags

**GIVEN** I have configured the CLI to point at a Korifi environment
**WHEN I** `cf login -u <user-name> -p <literally-anything>`
**THEN I** am logged in non-interactively for the given user (same behavior as `cf auth`) and the `-p` flag is ignored

### Dev Notes

* See how hard it would be to add a warning if the user provides a password - not necessary for k8s and would be ignored.

**Comment by matt-royal** [comment]
Here's our PR to the CLI to add this feature: https://github.com/cloudfoundry/cli/pull/2380

**Comment by matt-royal** [comment]
The PR was merged into the v8 branch of the CLI. @tcdowney, should I close this now or wait for a CLI release that includes the change?

**Comment by tcdowney** [comment]
Completed acceptance with a dev `cf` CLI and everything looked good to me. Closing this issue.
