### ISSUE TITLE
[Explore]: Figure out ways to improve payload validation

### ISSUE THREAD

**Issue by akrishna90** [cloudfoundry/korifi#2206]
### Background

A forerunner for #2123

We are using the [go playground validator](https://github.com/go-playground/validator) library to validate all our api payloads. There are two problems with the library:
- In the resulting validation error message all fields are displayed in camel case i.e. the way they are defined in the code and not the way they are defined in json.
- The error message does not indicate where exactly in the hierarchical structure of the payload did the error occur

Use this explore to look for ways we could address the problem and present to the team about our options. I have captured a few of the ideas we have discussed below: 
- Tweak the way we use the current library to address the problem.
- Find and explore other validation libraries
  - @matt-royal has done initial research and shared some alternatives and his thoughts about them. 👍🏽 
     - [ozzo-validation](https://go-ozzo.github.io/ozzo-validation/) - seems closer to Rails/Sequel validation and more flexible. Over 3k stars on github
     - [valix](https://github.com/marrow16/valix) - looks similar to our current solution and not many stars on github.
     - [validator](https://github.com/go-validator/validator) - looks similar to our current solution. Over 1k stars on github. Unclear if we can customize error messages.
     - [validating](https://github.com/RussellLuo/validating) - seems similar to ozzo-validation on the surface. ~200 stars on github.
  

### Acceptance Criteria

Capture your findings and present it to the team in a meeting.

### Timebox

No timebox

**Comment by gcapizzi** [comment]
I had done some research on this in https://github.com/cloudfoundry/korifi/issues/1947. I had looked at:
* [santhosh-tekuri/jsonschema](https://github.com/santhosh-tekuri/jsonschema) which didn't seem great;
* [eirini-forks/validus](https://github.com/eirini-forks/validus) which is a spike of mine, see https://github.com/cloudfoundry/korifi/issues/1947#issuecomment-1329096979 for an example;
* [gookit/validate](https://github.com/gookit/validate).

**Comment by matt-royal** [comment]
Here's an example using ozzo-validation. Running this yields the following output:

> Error:  version cannot be blank, applications.0.memory must use a supported unit (B, K, KB, M, MB, G, GB, T, or TB), applications.0.instances must be 0 or more, applications.0.routes.0.route is not a valid route


```golang
package main

import (
	apierrors "code.cloudfoundry.org/korifi/api/errors"
	"errors"
	"fmt"
	validation "github.com/go-ozzo/ozzo-validation"
	"gopkg.in/yaml.v3"
	"io"
	"regexp"
	"strings"
)

type Manifest struct {
	// Error field names will be pulled from the `json` tag. We can globally change this to `yaml` by setting
	// validation.ErrorTag = "yaml", but this will break json-encoded payloads. Alternatively, we can ensure that
	// yaml-encoded payloads also have `json` tags. We can also manually build up the errors ourselves, as shown
	// here: https://go-ozzo.github.io/ozzo-validation/#validation-errors
	Version      int                   `yaml:"version" json:"version"`
	Applications []ManifestApplication `yaml:"applications" json:"applications"` //validate:"dive"`
}

func (m Manifest) Validate() error {
	return validation.ValidateStruct(&m,
		validation.Field(&m.Version, validation.Required),
		validation.Field(&m.Applications),
	)
}

type ManifestApplication struct {
	Name                         string          `yaml:"name" json:"name"`                                                       //validate:"required"`
	Instances                    *int            `yaml:"instances" json:"instances"`                                             //validate:"omitempty,gte=0"`
	Memory                       *string         `yaml:"memory" json:"memory"`                                                   //validate:"amountWithUnit,positiveAmountWithUnit"`
	HealthCheckInvocationTimeout *int64          `yaml:"health-check-invocation-timeout" json:"health-check-invocation-timeout"` //validate:"omitempty,gte=1"`
	HealthCheckType              *string         `yaml:"health-check-type" json:"health-check-type"`                             //validate:"omitempty,oneof=none process port http"`
	Timeout                      *int64          `yaml:"timeout" json:"timeout"`                                                 //validate:"omitempty,gte=1"`
	Routes                       []ManifestRoute `yaml:"routes" json:"routes"`                                                   //validate:"dive"`
}

func (m ManifestApplication) Validate() error {
	return validation.ValidateStruct(&m,
		validation.Field(&m.Name, validation.Required),
		validation.Field(&m.Instances, validation.Min(0).Error("must be 0 or more")),
		validation.Field(&m.HealthCheckInvocationTimeout, validation.Min(1)),
		validation.Field(&m.HealthCheckType, validation.In("none", "process", "port", "http")),
		validation.Field(&m.Timeout, validation.Min(1)),
		validation.Field(&m.Routes),
		validation.Field(&m.Memory, validation.By(validateAmountWithUnit)),
	)
}

type ManifestRoute struct {
	Route *string `yaml:"route" json:"route"` // validate:"route"`
}

func (m ManifestRoute) Validate() error {
	routeRegex := regexp.MustCompile(
		`^(?:https?://|tcp://)?(?:(?:[\w-]+\.)|(?:[*]\.))+\w+(?:\:\d+)?(?:/.*)*(?:\.\w+)?$`,
	)
	return validation.ValidateStruct(&m,
		validation.Field(&m.Route, validation.Match(routeRegex).Error("is not a valid route")))
}

func DecodeAndValidateYAMLPayload(r io.Reader, object validation.Validatable) error {
	decoder := yaml.NewDecoder(r)
	decoder.KnownFields(false)
	err := decoder.Decode(object)
	if err != nil {
		return apierrors.NewMessageParseError(err)
	}

	return validatePayload(object)
}

func validatePayload(object validation.Validatable) error {
	err := object.Validate()
	if err != nil {
		return apierrors.NewUnprocessableEntityError(err, strings.Join(errorMessages(err), ", "))
	}
	return nil
}

func errorMessages(err error) []string {
	return errorMessagesWithLeafInfo("", err)
}

func errorMessagesWithLeafInfo(field string, err error) []string {
	errors, ok := err.(validation.Errors)
	if !ok {
		return []string{field + " " + err.Error()}
	}

	prefix := ""
	if field != "" {
		prefix = field + "."
	}
	var messages []string
	for f, err := range errors {
		ems := errorMessagesWithLeafInfo(f, err)
		for _, e := range ems {
			messages = append(messages, prefix+e)
		}
	}
	return messages
}

func validateAmountWithUnit(value any) error {
	var unitAmount = regexp.MustCompile(`^\d+(?:B|K|KB|M|MB|G|GB|T|TB)$`)
	v, isNil := validation.Indirect(value)
	if isNil {
		return nil
	}

	if !unitAmount.MatchString(v.(string)) {
		return errors.New("must use a supported unit (B, K, KB, M, MB, G, GB, T, or TB)")
	}

	return nil
}

func main() {
	manifest := new(Manifest)
	err := DecodeAndValidateYAMLPayload(strings.NewReader(`---
      #version: 1
      applications:
      - name: app1
        default-route: true
        memory: 128
        disk_quota: 256M
        instances: -1
        routes:
        - route: "0"`),
		manifest)

	if err != nil {
		fmt.Println("Error: ", err.(apierrors.UnprocessableEntityError).Detail())
		return
	}

	fmt.Println("No errors")
}
```

This example demonstrates...
- Custom validations
- Customizing the message for built-in validations
- Using the json field name in errors
- Showing the full path to errors on nested fields (e.g. applications.0.memory)
- We were able to replace the custom route validator with the built-in regexp validation with a custom error message

**Comment by matt-royal** [comment]
Based on my @gcapizzi and my notes at the top, we reviewed the following packages:
- https://github.com/RussellLuo/validating
- https://github.com/eirini-forks/validus
- https://github.com/gookit/validate
- https://go-ozzo.github.io/ozzo-validation

From these, ozzo-validation seemed like the most flexible and intuitive option. We were able to verify in a spike that it meets all of our needs (see comment above). The one major concern with this package is that it doesn't seem to be actively maintained. However, it is by far the most popular library we explored, it has only 1 production dependency and there is a recent fork that claims to be actively maintained. We believe that we can mitigate the risk of using this package by using the active fork, and that we will be able to make changes ourselves should we run into issues.

Regarding the other packages:
- `RussellLuo/validating` looks less intuitive than ozzo-validation, and it wasn't clear from their documentation if it would allow us to properly explain nested errors to users
- `validus` is young and will require us to build out a fair amount of logic ourselves. We believe we would be better served by modifying a more seasoned package when we run into trouble.
- `gookit/validate` seems mostly focused on processing web forms, doesn't encourage encapsulation of validation logic, and also uses tags to configure validation. We believe we'll have many of the same problems with this package as we do with our current one.

We also explored getting better error messages out of our current validation package. We may be able to correct the bad field names for the manifest by specifying `json` tags for each field, but we don't believe there's a way to properly display nested errors.

### Recommendation
We recommend that we use the https://github.com/jellydator/validation fork of ozzo-validation for #2123

**Comment by kieron-dev** [comment]
I like the look of this. Compared to go-playground/validator, I prefer the explicitness of defining the validation in code in a Validate method. It's quick enough to add out-of-the-box validations, and equally clear how to add custom ones when required.

When we make the actual change, I think it will be good to adopt the (already half-implemented) change to inject the payload decoder/validator into the handler and test it in the payloads package. We can then mock a single validation error in the handlers tests, and go into the detail in the payloads tests.

It probably makes little performance difference, but in the example code it might be better to declare and assign the regexes outside of the methods so they are only compiled once.
