### ISSUE TITLE
[Chore] Explore using viper for dynamic config changes

### ISSUE THREAD

**Issue by davewalter** [cloudfoundry/korifi#2207]
### Background

We introduced dynamic log level config changes in #2181 using `fsnotify`. It was suggested that we could use something like [viper](https://github.com/spf13/viper#watching-and-re-reading-config-files) to do this instead of using our own implementation. We could also expand the scope of which configuration options can be dynamically modified without restarting a component.

### Action to take

Try to incorporate viper into Korifi's config management. This might involve replacing some of our current configuration management code. Open a PR if this is possible, or document the issues encountered if not.

### Impact

Using viper would allow us to remove the logic to watch the config directory for changes.

### Dev Notes

* If this is possible, we could discuss expanding the scope to allow dynamic reloading of all configuration values. We could also investigate updating the Helm configuration to remove the random suffix from the ConfigMaps as it _should_ no longer be necessary.

**Comment by clintyoshimura** [comment]
We decided to put this story down for the moment. Changing to Viper for it's file monitoring functionality uses the same base fsnotify mechanism as the current code and doesn't remove all that much code in exchange for added package dependencies and parsing uncertainty. Even if we switch to Viper to monitor all config changes, work would still have to be done for each param to make them take effect without restarting the controller so we don't gain any additional functionality with just the switch.

**Comment by georgethebeatle** [comment]
Closing as we don't think it's worth introducing an extra dependency
