### ISSUE TITLE
[Bug]: Korifi can't specify buildpack

### ISSUE THREAD

**Issue by minhdtb** [cloudfoundry/korifi#2248]
### What happened?

An error orcured, when I was trying to specify buildpack for my application

Command used: 

```cf push -b https://github.com/cloudfoundry/php-buildpack.git```

The message:

```InvalidBuildpacks: Only buildpack auto-detection is supported. Specifying buildpacks is not allowed.```

Is that message is correct? I can't find any document about this problem

### What you expected to happen

Working as expected

### Acceptance Criteria

GIVEN ...
WHEN ....
THEN ...

### How to reproduce it (as minimally and precisely as possible)

...

### Environment

Revision of codebase:
Kubernetes version (use `kubectl version`): Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.24.10-eks-48e63af
Cloud provider or hardware configuration: EKS
Others:

**Comment by gcapizzi** [comment]
Hi @minhdtb!
As stated in the error, Korifi doesn't support specifying buildpacks when pushing yet. Also, the buildpack you're trying to use  is a V2 buildpack, while Korifi only supports [V3 buildpacks](https://github.com/buildpacks/spec).

However:
* a V3 buildpack for PHP exists [here](https://github.com/paketo-buildpacks/php) (`gcr.io/paketo-buildpacks/php`);
* you can modify the list of buildpacks used by Korifi by editing the `cf-default-buildpacks` `ClusterStore` on the cluster.

By adding the `gcr.io/paketo-buildpacks/php` buildpack to the `spec.sources` list in the `CluterStore` you should be able to push and build PHP apps.

I will close this issue as this is missing feature that we are aware of and that we plan to add in the future. Let us know how it goes!
