### ISSUE TITLE
[Chore]: Fork postfacto and deploy it on acceptance

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#2264]
### Background

Postfacto has been removed from Pivotal's github. Therefore we should create our own fork and deploy the fork on acceptance from CI.

### Impact

* We have the app in our control
* We have a reasonable app that deploys on a long-living cluster
* We still are able to use postfacto for our retro meetings

**Comment by kieron-dev** [comment]
A postfacto rewrite exists:  https://github.com/davidje13/Refacto. Let's see if this is usable, and perhaps deploy this instead of postfacto.

**Comment by kieron-dev** [comment]
We do not believe Refacto is really production deployable. Lots of hardcoding of localhost, and running of dev servers.

So we moved CI to point to eirini-forks/postfacto-release. We've bumped it to ruby-v3.2.2, which also prompted us to `bundle update`, and we've now got it working on rails-v7.

Hopefully it will be ok for a while again now...
