### ISSUE TITLE
[Feature]: Allow Roles to link to Kubernetes ServiceAccounts

### ISSUE THREAD

**Issue by Birdrock** [cloudfoundry/korifi#2279]
### Background

In Cloud Foundry, Users were the central authentication type. In Kubernetes, Users are opaque and by default are delegated to external tools. Currently, in Korifi setting a role will always try to set that role for a User, with no provision to set a role for a ServiceAccount.

**As an** Platform Operator
**I want to be able to** set an org or space role to a Kubernetes ServiceAccount
**So that** my ServiceAccount can interact with the platform as expected

### Acceptance Criteria

**GIVEN** I have a ServiceAccount
**WHEN** I `cf set-org-role USERNAME ORG ROLE` with a ServiceAccount name of the form `system:serviceaccount:<namespace>:<name>`
**THEN** a RoleBinding is created for the ServiceAccount

**GIVEN** I have a ServiceAccount
**WHEN** I `cf set-space-role USERNAME ORG SPACE ROLE` with a ServiceAccount name of the form `system:serviceaccount:<namespace>:<name>`
**THEN** a RoleBinding is created for the ServiceAccount

**GIVEN** that I have an entry in my kubeconfig for the service account user (see Dev Notes for steps)
**WHEN** I run `cf login` and choose the service account
**THEN** `cf orgs` should include the org ORG from the earlier step
**AND** `cf target -o ORG` should succeed
**AND** `cf spaces` should include the space SPACE from the earlier step
**AND** `cf target -s SPACE` should succeed
**AND** I should be able to successfully `cf push` an app

**GIVEN** I have a ServiceAccount
**WHEN** I `cf unset-org-role USERNAME ORG ROLE` with a ServiceAccount name of the form `system:serviceaccount:<namespace>:<name>`
**THEN** the RoleBinding is deleted for the ServiceAccount

**GIVEN** I have a ServiceAccount
**WHEN** I `cf unset-space-role USERNAME ORG SPACE ROLE` with a ServiceAccount name of the form `system:serviceaccount:<namespace>:<name>`
**THEN** the RoleBinding is deleted for the ServiceAccount

### Dev Notes

The following commands will create a service account called "acceptance-bot" on your cluster and add it to your local kubeconfig. It assumes you're using kind:

```bash
k create serviceaccount -n cf acceptance-bot

k create secret generic -n cf acceptance-bot-token --type kubernetes.io/service-account-token --dry-run=client -o yaml | k annotate -f - kubernetes.io/service-account.name=acceptance-bot --local=true -o yaml | k apply -f -

k config set-credentials acceptance-bot --token "$(k get -n cf secret acceptance-bot-token -ojsonpath='{.data.token}' | base64 --decode)"

# this line is only required to use the acceptance-bot user with kubectl
k config set-context kind-acceptance-bot --user acceptance-bot --cluster kind-kind
```

* If a username is of the form `system:serviceaccount:<namespace>:<name>` it is assumed to be a service account. Any other format will still attempt to create a RoleBinding for a User.
* RoleBindings are a 1-to-1 SA/user. While RBs can contain multiple subjects, this increases complexity and introduces potential sources of error.
_No response_

**Comment by matt-royal** [comment]
I confirmed that the acceptance criteria are satisfied on `main`. Accepted.

This did surface a different issue, though: there is no way to remove a user's access to an org entirely via the `cf` CLI. See https://github.com/cloudfoundry/cli/issues/781 for background. That issue gives a `cf curl` command you can run to remove a user from an org, but we haven't implemented the corresponding endpoint in korifi. (e.g. `cf curl -X DELETE "/v2/organizations/$(cf org --guid o)/users" -d '{"username": "system:serviceaccount:cf:acceptance-bot"}'`)

**Comment by matt-royal** [comment]
Actually, there is a flaw in the acceptance criteria for this story, which hid a bug. It is not possible to `cf login` with the service account and then list orgs with the current code. I'll update the AC in the next few minutes and reopen this issue.

**Comment by matt-royal** [comment]
The bug is that the `NamespacePermissions` code makes a bad assumption about the structure of the subject on role bindings. It's looking for a subject with a name like `system:serviceaccount:<namespace>:<name>`, when in reality it will just be `<name>`. I have a quick hack fix on my computer that confirms this and will pick this up today if I have time. There may be another issue, since even with the fix the CLI displays `Warning: subject 'ServiceAccount/system:serviceaccount:cf:acceptance-bot' has no CF roles assigned. This is not supported and may cause unexpected behaviour.`
