### ISSUE TITLE
[Feature]: App Developer can set service binding names that are reflected on the ServiceBinding / filesystem

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/korifi#2285]
### Background

Certain service binding libraries that apps use refer to the `ServiceBinding`'s name when configuring properties. One example is Spring Cloud Binding's Oauth2 library which uses the name to construct redirect URIs:

https://github.com/spring-cloud/spring-cloud-bindings/blob/main/src/main/java/org/springframework/cloud/bindings/boot/SpringSecurityOAuth2BindingsPropertiesProcessor.java#L57

We are currently setting the `.spec.name` field on `ServiceBinding`'s to the binding GUID that Korifi assigns which is impossible for developers to predict and can be a bad experience. Cloud Foundry Service Credential Bindings can have a "binding name" (`.spec.displayName` on our `CFServiceBinding` resource) set with `cf bind-service --binding-name` so we could use that to allow users to specify a more meaningful name for their bindings.

**As an** App Developer
**I want** the service binding name that I set to be propagated to the `ServiceBinding` resource and reflected on the filesystem when mounted
**So that** I have more control when using libraries that use refer to binding names

#### Binding Name is specified

**GIVEN** I have pushed an app (`MY_APP`) and created an UPSI (`MY_UPSI`)
**WHEN I** `cf bind-service MY_APP MY_UPSI --binding-name my-custom-binding-name`
**THEN I** See that the `.spec.name` on the `ServiceBinding` is set to "my-custom-binding-name" and when I inspect the filesystem of the app I see that it is reflected there as well.

```
cnb@d8e23a06-a57e-4717-ba26-45de07e0ed2d-cf--714be0d96d-0:/workspace$ ls $SERVICE_BINDING_ROOT
my-custom-binding-name
```

#### Binding Name is not specified

**GIVEN** I have pushed an app (`MY_APP`) and created an UPSI (`MY_UPSI`)
**WHEN I** `cf bind-service MY_APP MY_UPSI `
**THEN I** See that the `.spec.name` on the `ServiceBinding` is set to the `CFServiceBinding`'s GUID (current behavior)

```
cnb@d8e23a06-a57e-4717-ba26-45de07e0ed2d-cf--714be0d96d-0:/workspace$ ls $SERVICE_BINDING_ROOT
7762e318-91ac-4258-93b2-e22ebc296355
```

### Dev Notes

* There are no CF APIs for updating a binding's name once it has been created. You must delete and recreate the binding.
* The `ServiceBinding`'s `.spec.name` field is mutable, though. So if you change it then the Pod will be rolled to reflect the updated binding name on its filesystem.

**Comment by matt-royal** [comment]
I just confirmed that the acceptance criteria are met on main of korifi
