### ISSUE TITLE
[Feature]: Korifi API users can get spaces by space guids

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#2303]
### Background

**As a** Korifi API user
**I want** to be able to get spaces by GUID
**So that** I am happy that the Korifi API complies to the [CF API spec](https://v3-apidocs.cloudfoundry.org/version/3.134.0/index.html#get-a-space)

### Acceptance Criteria

**GIVEN** Korifi is deployed
**WHEN I** `cf curl /v3/spaces/space-guid`
**THEN I** get the space

**GIVEN** Korifi is deployed
**WHEN** I am logged in as a cf user with no permissions
**WHEN I** `cf curl /v3/spaces/space-guid`
**THEN I** get a 404 NotFound

**Comment by georgethebeatle** [comment]
already imlpemented
