### ISSUE TITLE
[Feature]: Korifi API users can get orgs by org guid

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#2304]
### Background

**As a** Korifi API user
**I want** to be able to get orgs by GUID
**So that** I am happy that the Korifi API complies to the [CF API spec](https://v3-apidocs.cloudfoundry.org/version/3.134.0/index.html#get-an-organization)

### Acceptance Criteria

**GIVEN** Korifi is deployed
**WHEN I** `cf curl /v3/organizations/org-guid`
**THEN I** get the org

**GIVEN** Korifi is deployed
**AND** I am logged in as a cf user with no permissions
**WHEN I** `cf curl /v3/organizations/org-guid`
**THEN I** get a 404 not found

**Comment by georgethebeatle** [comment]
already implemented
