### ISSUE TITLE
[Feature]: Korifi API users can filter service instances by label selector

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#2305]
### Background

**As a** Korifi API user
**I want** to be able to filter the list of service instances via a label selector
**So that** I am happy that the Korifi API complies to the [CF API spec](https://v3-apidocs.cloudfoundry.org/version/3.134.0/index.html#list-service-instances)

### Acceptance Criteria

**GIVEN** I have service instances labeled as `foo=bar` and service instances that do not have the label `foo`
**WHEN I** `cf curl /v3/service_instances?label_selector=foo=bar`
**THEN I** see only those service instances that have the `foo=bar` label

**Comment by georgethebeatle** [comment]
already implemented
