### ISSUE TITLE
[Feature]: Korifi API users can filter apps by label selector

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#2307]
### Background

**As a** Korifi API user
**I want** to be able to filter the list of apps via a label selector
**So that** I am happy that the Korifi API complies to the [CF API spec](https://v3-apidocs.cloudfoundry.org/version/3.134.0/index.html#list-apps)

### Acceptance Criteria

**GIVEN** I have apps labeled as `foo=bar` and apps that do not have the label `foo`
**WHEN I** `cf curl /v3/apps?label_selector=foo=bar`
**THEN I** see only those apps that have the `foo=bar` label

**Comment by georgethebeatle** [comment]
already implemented
