### ISSUE TITLE
[Feature]: Korifi API users can update app lifecycle

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#2327]
### Blockers/Dependencies

No response

### Background

As a CF API client I want to be able to update apps lifecycle data

### Acceptance Criteria

GIVEN Korifi is deployed
WHEN I request

```
curl "https://api.example.org/v3/apps/[guid]" \
  -X PATCH \
  -H "Authorization: bearer [token]" \
  -H "Content-type: application/json" \
  -d '{
    "name": "my_app",
    "lifecycle": {
      "type": "buildpack",
      "data": {
        "buildpacks": ["java_buildpack"]
      }
    }
  }'
```

THEN I get response similar to

```
HTTP/1.1 200 OK
Content-Type: application/json

{
  "guid": "1cb006ee-fb05-47e1-b541-c34179ddc446",
  ....
  "lifecycle": {
    "type": "buildpack",
    "data": {
      "buildpacks": ["java_buildpack"],
      "stack": "cflinuxfs3"
    }
  },
  ...
}
```

**Comment by tcdowney** [comment]
## Acceptance

1. Pushed a NodeJS app and specified the wrong buildpack: `cf push node -b paketo-buildpacks/ruby`
2. It failed to stage and I confirmed that the app's lifecycle listed the Ruby buildpack by inspecting the `CFApp`
3. Updated the lifecycle using the following `cf curl` command:
  ```
  cf curl "/v3/apps/$(cf app node --guid)" \
  -X PATCH \
  -H "Content-type: application/json" \
  -d '{
    "lifecycle": {
      "type": "buildpack",
      "data": {
        "buildpacks": ["paketo-buildpacks/nodejs"]
      }
    }
  }'
 ```
4. Confirmed that this updated the `CFApp`, was present in the API response, and I was able to restage the app.
