### ISSUE TITLE
[Chore]: Create e2e tests that validate user role management for ServiceAccounts

### ISSUE THREAD

**Issue by matt-royal** [cloudfoundry/korifi#2377]
### Background

#2279 added the ability to add and remove roles from service accounts and to log in as those service accounts. However, we only have unit tests for this functionality and problems were discovered during acceptance that the unit tests didn't catch.

### Action to take

Add tests to our current e2e suite that do the following

- As an admin user, make a service account user into an org manager for an org
- As an admin user, make the service account user into a space developer for a space
- As the service account user, create an app in the space
- As an admin user, remove the org and space roles from the service account user
- Verify that the roles were removed (e.g. attempt to create or update an app in the space as the user, find a way to list the org and space users if it exists and verify the user is missing)

### Impact

These new e2e tests will ensure that we don't have regressions in our support for e2e users.

### Dev Notes

You may need to change the scripts that set up test users and service accounts to run the e2e tests. This may also affect korifi-ci.

If making service accounts and getting tokens for them proves difficult on some platforms, consider skipping the tests there. We only really need this on one platform.

Here are some commands you can run locally to create a service account that can log in via the `cf` cli:

```
k create serviceaccount -n cf acceptance-bot

k create secret generic -n cf acceptance-bot-token --type kubernetes.io/service-account-token --dry-run=client -o yaml | k annotate -f - kubernetes.io/service-account.name=acceptance-bot --local=true -o yaml | k apply -f -

k config set-credentials acceptance-bot --token "$(k get -n cf secret acceptance-bot-token -ojsonpath='{.data.token}' | base64 --decode)"

# this line is only required to use the acceptance-bot user with kubectl
k config set-context kind-acceptance-bot --user acceptance-bot --cluster kind-kind
```

**Comment by matt-royal** [comment]
Consider adding a test that it's possible to add a role for 2 different service accounts with the same name, but different namespaces. See https://github.com/cloudfoundry/korifi/issues/2385 for details

**Comment by matt-royal** [comment]
To support these new tests, we'll likely need to change CI in the same way we did to support the crd tests. Here are some places to look:

- Storing the user info for EKS: https://github.com/cloudfoundry/korifi-ci/blob/2b2d03b17ed9302f7df8b7e2b6e6461040c73385/pipelines/scripts/set-account-env-vars.sh#L29-L32
- Creating the user and exporting the info for non-EKS: https://github.com/cloudfoundry/korifi/blob/b7de3ee4fe54ee7d617bdbbe3727bb381795888b/scripts/account-creation.sh#L67-L73

I dug around but couldn't find where the terraform variables we use for EKS are coming from. You may need to ask the EMEA folks

**Comment by kieron-dev** [comment]
EKS setup is in the cf-k8s-secrets repo, in particular:
- https://github.com/cloudfoundry/cf-k8s-secrets/blob/main/ci-deployment/eks-e2e/cf-users.tf
- https://github.com/cloudfoundry/cf-k8s-secrets/blob/main/ci-deployment/eks-e2e/outputs.tf
