### ISSUE TITLE
Address the BLOB_UNKNOWN: Manifest references unknown blob(s) error pushing droplets to Google Artifact Registry

### ISSUE THREAD

**Issue by kieron-dev** [cloudfoundry/korifi#2381]
***Blocked on response from kpack***

### Background

Since we began deleting container images from the registry when a CFPackage or kpack.Build resource is finalized, we have seen a new flake where a push of a droplet image to Google Artifact Registry (GAR) fails. The error shows up in the build pod logs like:
```
ERROR: failed to export: failed to write image to the following tags: [europe-docker.pkg.dev/cf-on-k8s-wg/pr-e2e-images/4b796eef-25df-4f84-a08f-56434e1216b0-droplets: PUT https://europe-docker.pkg.dev/v2/cf-on-k8s-wg/pr-e2e-images/4b796eef-25df-4f84-a08f-56434e1216b0-droplets/manifests/latest: BLOB_UNKNOWN: Manifest references unknown blob(s): sha256:f82966a670593cba9128e22a4bbe1a98a0d5a47d48e8d8e9a2a6784f1b08883a]
```

We believe this is due to a race between checking the blob exists in the [go-containerregistry code](https://github.com/google/go-containerregistry/blob/e2620e56504cf41a712b0e5eda5509c748ebbb11/pkg/v1/remote/write.go#L411-L419) and pushing the manifest having skipped uploading a layer, when in the meantime GAR has removed the blob since the last reference to it has been deleted from the registry.

This only seems to occur on GAR. Possibly it has a more aggressive garbage collection of blobs than other registries.

### Action to take

The issue affects the kpack build. It will fail in the export init-container, failing the build pod, and that failure bubbles up eventually to the CFBuild, and the droplet never becomes ready - failing the `cf push` or whatever triggered the build.

There are several points at which we could address the issue:
- go-containerregistry: this code is definitely racy if it is possible for a blob to disappear between checking for it and completing the image upload having skipped uploading the blob. However, this behaviour is very important to avoid reuploading large blobs unnecessarily. Maybe failure is the correct outcome here?
- buildpacks/lifecycle: it is the export binary which invokes the upload from go-containerregistry. Should this be more tolerant of upload errors? It might be worth asking if limited retries could be added here.
- kpack: kpack invokes the export binary from buildpacks/lifecycle. This might also be a reasonable place to be more tolerant of export errors and attempt some retries.
- korifi: korifi triggers the kpack build. If korifi retries on build errors, the entire build would need to be redone, which is an expensive operation. So korifi is probably too far away from the problem to use retry logic.

We only see this problem in our e2e tests. When running, they frequently delete all images in the GAR registry, triggering the blob garbage collection. In a production environment, it is less likely that all images would be cleared out just before a new image using the same blobs is being pushed. So, if we have no luck persuading the lifecycle or kpack projects to add retries, we could mitigate the issue in our e2e tests by pushing a droplet at the beginning of the test suite and removing it at the end. This would stop garbage collection of its blobs and should make the tests more stable.

### Impact

- Contact buildpacks/lifecycle and pivotal/kpack teams, explain the issue and ask if a retry would be feasible.

- Consider implementing the beforesuite droplet creation / aftersuite droplet deletion to mitigate e2e failures.

**Comment by kieron-dev** [comment]
We've added a change to push all test apps at the start of the suite. This looks like it solves the e2e CI issue.

**Comment by kieron-dev** [comment]
Question asked on kpack slack: https://kubernetes.slack.com/archives/C02UKAM5F2P/p1680185095718969

**Comment by georgethebeatle** [comment]
Closing as it is not critical for production usage
