### ISSUE TITLE
Improve resource filtering in repos layer

### ISSUE THREAD

**Issue by kieron-dev** [cloudfoundry/korifi#2422]
### Background

Each repo resource that needs filtering does it in a different way. Sometimes inefficiently, iterating over multiple list over and over again. E.g. https://github.com/cloudfoundry/korifi/blob/53aeb5f267478c2706f69e87c2d066d6f8de92a1/api/repositories/app_repository.go#L332. 

We should have a common, efficient way of filtering, and implement it across all repo resources.

### Impact

Reduced complexity. Increased performance on large datasets.

**Comment by kieron-dev** [comment]
Note that we did this in the app repository. The same pattern should be moved to the other repositories.

**Comment by georgethebeatle** [comment]
This seems to be implemented in all repos, closing
