### ISSUE TITLE
[Explore] Audit all CRDs to ensure they record a useful status condition

### ISSUE THREAD

**Issue by davewalter** [cloudfoundry/korifi#2502]
### Background

We have (repeatedly) noted at our working group meetings (see [here](https://docs.google.com/document/d/1ULNBEjlrNAgn3ko9y8ZJfwI7mw5-oofYdjl-dhkEoDA/edit#heading=h.5rixsb35gjd0) and [here](https://docs.google.com/document/d/1j_r7C4ThCBRXlI_LRleYns1QgIdFRkiFfzdBx_EXLLQ/edit#heading=h.q1pgdq6jwx5i)) that some of the CRDs are missing useful status information that would indicate whether a resource has been reconciled and, if so, what the current state of the resource is.

For this exploration, we want to answer the following questions for each CRD in Korifi:

* Does the status include an observed generation status?
* Would an observed generation status be useful for debugging?
* Does it have a high-level status condition such as `Ready`, `Succeeded`, or `Valid`?
* Does it "bubble up" the status of child resources (for example, Image -> BuildWorkload -> CFBuild -> CFApp)?

### Acceptance Criteria

The outcome of this exploration should be a document containing the following information for each CRD defined in Korifi:

* the answers to the above questions
* a list of all the status conditions defined, including their possible values and whether a particular value is terminal or not

### Timebox

No timebox

### Dev Notes

* See the notes about [status conditions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties) in the Kubernetes API Conventions doc.

**Comment by gcapizzi** [comment]
@davewalter is this actually done, or do you plan to work on the document about status conditions?
I moved this to _Reviewer approved_ because of the merged PR, but I now see this might not be done.
