### ISSUE TITLE
[Feature]: Runner authors can indicate that their runner doesn't support rolling deploys

### ISSUE THREAD

**Issue by matt-royal** [cloudfoundry/korifi#2542]
### Background

**As a** runner author
**I want** to have the option of disabling rolling deploys
**So that** my users don't experience incorrect behavior

### Acceptance Criteria

**GIVEN** I have a deployment of korifi using a non-default runner
**AND** that runner has indicated that it does not support rolling deploys
**WHEN I** attempt to run `cf push`, `cf restart` or `cf restage` with  `--strategy=rolling`
**THEN I** see an error message explaining that rolling deployments aren't supported

### Dev Notes

One option for implementing this: add a `RunnerInfo` CRD that has a field like `status.capabilities.rollingDeploy` on it. This mirrors the existing `BuilderInfo` custom resource, but scopes it to the runner, since this is a runner concern.

**Comment by tcdowney** [comment]
@Birdrock @matt-royal is this complete?

**Comment by Birdrock** [comment]
Made one more change to align error messages, but once that is through, should be good.
