### ISSUE TITLE
Ensure leases are available in the webhook cache after they have been created

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#2587]
We are occasionally seeing random errors on updating objects that validate unique properties (such as `CFOrg.Spec.DisplayName`). The error goes like this:

```
  2023-06-09T10:23:31Z  INFO    cforg-validate.duplicateValidator.ValidateUpdate        failed to acquire lock on old name      {"name": "9abf41c1-1e98-4812-a706-dc8df63a7362", "namespace": "root-namespace-4319678b", "reason": "failed to acquire lock on lease: leases.coordination.k8s.io \"n-98bb3adcaf422adebc6831501d9a42d6ea632af9\" not found"}
```

There are no other errors in the log.

Our theory is that this could happen when a test quicly creates and then immediately updates the object:
- The test creates the object, thus the validate create webhook kicks in and creates the `Lease` object. At this point in time due to the way webhooks cache works, the lease is not available in the cache immediately
- Then the test tries to update the object, therefore the validate update webhook is triggered. As all webhooks share the same cache, it fails to get the lease from the cache (as it is not available there yet), therefore returns an error.

In order to fix this error we should probably ensure that the lease is in the webhook cache (repeatedly try to get it after creating it until succeess). Also, we then have to ensure that the lease is gone from the cache after being deleted.

It would be useful to try to prove this theory because we are not sure whether cache is used when dealing with leases. Maybe we could create a test that just creates an org and immediately patches it by changing the display name and run it until it fails.

**Comment by georgethebeatle** [comment]
As Patch does not really use the cache the above theory is not likely. Maybe what happens is that the two etcd instances are not synced and the lease is not found in one of them. A simple retry should perhaps fix this
