### ISSUE TITLE
Find replacement for code climate for PRs

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#2614]
People on the team have found the default code climate liner that we run on every PR to be too noisy and inflexible. The issue is that even though this check is not required to pass for the PR to get merged, the PR still gets a red cross on it and looks like it has failed. The other problem is that most of the time the suggestions are not too helpful and there does not seem to be a way to configure it to our needs. Can we find a better solution or should we just disable it.

Maybe https://staticcheck.io/ or similar can yield better results

**Comment by kieron-dev** [comment]
It is possible to tweak code climate: https://docs.codeclimate.com/docs/advanced-configuration. Maybe we should consider allowing more return statements and being stricter about what constitutes duplicate code, and then it might start working for us again.

**Comment by kieron-dev** [comment]
Note: you can test code climate using the [command line tool](https://docs.codeclimate.com/docs/command-line-interface), which has a JSON output option that's helpful for analysing the results.

#### Summary of actions taken in new .codeclimate.yml configuration

- Introduce `**/fake/` into `excluded_files`

| Check | Failures | Threshold | Action | New count |
| --- | --- | --- | --- | --- |
| duplication:identical-code  |   2 | 100 | Force back to 100 | 2 |
| duplication:similar-code    | 114 | 100 | Increase to 400 | 4 |
| structure:argument_count    |  23 | 4 | Increase to 5 | 6 |
| structure:file_lines        |   9 | 250 | Increase to 500 | 2 |
| structure:method_complexity |  77 | 5 | Increase to 10 | 25 |
| structure:method_count      |   1 | 20 | Increase to 30 | 0 |
| structure:method_lines      |  81 | 25 | Increase to 50 | 8 |
| structure:return_statements |  56 | 4 | Increase to 8 | 5 |
