### ISSUE TITLE
[Bug]: `cf push` not triggering a build 

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#2645]
While accepting https://github.com/cloudfoundry/korifi/issues/2474, I have noticed that the following sequence of pushes, using a NodeJS app, would result in `cf push` getting stuck:

1. ```yaml
    ---
    version: 1
    applications:
    - name: app1
      buildpacks:
      - paketo-buildpacks/java
      - paketo-buildpacks/nodejs
    ```
    (succeeds)
2. ```yaml
    ---
    version: 1
    applications:
    - name: app1
      buildpacks:
      - paketo-buildpacks/java
    ```
    (fails, _"No buildpack groups passed detection."_)
3. ```yaml
    ---
    version: 1
    applications:
    - name: app1
      buildpacks:
      - paketo-buildpacks/java
      - paketo-buildpacks/nodejs
    ```
    (gets stuck, no `kpack.Build` gets created)

It looks like a problem with the implementation of https://github.com/cloudfoundry/korifi/issues/2440.

**Comment by gcapizzi** [comment]
@tcdowney I haven't tried anything else, but maybe pushing different sources? That would definitely convince Kpack to generate a new build!

**Comment by danail-branekov** [comment]
I believe the [this commit](https://github.com/cloudfoundry/korifi/commit/961f366d708e144b6b6063377477282474058899) changes the way how ownership to the builder is set. It used to be a simple owner reference, now it is controller reference.
