### ISSUE TITLE
Korifi CI doesn't run any of the unit tests under the /tools subdirectory

### ISSUE THREAD

**Issue by julian-hj** [cloudfoundry/korifi#2653]
### Background

When you run `make test` it runs all of the unit tests in Korifi. But our CI tests only run units under the directories that build into an executable.

### Action to take

We should add a step to run tests under /tools

### Impact

We won't have unit test failures going unnoticed for a long time

### Dev Notes

Extra-credit: the EMEA team uses the [check-everything script](https://github.com/cloudfoundry/korifi/blob/main/scripts/check-everything.sh) to test changes locally. We should make sure that tests things under /tools also.

**Comment by davewalter** [comment]
To avoid making the tmux panes unreadable when running `check-everything`, I ended up adding the tools tests to the pane that currently runs `make lint`.

**Comment by tcdowney** [comment]
I confirmed that the tools tests are running against PRs ([here is a recent PR that includes them](https://github.com/cloudfoundry/korifi/pull/2695)) and that the `check-everything` script is running them as well. Going to mark this core as complete.
