### ISSUE TITLE
[Feature] Platform operators can see when a route is invalid due to a non-existent domain

### ISSUE THREAD

**Issue by davewalter** [cloudfoundry/korifi#2706]
### Background

**As a** platform operator
**I want** to see when a route is invalid due to a non-existent domain
**So that** I can address the problem

### Acceptance Criteria

**GIVEN** an existing route with a corresponding domain
**WHEN** I delete the domain resource
**THEN** I see that the routes for that domain have been marked as invalid with a status condition that tells me what the problem is

**Comment by julian-hj** [comment]
Closing this issue, since deleting domains automatically deletes the routes. The route webhook is now more tolerant of missing domains, so even when there are race conditions and a route gets created with no domain, we think uninstallation will proceed now.
