### ISSUE TITLE
Set `CF_INSTANCE_INDEX` based on `statefulset.kubernetes.io/pod-index` label

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/korifi#2732]
### Background

Kubernetes version 1.28+ will set the `statefulset.kubernetes.io/pod-index` label on Pods within a StatefulSet. We should be able to set the `CF_INSTANCE_INDEX` env var on Pods with the value of that label using the [K8s Downward API](https://kubernetes.io/docs/concepts/workloads/pods/downward-api/) instead of our custom webhook.

### Action to take

* Update the statefulset-runner (and inform users who may be using custom runners) to set `CF_INSTANCE_INDEX` based on the new pod index label
* Remove the [webhook](https://github.com/cloudfoundry/korifi/blob/958e8d90e979d68bc18a555d6c285c12ca6a2734/statefulset-runner/api/v1/pod_webhook.go) that does this job today

### Impact

* This will simplify the code and allow us to remove an awkward Pod mutating webhook.
* Question: Will this change cause all StatefulSets to roll at the same time or will it only take effect when a user explicitly restarts an app? Or will it just occur when the statefulset-runner controller resyncs a particular AppWorkload?

### Dev Notes

* We can't get rid of the webhook until Kubernetes version 1.27 falls out of support.
* https://github.com/kubernetes/kubernetes/pull/119232

**Comment by georgethebeatle** [comment]
Fixed by #3483
