### ISSUE TITLE
As a Korifi API user I can request each api endpoint with a trailing slash

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#2749]
## Background

At the moment korifi rejedts all requests with a trailing slash. However traditional cf accepts both and serves valid responses

## Acceptance

**GIVEN** I have korifi deployed
**WHEN** I request any endpoint (i.e. /v3/organizations)
**THEN** I see a list of all orgs
**WHEN** I request the same endpoint with a trainling slash (i.e. /v3/organizations/)
**THEN** I see an identidal response

**Comment by tcdowney** [comment]
Here's a note on what we can do for this:
https://github.com/go-chi/chi/issues/41

**Comment by alperdedeoglu** [comment]
Hi @tcdowney, @danail-branekov,

First of all thanks for Korifi project, looks really promising. I'd like to suggest an alternative approach to the one shared by @tcdowney in [this issue](https://github.com/go-chi/chi/issues/41). In my opinion, the following proposal could be a more streamlined and quicker implementation:

```go
package main

import (
	"net/http"

	"github.com/go-chi/chi"
	"github.com/go-chi/chi/middleware"
)

func main() {
	r := chi.NewRouter()
	r.Use(middleware.StripSlashes)
	r.Get("/v3/apps", appsHandler)
	r.Get("/v3/apps/{guid}", guidHandler)
	http.ListenAndServe("localhost:8080", r)
}

func appsHandler(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("Apps Returned"))
}
func guidHandler(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("Guid Returned"))
}

```
I have tested via following commands:
```sh
curl http://localhost:8080/v3/apps/
curl http://localhost:8080/v3/apps
curl http://localhost:8080/v3/apps/123
```
And the result seems to be working as expected. 
```sh
Apps Returned
Apps Returned
Guid Returned
```
First two requests are handled identically, but the last one is of course handled differently.

What do you think? Is this approach also feasible?

**Comment by danail-branekov** [comment]
Hi @alperdedeoglu 

That sounds awesome and quite simple. Would be interested into PR-ing a fix? I guess adding the middleware [here](https://github.com/cloudfoundry/korifi/blob/d0613039e42d4118b36be8e784e07b00f77a9cf3/api/routing/router.go#L49C2-L49C13) and a unit test [here](https://github.com/cloudfoundry/korifi/blob/d0613039e42d4118b36be8e784e07b00f77a9cf3/api/routing/router_test.go#L41) should suffice.

Thanks!

**Comment by danail-branekov** [comment]
Yes, automation did not work as the commit message does not have a `fixes <issue-number>` comment. closing
