### ISSUE TITLE
Ensure that the Github account "korifi-bot" has 2FA enabled

### ISSUE THREAD

**Issue by julian-hj** [cloudfoundry/korifi#2818]
### Background

We got a notice that we have until September 28, 2023 to enable 2FA on korifi-bot (if it doesn't already have it enabled).

This is a user we use for the OSS foundation repos so we want to save its 2FA secret in korifi-ci's Vault. 

### Action to take

We need to set up 2FA for our CI bot account.

- Github instructions about 2FA for a team account:
https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-two-factor-authentication-for-your-organization/managing-bots-and-service-accounts-with-two-factor-authentication#managing-shared-access-to-bots-or-service-accounts-with-2fa
- update #korifi-dev on CF slack with some basic instructions about what changed in the bot account. (maybe add a more specific note vault describing how to use the 2FA key to reset the password & log in).
- make sure that CI is accessing the korifi github repo using a deploy key that will still work after 2fa is enabled.

### Impact

This will allow CI to keep working after September 28 2023

### Dev Notes

@davewalter wants to double check with other cloudfoundry teams to make sure we are all dealing with this the same way.

**Comment by Birdrock** [comment]
Completed 09/14/23.
