### ISSUE TITLE
[Chore] Enable the gocyclo linter

### ISSUE THREAD

**Issue by mnitchev** [cloudfoundry/korifi#290]
# Action to take

Enable the [gocyclo](https://github.com/fzipp/gocyclo) linter and see it it gives us some valuable feedback

# Dev notes

Add `gocyclo` to the [list of enabled](https://github.com/cloudfoundry/korifi/blob/d37a1f8833ceec517a08bbd109c942cf62634da6/.golangci.yml#L26) golangci linters

**Comment by georgethebeatle** [comment]
Code climate already warns us about cyclomatic complexity when we push a PR.
