### ISSUE TITLE
Configure CI clusters maintenance window

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#2907]
We are occasionally seeing flakes, especially on GCP, that seem to be caused by infrastructure (.e.g. network connectivity) issues. We are wondering whether those are not caused by cluster updates that coincide with periodic tests executions. Maybe we could configure maintenance windows for our clusters and stop running periodics during that time.

[GCP maintenance windows documentation](https://cloud.google.com/kubernetes-engine/docs/how-to/maintenance-windows-and-exclusions#maintenance-window)

We are not seeing such issues on AWS that often, however maybe it is worth to see whether we can configure such maintenance intervals for AWS clusters as well.

**Comment by danail-branekov** [comment]
We have enabled the maintenance window of the pr-e2e cluster to be [every Saturday, all day long](https://github.com/cloudfoundry/cf-k8s-secrets/blob/b68362a2e08e52996c6522815c701f8b0a29efd1/ci-deployment/gke-cluster/cluster-config/terraform.tf#L88-L94)

**Comment by georgethebeatle** [comment]
Done, and looks like it made a difference!
