### ISSUE TITLE
[Bug]: Do not trust insecure registries by default

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/korifi#2912]
### What happened?

I just tried to run the sample app `cf push nginx --docker-image nginxinc/nginx-unprivileged` provided in https://github.com/cloudfoundry/korifi/pull/2910 VM based CF deployment. It fails with [this](https://github.com/cloudfoundry/dockerapplifecycle/blob/93dcb397bf4de6ce44821a82ec6e955d97455637/builder/builder_runner.go#L82) error message. There seems to be also some docs [here](https://github.com/cloudfoundry/diego-notes/blob/80926d1963c8b75cd2cd6e36f342a79ccf7afaa9/proposals/docker_registry_configuration.md?plain=1#L15) why. 

### What you expected to happen

Maybe insecure registries could be supported with a special argument in case we think the it should behave like CF on VMs. 

### Acceptance Criteria

GIVEN that this is an accepted issue
WHEN I use an insecure registry
THEN it should fails by default

### How to reproduce it (as minimally and precisely as possible)

check the descriptions

### Anything else we need to know?

N/A

### Environment

Kofiri version https://github.com/cloudfoundry/korifi/releases/tag/v0.9.0

**Comment by danail-branekov** [comment]
Hi @beyhan and thanks for opening an issue!

The image that you have pushed is coming from the docker hub, which is not an
insecure docker registry. As a matter of fact it is the official docker
registry and only supports https.

We attempted to push `nginxinc/nginx-unprivileged` on a classical CF deployment
and here is the full error we're seeing when we run `cf logs --recent`:

```
ERR builder exited with error: failed to fetch metadata from [nginxinc/nginx-unprivileged] with tag [latest] and insecure registries [] due to unsupported schema version 2
```

The error is actually that the manifest schema of the image is not supported
and no insecure registries have been configured.

In kiubernetes it is not easy to run an image coming from an insecure regsistry
unless you own the docker daemon. More info in [this
article](https://saturncloud.io/blog/pulling-from-an-insecure-docker-registry-in-kubernetes-a-guide/)

We do not see this as a korifi bug. However if we want to be able to push
insecure images (do we?) we can file a feature request.
