### ISSUE TITLE
[Feature]: Support `info` endpoint 

### ISSUE THREAD

**Issue by beyhan** [cloudfoundry/korifi#2914]
### Blockers/Dependencies

N/A

### Background

**As a** user
**I want** want to have support for the V3 `info` endpoint documented [here](https://v3-apidocs.cloudfoundry.org/version/3.148.0/index.html#info-in-v3)
**So that** I can call `cf curl "/v3/info"` and get information about the Korifi version and some configurations.

### Acceptance Criteria

**GIVEN** the `/v3/info` gets implemented
**WHEN I** I call `cf curl /v3/info`
**THEN I** I see some descriptive information about the Korifi system.

**Comment by georgethebeatle** [comment]
This issue is fixed by #3248, thanks @gogolok
