### ISSUE TITLE
[Feature]: CF apps can access external CF routes from VCAP_APPLICATION

### ISSUE THREAD

**Issue by szeort** [cloudfoundry/korifi#2950]
### Background

An application shall be able to read external URLs, since that is an important feature from the classic CF.
That is normally accessible via env var VCAP_APPLICATION
VCAPP_APPLICATION.application_uris = [URL1, URL2, ....]
where URL1, URL2 are CF Routes. 
The same for VCAP_APPLICATION.uris 

That is VERY important feature!
The app could construct URLS for itself (self-link) and give it to the end user, so he/she could click and use a specific link for that application.
That link could be transferred to another third party like email, message etc, so that it could be used outside the browser context.

### Acceptance Criteria

In the application runtime, the following expressions gives a valid array of URL strings
VCAP_APPLICATION.application_uris
VCAP_APPLICATION.uris

**Comment by gogolok** [comment]
Commit ae55aad070fcd36336888c54a0a0078c9d4cbf14 introduces this feature.
