### ISSUE TITLE
[Chore]: Remove `Serial` restrictions from tests that have it

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#303]
### Background

There is at least one test that is configured to run [serially](https://github.com/cloudfoundry/cf-k8s-controllers/blob/d022c298fc1dc1197efa30393a566012965848ed/api/repositories/app_repository_test.go#L142). It will be great if this could be avoided, because parallel tests are not only faster, but also guarantee that you code (and tests) are more robust.

### Action to take

Remove the serial restrictions and fix the flaky tests

### Impact

We have faster and more robust tests

### Dev Notes

If the reason to flake is the ever changing environment due to parallel test we may try to make relative rather than absolute expectations. For example if we create an app and delete two apps, we can check that the new app is there and the two that we deleted are gone, while ignoring any other apps that we do not know about. If you think about it that is exactly what a human would do when playing with a busy multitenant system.

**Comment by kieron-dev** [comment]
Flakes to address:
- [ ] https://ci.cf-k8s.cf/teams/main/pipelines/pr-e2e/jobs/e2e/builds/40
- [ ] https://github.com/cloudfoundry/cf-k8s-controllers/runs/5814624255?check_suite_focus=true (service bindings: 85)

**Comment by kieron-dev** [comment]
https://github.com/cloudfoundry/cf-k8s-controllers/commit/bcba87283752fe0ca54631d5c947d3a3ab038e67 fixes the problem where one or more service account tokens aren't retrieved

**Comment by kieron-dev** [comment]
It seems user cert creation fails sometimes: https://ci.cf-k8s.cf/teams/main/pipelines/pr-e2e/jobs/e2e/builds/45

I fly intercepted onto the worker and saw the `E2E_USER_PEMS` env var had only 3 certificates in it.

**Comment by danail-branekov** [comment]
We should also look into at the api integration tests - why do they need to [start the test env](https://github.com/cloudfoundry/cf-k8s-controllers/blob/4e26a2af86acac0ab68664a54bf4e6afaa5ad3bc/api/tests/integration/integration_suite_test.go#L48) in `BeforeEach` rather than `BeforeSuite`?
