### ISSUE TITLE
[Feature]: As a Korifi app developer I want to see the MEMORY_LIMIT environment variable in my app containers

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#3081]
### Background

The [`MEMORY_LIMIT`](https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html#memory) environment variable is a standard Cloud Foundry one that hints applications on the memory limit they can use before getting restarted. 

**As a** Korifi app developer
**I want** to communicate the memory limit to my app
**So that** I can implement the app not to exceed the limit and eventually get restarted

### Acceptance Criteria

**GIVEN** a standard Korifi installation
**WHEN I** `cf push dorifi -p ~/workspace/trinity/korifi/tests/assets/dorifi -m 2345M`
**THEN I** see the `MEMORY_LIMIT` set to `2345M` in my app environment (by e.g. running `curl -k https://dorifi.apps.172.17.0.1.nip.io/env.json | jq .MEMORY_LIMIT`)

**Comment by marsteg** [comment]
opened PR for this issue: https://github.com/cloudfoundry/korifi/pull/3165

**Comment by marsteg** [comment]
I think this could be closed now
