### ISSUE TITLE
Monitor app health during Korifi upgrade

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#3134]
### Background
One of the important aspects of undisruptive Korifi updates is that we do not cause applications downtime. Currently CI ensures that `main` branch can be deployed on top of the latest Korifi release, but does not check for apps downtime.

### Actions to take
CI should check for apps downtime when upgrading Korifi.
Bonus points: if that check fails, mark the issue a commit fixes with the `disruptive` label.

**Comment by danail-branekov** [comment]
We have implemented a job to check for the age of a long-living app pod: https://ci.korifi.cf-app.com/teams/main/pipelines/main/jobs/check-long-living-app/
