### ISSUE TITLE
cf push fails with cf cli 8.8.0

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#3459]
```
~/workspace/junk                                                                                                                                                ⎈kind-e2e⎈
❯ ./cf --version
cf version 8.8.0+c1b66a0.2024-08-21

~/workspace/junk                                                                                                                                                ⎈kind-e2e⎈
❯ ./cf push dorifi -p ~/workspace/korifi/tests/assets/dorifi
Pushing app dorifi to org org1 / space space2 as cf-admin...

......

   Build successful

Waiting for app dorifi to start...

Instances starting...
Instances starting...
API endpoint not found at 'https://localhost/v3/deployments?app_guids=70cea9ae-cd4b-4b3e-bf47-ec230270c989&order_by=-created_at&page=1&per_page=1&status_values=ACTIVE'
FAILED
```

#### Dev notes

Apparently cli 8.8.0 has started using the `GET /v3/deployments` which is not supported by Korifi. Pushing apps with cli 8.7.11 works fine.

- [ ] fix the issue
- [ ] ensure latest cli is used when running tests. Can we introduce a make target to do that and use that binary when running the smoke tests?
- [ ] revert https://github.com/cloudfoundry/korifi-ci/commit/fe86b42c2897501500cbb1760cb29137611493ab (in case cf cli remains in the CI image)

**Comment by danail-branekov** [comment]
WIP branch: https://github.com/cloudfoundry/korifi/tree/issues/3459-cli-8-8-0-push

**Comment by fapo85** [comment]
fyi: the smoke test also fails if a cli in version 8.8.0 is installed.

**Comment by danail-branekov** [comment]
> fyi: the smoke test also fails if a cli in version 8.8.0 is installed.

Yes, they are running cli commands. Downgrading the cli should fix them
