### ISSUE TITLE
[Explore]: What is your release cadence?

### ISSUE THREAD

**Issue by BooleanCat** [cloudfoundry/korifi#3464]
### Background

I'd like to release `v2.0.0` of go-functional, but not until the beta has seen real production usage. How often do you ship to prod?

### Acceptance Criteria

Just some questions answered.

### Timebox

No timebox

**Comment by danail-branekov** [comment]
Hey @BooleanCat 

We are not aware of any production usages of Korifi so far. There are companies evaluating it right now though.

As per release cadance, we release whenever we believe we have anything worth releasing. We are currently looking into getting experimental managed services support with Korifi, this would probably take us about two months more.

What are your concerns? What we have seen so far, go-functional works well for us. If you are considering backwards incompatible changes, don't worry - we can adopt them.

**Comment by BooleanCat** [comment]
Thanks for the information! I just wanted to tease out any bugs that would incur breaking changes to fix but if you're willing to adopt breaking changes then I won't wait! Thanks.
