### ISSUE TITLE
[Chore]: Benchmark and Refactor Controller Integration Tests

### ISSUE THREAD

**Issue by gnovv** [cloudfoundry/korifi#351]
### Background

As we continue to add more functionality to the CF Controllers, we are noticing that the time it takes to run the integration tests is nearing 30 seconds.

We are guessing that some of the longest running tests use multiple eventual consistency steps which slows down execution significantly.

For example, the build controller tests update by first creating the CR and then waiting for the controller to update some status fields- only then do we pick up and modify the CR to set up the test.

### Action to take

This chore is to benchmark all the unit and integration tests in the controllers side of the codebase and determine which are the top 2-4 longest running tests.
When take those tests and improve their running time by either fully initializing the CR in question or perhaps injecting ad-hoc cache updates into the tests to speed up the eventual consistency waits.

### Impact

This will speed up development time both for all stories running tests, and speed up any future stories that need to update the code that the specific tests validate.

**Comment by georgethebeatle** [comment]
Waiting for the status to get updated is the very nature of kubernetes CRs. Our integration tests should be aimed at testing our controllers in as realistic an environment as possible. If we want to optimize the test runtime we could move some checks to a respective unit test. In a unit test we have full control which means we won't have to wait for reconciliation. So maybe this chore should explore if some test cases are better suited to a unit approach? What do you think?

**Comment by georgethebeatle** [comment]
Closing this chore as it appears to have aged and due to inactivity. Potentially doing the experiment described in #2874 could make our controller tests significantly faster and more stable
