### ISSUE TITLE
Implement the GET /v3/apps/guid/droplets endpoint

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#3552]
### Acceptance

Implement the `GET /v3/apps/guid/droplets` endpoint

### Dev Nots
[API Docs](https://v3-apidocs.cloudfoundry.org/version/3.159.0/index.html#list-droplets-for-an-app)

**Comment by benjaminguttmann-avtq** [comment]
Will see if I can get this one done :)
