### ISSUE TITLE
Error when trying to install Korifi on EKS

### ISSUE THREAD

**Issue by lohiaashwin** [cloudfoundry/korifi#3631]
Hello!

I'm trying to install Korifi on EKS as per the latest documentation but ran into issues where the korifi-controllers-controller-manager pod is failing.

kubectl get pods -n korifi
NAME                                                     READY   STATUS             RESTARTS        AGE
korifi-api-deployment-d944467b4-bwbz4                    1/1     Running            0               79m
korifi-controllers-controller-manager-7fb9b9fcf9-48nvw   0/1     CrashLoopBackOff   14 (3m6s ago)   79m

Some errors - 

{"severity":"ERROR","timestamp":"2024-11-26T10:25:23.874925996Z","caller":"controller/controller.go:316","message":"Reconciler error","controller":"cfdomain","controllerGroup":"korifi.cloudfoundry.org","controllerKind":"CFDomain","CFDomain":{"name":"default-domain","namespace":"cf"},"namespace":"cf","name":"default-domain","reconcileID":"0e7e77f3-a7f5-422b-a02e-3dc5182564bc","error":"patching-main-obj-failed: Internal error occurred: failed calling webhook \"mcfversion.korifi.cloudfoundry.org\": failed to call webhook: Post \"https://korifi-controllers-webhook-service.korifi.svc:443/mutate-korifi-cloudfoundry-org-v1alpha1-all-version?timeout=10s\": no endpoints available for service \"korifi-controllers-webhook-service\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:316\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:263\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:224"}

{"severity":"ERROR","timestamp":"2024-11-26T10:27:22.550202304Z","caller":"controller/controller.go:200","message":"Could not wait for Cache to sync","controller":"cfservicebinding","controllerGroup":"korifi.cloudfoundry.org","controllerKind":"CFServiceBinding","error":"failed to wait for cfservicebinding caches to sync: timed out waiting for cache to be synced for Kind *v1beta1.ServiceBinding","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:200\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:205\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/internal/controller/controller.go:231\nsigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.19.0/pkg/manager/runnable_group.go:226"}

{"severity":"ERROR","timestamp":"2024-11-26T10:27:22.553837222Z","logger":"setup","caller":"controllers/main.go:586","message":"problem running manager","error":"failed to wait for cfservicebinding caches to sync: timed out waiting for cache to be synced for Kind *v1beta1.ServiceBinding","stacktrace":"main.main\n\t/workspace/controllers/main.go:586\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:272"}

**Comment by danail-branekov** [comment]
> timed out waiting for cache to be synced for Kind *v1beta1.ServiceBinding"

Sounds like [servicebinding.io](https://github.com/cloudfoundry/korifi/blob/main/INSTALL.md#service-bindings-controller) is not properly installed. Could you check whether `servicebindings` CRD from the `servicebinding.io` group is available and the status of the `servicebinding-controller-manager` deployment in the `servicebinding-system` namespace?

**Comment by lohiaashwin** [comment]
Thanks @danail-branekov ! That helps.. I reinstalled the servicebinding CRDs and it looks better.
