### ISSUE TITLE
[Chore]: Refactor api/repositories errors

### ISSUE THREAD

**Issue by Birdrock** [cloudfoundry/korifi#403]
### Background

There are 3 separate errors types for resources not found or permissions issues. `NotFoundError` can contain the most information. `ResourceNotFoundError` is unused. `PermissionDeniedOrNotFoundError` is used in a few places.

### Action to take
* Choose an error name.
* Consolidate error types and refactor references. Include `ResourceType` information where appropriate.

### Impact

This will reduce some clutter in logging and eliminate dead code. This is low impact tech debt.

### Dev Notes

https://github.com/cloudfoundry/cf-k8s-controllers/blob/issue-398/api/repositories/errors.go

Is denied or not found a convention?

**Comment by kieron-dev** [comment]
ToDo:

- [ ] Write ADR
- [ ] AppRepo::GetApp
- [ ] AppRepo::GetNamespace
- [ ] AppRepo::SetAppDesiredState
- [ ] DomainRepo::GetDomain
- [ ] OrgRepo::GetOrg

**Comment by julian-hj** [comment]
@kieron-dev @gcapizzi @Birdrock we see that this is marked as "done" in the project. Can the issue be closed also, or is there some process subtlety that I'm not aware of?

**Comment by kieron-dev** [comment]
@julian-hj Yep - this should be closed. We don't require any PM style acceptance on chores.
