### ISSUE TITLE
[Bug]: Unauthorized Delete App returns 500 instead of 403

### ISSUE THREAD

**Issue by gnovv** [cloudfoundry/korifi#433]
### What happened?

When calling Delete App with permission to list, but not delete apps, the app handler returns a 500 regardless of the error type instead of intelligently wrapping and responding with a 403 if the app exists but the user does not have permission to delete it.

### What you expected to happen

Return a 403 error similar to this [PR branch](https://github.com/cloudfoundry/cf-k8s-controllers/pull/432) when the app cannot be deleted due to insufficient permissions.

### Acceptance Criteria

GIVEN I am a k8s user with permission to list but not delete apps
WHEN I send a DELETE app request to the cf api shim
THEN I receive a 403 error

### How to reproduce it (as minimally and precisely as possible)

Create a k8s clusterrole and rolebinding with only permissions to list apps. Use it to send a delete app request to the cf api shim.

### Anything else we need to know?

V3 error codes: https://v3-apidocs.cloudfoundry.org/version/3.113.0/index.html#common-errors

### Environment

Applies to all K8s distributions

**Comment by gcapizzi** [comment]
Closing as this is already fixed!
