### ISSUE TITLE
[Explore]: CLI unattended login

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#467]
### Background

The [`cf auth` command](https://cli.cloudfoundry.org/en-US/v6/auth.html) provides a way to authenticate the `cf` CLI non-interactively, which is very useful in scripts. We want to provide an equivalent flow for CF-on-K8s.

Overriding the `cf auth` command and ignoring the password argument could be a way: the user effectively selects a user entry in their `$KUBECONFIG` without the need for an interactive menu. This only makes sense if the selected user can be in turn authenticated non-interactively to the Kubernetes API though, and this is usually done via [Service Accounts](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#service-account-tokens). Which flow should we recommend to our users?

### Acceptance Criteria

A proposal to discuss with our team and the CLI team.

### Notes

We had already looked at this in cloudfoundry/cf-crd-explorations#42.

**Comment by tcdowney** [comment]
That issue @gnovv mentioned above mentions a rough "workaround":
https://github.com/cloudfoundry/korifi/issues/704#issuecomment-1058265358

**Comment by tcdowney** [comment]
@gcapizzi I'm going to go ahead and close this one. @julian-hj submitted a PR to the CLI to get `cf auth` working with Korifi that has been merged:
https://github.com/cloudfoundry/cli/pull/2296
