### ISSUE TITLE
[Feature]: Review permissions for `cf-admin-serviceaccount` and rename it accordingly

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#469]
The API shim uses two Kubernetes clients:
* a user-scoped client, built from the authentication header sent by the user in the request;
* a privileged client.

Most endpoints currently use the user-scoped clients, but we still have some legitimate uses for the privileged client. We want to reduce the permissions of the service account that backs it to the minimum necessary to function. This is currently [not the case](https://github.com/cloudfoundry/cf-k8s-controllers/blob/c92e095997059946b3c35b267afef5d51ff4ed09/api/config/base/rbac/role.yaml), as the privileged client used to be everywhere and we haven't trimmed down its permissions as we removed it from the codebase.

The name of the service account and its role (`cf-admin-serviceaccount`/`clusterrole`/`clusterrolebinding`) is also misleading, as this has nothing to do with the [`admin` user](https://github.com/cloudfoundry/cf-k8s-controllers/blob/c92e095997059946b3c35b267afef5d51ff4ed09/controllers/config/cf_roles/cf_admin.yaml). Something like `cf-serviceaccount`/`clusterrole`/`clusterrolebinding` makes more sense.

**Comment by kieron-dev** [comment]
We've implemented the minimal permissions for the service account.

It remains to rename it to something more appropriate

**Comment by georgethebeatle** [comment]
Whoops, I missed that and cut the draft release @kieron-dev . I guess the service account name is not overly important, no big deal if stays the same, given that the permissions are settled. We could also re-start the version counter and cut a new one, since this one is only an unpublished draft.

**Comment by gcapizzi** [comment]
I think it'd be ideal to have the rename in the draft release, but only if it's not too much work! We'd also have to delete the existing tag and release before we kick off the pipeline right? I'm afraid that we might forget something and end up in an inconsistent state, but if you think it's doable I'd do it.
