### ISSUE TITLE
[Chore]: Improve user client creation time

### ISSUE THREAD

**Issue by kieron-dev** [cloudfoundry/korifi#572]
### Background

It takes about 1.4s to create a k8s user client on my kind cluster. As we use the user client in more and more repos, we should be conscious that `BuildClient()` method on the factory is consuming a lot of time and k8s resources.

### Action to take

We successfully cached the identity response from k8s with a [caching identity provider wrapper](https://github.com/cloudfoundry/cf-k8s-controllers/blob/issues/449-restart-app-authz/api/authorization/caching_identity_provider.go). Maybe we should do a similar thing with the user client factory.

In terms of security, there is no concern about returning a client for an expired authInfo, since that client will return authorization errors as soon as it is used. We merely need to be concerned about the size of the cache.

### Impact

The responsiveness of the API is increased. CLI commands return more quickly.

**Comment by kieron-dev** [comment]
@gcapizzi  and I had a little spike on this. Caching looks a bit like this:
```
    clientInterface, ok := f.clientCache.Get(authInfo.Hash())
    if ok {
        client, castOK := clientInterface.(client.WithWatch)
        if castOK {
            return client, nil
        }
        return nil, fmt.Errorf("user-client-cache: expected client.WithWatch, got %T", clientInterface)
    }
/// body of BuildClient
     wrappedClient := RetryingClient{WithWatch: userClient}

     f.clientCache.Set(authInfo.Hash(), wrappedClient, 5*time.Minute)
     return wrappedClient, nil
```

And we wrapped the controller runtime client to do some retries, because the CLI create space fails as the space role cannot be created. This is due to HNC not propagating the callers role to the space quickly enough.

Here's a quick example of the client wrapping:
```
type RetryingClient struct {
    client.WithWatch
}

// This fixes role creation. Other methods should be wrapped too
func (c RetryingClient) Create(ctx context.Context, obj client.Object, opts ...client.CreateOption) error {
    var err error
    for i := 0; i < 5; i++ {
        err = c.WithWatch.Create(ctx, obj, opts...)
        if !k8serrors.IsForbidden(err) {
            return err
        }
        time.Sleep(100 * time.Millisecond)

    }
    return err
}
```

These changes lead to the following speed improvements:

Before
```
cf app app1  0.08s user 0.08s system 1% cpu 16.157 total
cf push app2  4.74s user 0.15s system 7% cpu 1:05.92 total
cf create-space space3 -o org1  0.10s user 0.05s system 1% cpu 9.071 total
```
After
```
cf app app1  0.10s user 0.02s system 28% cpu 0.405 total
cf push app1  0.50s user 0.13s system 1% cpu 44.192 total
cf create-space space2 -o org1  0.10s user 0.06s system 6% cpu 2.688 total
```

**Comment by gcapizzi** [comment]
I might have found a better way of doing this! 

The reason the client creation is performing a call is to discover the API group resources it needs for its mapping. If no [`Mapper`](https://github.com/kubernetes-sigs/controller-runtime/blob/d887b2f1c68fee51b20378ff2a0bd6a8a77674dd/pkg/client/client.go#L57-L58) is specified in the options, the client will [create a `NewDynamicRESTMapper`](https://github.com/kubernetes-sigs/controller-runtime/blob/d887b2f1c68fee51b20378ff2a0bd6a8a77674dd/pkg/client/client.go#L57-L58), which in turn will [`GetAPIGroupResources `](https://github.com/kubernetes-sigs/controller-runtime/blob/d887b2f1c68fee51b20378ff2a0bd6a8a77674dd/pkg/client/apiutil/dynamicrestmapper.go#L85).

We can avoid this by specifying a [`DeferredDiscoveryRESTMapper`](https://github.com/kubernetes/client-go/blob/cc43a708a08eb9ff6a436f0cb00c5ee05121d2cd/restmapper/discovery.go#L188-L192) instead, which will in turn wrap a cached discovery client. The available cached discovery clients are:
* `CachedDiscoverClient` which caches on disk and automatically falls back to an underlying client on miss.
* `memCacheClient` which caches in memory but needs to be refreshed periodically. I _think_ that the `DeferredDiscoveryRESTMapper` [does do the refreshing when needed](https://github.com/kubernetes/client-go/blob/master/restmapper/discovery.go#L231-L234), but I'm not 100% sure it would work.

If these solutions worked, we wouldn't need any cache on our side.

**Comment by danail-branekov** [comment]
The speed improvement ([wip branch here](https://github.com/cloudfoundry/cf-k8s-controllers/tree/issues/572-improve-client-creation-time)) made the [droplet flake in e2e tests](https://github.com/cloudfoundry/cf-k8s-controllers/issues/692) 100% reproducible. We found the root cause, but until we fix it, we cannot push this change forwards as we currently can't get green tests
