### ISSUE TITLE
[Chore] Investigate why controller tests hang under high load

### ISSUE THREAD

**Issue by mnitchev** [cloudfoundry/korifi#591]
# Background
We've recently noticed that running check-verything.sh sometimes causes the controller integration (env) tests to hang. We've traced the issue to a orphaned etcd process left over from the envtests. Since the the process is orphaned and ginkgo is waiting on a pipe containing stdout output, the test completes, but hangs and cannot continue to the next suite of tests.
 
 By debugging with [dlv](https://github.com/go-delve/delve), we noticed that the envtest cleanup is supposed to send a SIGTERM to the etcd process, however, either the signal is not sent or it is ignored by etcd. Manually sending the SIGTERM to etcd after the fact kills the process and unblocks the ginkgo process.

# Reproducing
To reproduce this we ran one of the env tests in controllers with `--until-it-fails` and at the same time ran check-verything. This gave us the highest chance of reproducing it in a reasonable amount of time. We suspect that it is because the system is under very high load when all the tests are running at the same time.

To help with debugging we also had to compile etcd ourselves and put it in `testbin/bin/etcd` as well as disable [this line](https://github.com/cloudfoundry/cf-k8s-controllers/blob/main/scripts/run-tests.sh#L14) when running tests. This is because the etcd binary we use isn't compiled with the right flags and we cannot attach to process.
In order to change things in the env tests we also locally ran `go mod vendor` and added a `-mod=vendor` flag when running ginkgo, so we can add debugging info in envtest.

**Comment by georgethebeatle** [comment]
#1242 might solve this by sharing the envtest instance and therefore reducing the load. If it fails we could have another go debugging envtest.
