### ISSUE TITLE
[Chore]: Offboard Mario

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#619]
# Garden
Mailing lists: cf-garden@pivotal.io
Lastpass groups: Shared-Garden
GitHub Teams in each org
cloudfoundry: CF Garden
cloudfoundry-incubator: CF Garden
GCP: CF-Garden Core
Pivotal Tracker: CF Garden Public; CF Garden/GrootFS Private
Wavefront: https://longboard.wavefront.com/u/NpYmkFnwVT?t=pivotal-garden
GitHub Org: master-of-cats
Slack: #garden-core, #garden-notifications; @gardencore, @gardencipair

# Eirini
Mailing lists: eirini@cloudfoundry.org
Calendar Invites: Standup, IPM, Retro, Conv Street etc.
Pairup: [pair board](https://pairup.eirini.cf) and your email from the [firebase access rules](https://console.firebase.google.com/u/0/project/cff-eirini-peace-pods/database/cff-eirini-peace-pods-defa
ult-rtdb/rules)
GitHub: [CF Eirini team](https://github.com/orgs/cloudfoundry-incubator/teams/eirini/members); [Eirininauts Team](https://github.com/orgs/eirini-forks/teams/eirininauts/members)
Pass: GGP key from [pass](https://github.com/cloudfoundry/eirini-private-config/blob/master/README.md#removing-a-team-member)
Git Authors: [git authors](https://github.com/eirini-forks/eirini-home/blob/master/git/.git-authors) and [github handles](https://github.com/eirini-forks/eirini-home/blob/master/team-github-ids)
SSH key: remove from eirini-home
Eirini-station: remove VM from GCP
Pivotal Tracker: Eirini Public
Add new ci-bot integration in #eirini-ci
GCP: cff-eirini-peace-pods

# CF-K8s
GCP project
GitHub Teams in each org

**Comment by mnitchev** [comment]
Should be all done, let me know if I've missed anything. Since I removed all my permissions I can't actually close this issue anymore, so please do that for me @georgethebeatle
