### ISSUE TITLE
[Chore]: Introduce Correlation-IDs and use in logs

### ISSUE THREAD

**Issue by kieron-dev** [cloudfoundry/korifi#656]
### Background

When debugging an issue, it can be hard to find the relevant information in the api logs. If e2e tests were running, for instance, we might see lots of failure lines, but not be able to work out if any are connected to the issue we're investigating.

It would be better if all log lines for a particular request contained a unique id. A common pattern for this is to use a correlation id. A request provides an id in the header field "X-Correlation-ID", and each logger should take care to set this value so it appears in its output.

We should also pass the id in a correlation id header when making calls to other systems, which helps with distributed logging and metrics.

We should integrate this approach into our e2e tests so that the fail handler is aware of the correlation id and so can filter the log lines shown to those relevant to the failing test.

#### Implement a new correlation ID middleware
This should extract the correlation ID, if any, from the request, and store it in the request context so that it is available to all code receiving the context.

It might be useful to generate a correlation ID if none is passed in. This means we can still tie together log lines from a particular request. In this case it might be useful to set "X-Correlation-ID" in the response headers.

#### Use the correlation id in all loggers
Each method or function performing logging and receiving a context should set the `correlation-id` value on the logger.

#### Teach the e2e test suite about correlation id
Each REST call from the suite should generate a correlation id and pass it in the `X-Correlation-ID` header. The fail handler should filter the logs it prints using the correlation id from the failing test.

### Impact

_Immediate_: API logs are more useful.
_Longer term_: We can contribute to distributed logging, profiling and metrics.

**Comment by tcdowney** [comment]
cc @gnovv who is interested in this area (OpenTelemetry, distributed tracing, etc.)

Also this might cross the line into feature work. Feels like it's similar in spirit to `X-Vcap-Request-Id` and a key part of the platform operator debugging experience. cc @emalm
