### ISSUE TITLE
[Bug] Deleted org/space can be still retrieved for a while after being deleted

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#680]
While backfilling e2e tests for spaces as part of issue #498 we wanted to create a test that
1. Deletes a space via the REST API
2. Invokes the URL specified in the response as `Location` and waits until it says `COMPLETE`
3. List the spaces that have the name of the space we just deleted
4. Expect that the result is empty

(Spoiler alert: it failed)

Here is the test (we cannot push it to master as it fails, wip branches could be deleted)

```go

         When("admin", func() {
             BeforeEach(func() {
                 client = adminClient
             })

             It("deletes the space", func() {
                 Expect(resp).To(
                     HaveRestyStatusCode(http.StatusAccepted),
                     HaveRestyHeaderWithValue("Location", HaveSuffix("/v3/jobs/space.delete-"+spaceGUID)),
                 )

                 jobURL := resp.Header().Get("Location")
                 Eventually(func(g Gomega) string {
                     resp, err := client.R().
                         Get(jobURL)
                     g.Expect(err).NotTo(HaveOccurred())

                     return string(resp.Body())
                 }).Should(ContainSubstring("COMPLETE"))

                 fmt.Printf("spaceGUID: %v\n", spaceGUID)
                 var resultList resourceList
                 listResp, err := client.R().
                     SetResult(&resultList).
                     Get("/v3/spaces?names=" + spaceName)
                 Expect(err).NotTo(HaveOccurred())
                 Expect(listResp).To(HaveRestyStatusCode(http.StatusOK))
                 Expect(resultList.Resources).To(BeEmpty())
             })
         })
     })
```

The code above fails at the last `Expect`

We noticed that the `GET /v3/jobs/{guid}` endpoint is currently implemented to [immediately return deletion completed response](https://github.com/cloudfoundry/cf-k8s-controllers/blob/1502a61c20c2947e592b32395b7cd48e990027b0/api/apis/job_handler.go#L55), however, it seems that the subnamespace anchor is still around as the subsequent list returns a non-empty array containing the space we just deleted.

Apparently, deleting subnamespace anchors (the thing that implements orgs and spaces) is an asynchronous process. Indeed, the HNS controller would [install finalizers](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/281b24ff4c6d9fbbed59f6ac473b9c3cad79450f/internal/hierarchyconfig/reconciler.go#L256) on reconciling created subnamespace anchors. Those finalizers are [removed](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/281b24ff4c6d9fbbed59f6ac473b9c3cad79450f/internal/anchor/reconciler.go#L169-L170) by the anchor reconciler once the underlying namespace is gone.

This bug cannot be reproduced with envtests as there are not controllers/reconcilers running there.

**How to fix it**
Maybe the best approach would be to implement `GET /v3/jobs/{guid}` to only return `COMPLETE` when the subnamespace anchor is gone. Thus
* We achieve that CF API assumption that delete operations are asynchronous
* The delete operation would not be slowed down by waiting for the subnamespace anchor to disapper

**... however you fix it**
Do make sure to add the test above into the e2e tests for both orgs and spaces.

**Comment by tcdowney** [comment]
Thanks for creating this!

For some additional context, we initially took this on as tech-debt to get the core workflows driven out to build off of.

* https://github.com/cloudfoundry/cf-k8s-controllers/issues/164
* https://github.com/cloudfoundry/cf-k8s-controllers/issues/335

It worked pretty good initially cause manifest application is completely synchronous, app deletion is less so, but still pretty reliable. I think with orgs/spaces, routes, etc. you're correct that they're now unreliable enough we should improve this.

A couple outstanding questions to think about:
1. In CF, the jobs have a defined timeout and means of propagating errors. If a deletion is "stuck", we will need some timeout to eventually mark it as `FAILED` even if the underlying resources aren't themselves in a terminal failure state. I think in CF this is usually (a configurable) 15 minutes.
2. How do we surface these errors to users such that they're actionable? I guess even just saying `FAILED` is better than saying `COMPLETE`, so maybe the error surfacing part of this is something we can iterate on.

https://v3-apidocs.cloudfoundry.org/version/3.115.0/index.html#jobs

**Comment by matt-royal** [comment]
This same behavior is occurring for deleting Service Instances. We've noticed it causes some a flakey e2e test failure, so we're making a PR to make the test resilient. In the long run, it would be better to revert this change and fix the inconsistency properly.

**Comment by danail-branekov** [comment]
The job handler now awaits that orgs/space namespacesare gone, therefore this issue is no longer relevant
