### ISSUE TITLE
[Feature]: Improve how we surface errors in the Space Manifest

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/korifi#699]
### Background

**UPDATE:** The repro steps below are no longer accurate since we fixed that particular issue in https://github.com/cloudfoundry/cf-k8s-controllers/pull/725. We can still trigger this through other cases, though, like requesting a route for an app that already exists (see https://github.com/cloudfoundry/cf-k8s-controllers/issues/548#issuecomment-1058427556). 

Currently any error in the [`applyManifestAction`](https://github.com/cloudfoundry/cf-k8s-controllers/blob/main/api/actions/apply_manifest.go) will cause the `SpaceManifestHandler` to return a `500` error:
https://github.com/cloudfoundry/cf-k8s-controllers/blob/39dae24761131efa657437c09d4bc1db153d9fc3/api/apis/space_manifest_handler.go#L73

For example, I attempted to push an app and requested `default-route: true`, but there was no default domain configured. This resulted in an error [here](https://github.com/cloudfoundry/cf-k8s-controllers/blob/39dae24761131efa657437c09d4bc1db153d9fc3/api/actions/apply_manifest.go#L149), but instead of an error message like "No default domain configured", I got a `500` error.

```console
cf push node
Pushing app node to org o / space s as tdowney...
Unexpected Response
Response Code: 500
Code: 0, Title: , Detail: {"errors":[{"detail":"An unknown error occurred.","title":"UnknownError","code":10001}]}
```

**As an** App Developer
**I want** to receive meaningful errors when manifest application fails
**So that** I can fix my app manifest without requiring the platform operator to look at component logs

---

### Acceptance Criteria

One of the easier cases to reproduce is the "no default domain" case, but in general we should think through some of the errors we can handle better here without explicit A/C.

### No Default Domain Found
**GIVEN** I configured the CF API shim with a default domain, but haven't applied the `CFDomain` CR 
**WHEN I** `cf push` an app with `default-route: true` in its manifest
**THEN I** see a friendlier `422` error saying something like "No default domain available"

For other types of errors even just something like "Error creating `CFProcess`  or "Error updating `CFRoute`" could be better.

**Comment by danail-branekov** [comment]
It seems that the issue has been fixed in the meanwhile:
* When I push a manifest requesting default route with no CFRoutes configured, but with a default domain configured in the helm chart, I get the following error: 

```
The configured default domain "apps-127-0-0-1.nip.io" was not found
```

* When I try to push an app with the same name in another org I get

```
Route already exists with host 'node' for domain 'apps-127-0-0-1.nip.io'.
```

Seems good enough to me.

Generally, the way we propagate errors from webhooks to the user is through [`ValidatonError`](https://github.com/cloudfoundry/korifi/blob/cf85f691acfc3e0c4c1479c96a11718ce398ff72/controllers/webhooks/cf_validation_errors.go) which gets presented in a human-friendly manner to the user.

**Comment by tcdowney** [comment]
Sounds good, plus I think #2123 is going to be making some further improvements to these error messages. I'm going to close this one.
