### ISSUE TITLE
[Chore]: Use Patch instead of Update

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#714]
### Background

When performing Update you have to get the object first, then modify it and finally attempt to Update it. This opens up a gap for the object to be asynchronously changed by another thread resulting in conflicts. One way to work around that is to use Patch instead, as demonstrated [here](https://github.com/cloudfoundry/cf-k8s-controllers/blob/489b41eecfcbc08151254da2fe9c6513300ed1fa/controllers/controllers/networking/cfroute_controller.go#L171). If Patch is used the operation is atomic and conflicts are avoided.

### Action to take

Change the code to use Patch instead of Update everywhere

### Impact

Code is more robust

**Comment by danail-branekov** [comment]
`Update` has been replaced by `Patch` in the route and service instance controllers, leaving the chore opened to address the rest of the `Update` occurrences.

**Comment by georgethebeatle** [comment]
Today's progress is summarized in this commit: https://github.com/cloudfoundry/korifi/commit/f3cbb9a06d1492585eca66577d05c435c3938200

It works in e2es and integrations, but the pathcher tests are broken, because the test objects (a Pod and a Secret) lack type metadata and cannot be looked up form the Schema which seems to be populated properly. Tests need more looking into, otherwise looks promising.

**Comment by danail-branekov** [comment]
With latest PR the chore has been implemented for the "core" controllers. What is left to do:
- use `PatchingReconciler` in `kpack-image-builder`, `statefulset-runner`, `job-task-runner` controllers
- use the `k8s.Patch` utility in repositories
- use the `k8s.Patch` utility in repositories in integration tests 
- check for other usages of `k8sClient.Update` and `k8sClient.Patch` and deal with them accordingly
