### ISSUE TITLE
[Explore]: Remove HNC Controller

### ISSUE THREAD

**Issue by julian-hj** [cloudfoundry/korifi#769]
### Blockers/Dependency

CFOrgs and CFSpace stories

### Background
- We've seen a lot of bugs & race conditions arising from our use of HNC, and we have worked around some issues with very hacky fixes. 
- We've also found that it doesn't propagate all the things we want it to (e.g. service accounts) so we already have to do some manual propagation when we create orgs and spaces.
- The [HNC webhook is called for every object in the cluster](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/config/webhook/webhook_patch.yaml#L27-L37), which causes security and performance issues

We'd like to understand the scope and feasibility of managing orgs and spaces using only our custom controllers.

This exploration is likely a spike to see how hard it would be to manage roles, service accounts, and role bindings with no HNC.

This spike should include
- creation of secrets, role bindings and service accounts when new spaces and orgs are created
- propagation of access when new role bindings are added to the root namespace

### Acceptance Criteria

- A proposal to remove HNC with corresponding spike branch OR
- Comments to describe why the work was harder than we thought, and we cannot do it.

### Dev Notes

Currently, the only role-binding that needs to be copied into orgs and spaces is the cf-admin one. We may not want a generic mechanism to do this.

**Comment by kieron-dev** [comment]
See https://github.com/cloudfoundry/korifi/blob/issues/1000-role-latency-flakes/api/config/base/apiconfig/role_mappings_config.yaml for the role bindings that need to be propagated. At the moment that is admin, admin-read-only, global-auditor, and organization-manager. We just haven't put any useful permissions in anything other than admin and space-developer at the moment.

**Comment by kieron-dev** [comment]
I also wanted to point out that the HNC webhook configuration is our fault for not configuring it properly! It comes out of the box like that so that the configuration can be changed at runtime to propagate any resource. We don't need that, and we've only configured secrets to be propagated on top of the default roles and rolebindings. We don't actually rely on role propagation, so we can safely configure the webhooks to listen only to rolebindings and secrets.

**Comment by kieron-dev** [comment]
About the hacky fixes to address slow HNC propagation: we also now have to deal with slow k8s API recognition of new role bindings - see #1000. The latency is only a few hundredths of a second, compared to up to 10 seconds for HNC under heavy load, but we will need to address that somehow too.

**Comment by kieron-dev** [comment]
I was also wondering what the problem with propagating service accounts was. I see the code for manually creating kpack and eirini service accounts in the space creation code, but wonder why those couldn't be created in the root CF namespace and propagated through the orgs and spaces.

**Comment by davewalter** [comment]
The problem with the service account propagation is that the service account tokens are auto-generated by Kubernetes and cannot be propagated. The [HNC docs](https://github.com/kubernetes-sigs/hierarchical-namespaces/blob/master/docs/user-guide/concepts.md#built-in-exceptions) call this out as a built-in exception.

**Comment by davewalter** [comment]
Exploration branch: `issue-768-explore-hnc-removal`

**Comment by davewalter** [comment]
Notes for the CFOrg reconciliation:
* We would not be able to use an OwnerReference to delete the namespace (namespaced resources cannot "own" cluster-scoped resources), so we would need a finalizer to clean up when an org is deleted.
