### ISSUE TITLE
[Feature]: Set `Stack` used for building Image on BuildDropletStatus

### ISSUE THREAD

**Issue by akrishna90** [cloudfoundry/korifi#77]
### Background

The [GET Droplet V3 API](https://v3-apidocs.cloudfoundry.org/version/3.107.0/index.html#get-a-droplet) returns a `stack` field that indicates the root filesystem used with the buildpack, for example `cflinuxfs3`. Information about the `stack` used in the kpack build is available on the `kpackImage.Status.LatestStack` field. We would like to capture the same on the `CFBuild.Status.BuildDropletStatus`.

Add a new field `stack` to `CFBuild.Status.BuildDropletStatus` and set the value to match corresponding Kpack Image's  `Status.LatestStack` value 

### Acceptance Criteria

GIVEN that I am targeting a k8s cluster
AND that I have followed the README instructions to install the Controllers and set up the kpack Registry Credentials and staging CRs
WHEN I apply the example CFApp, CFPackage, and CFBuild resources in config/samples directory
THEN I should see all those operations succeed
WHEN I fetch the yaml for the CF Build CR after its kpack Build completes successfully
THEN I should see that it now contains the `Stack` used to build image under BuildDropletStatus

### Dev Notes

- Update the `cf-k8s-api` droplet_repository.go file and set the stack value.

**Comment by tcdowney** [comment]
> should we still be thinking about docker builds

No, not really. There's no immediate plans to support them and the belief is that the Docker app UX on Kubernetes is already richer than what CF provides so it's unlikely to be a priority.

I wouldn't do anything that makes them outright impossible to add in the future, but I wouldn't worry too much about it either.
