### ISSUE TITLE
[Feature]: API can get process disk usage stats

### ISSUE THREAD

**Issue by acosta11** [cloudfoundry/korifi#772]
### Blockers/Dependencies

Immediately available solution depends on disk usage logic from metric-proxy. See [the disk usage fetcher](https://github.com/cloudfoundry/metric-proxy/blob/main/pkg/metrics/diskusage/fetcher.go).

Otherwise this is blocked on an exploration for updating controller logic to surface this information on the process/statefulset itself to avoid auth complexity in the api.

### Background

**As a** API client
**I want** to view stats for given cf processes
**So that** I can observe my applications

### Happy Path
**GIVEN** cluster with cf-k8s-controllers, api shim, and metrics server installed
**WHEN I** make a request that looks like
```
curl "https://api.example.org/v3/processes/[guid]/stats" \
-X GET \
-H "Authorization: bearer [token]"
```
**THEN I** get a response that looks like 
```
HTTP/1.1 200 OK
Content-Type: application/json

{
  "resources": [
    {
      "type": "web",
      "index": 0,
      "state": "RUNNING",
      "usage": { "time": "2016-03-23T23:17:30.476314154Z", "cpu": 0.00038711029163348665, "mem": 19177472, "disk": 69705728 },
      "host": "10.244.16.10",
      "instance_ports": [],
      "uptime": 9042,
      "mem_quota": 268435456,
      "disk_quota": 1073741824,
      "fds_quota": 0,
      "isolation_segment": null,
      "details": null
    }
  ]
}
```

### Dev Notes

API docs: https://v3-apidocs.cloudfoundry.org/version/3.113.0/index.html#get-stats-for-a-process

Note on RBAC:
* The metrics api group is separate from corev1, so the existing process/pod RBAC is likely insufficient, we will have to determine the necessary RBAC on the cluster node for access to disk usage
* For direct node access requirements, we would need a privileged client in the api
* For propagated information on the process/statefulsets, we can use a user client in the api

Fallback:
* If metrics server is not available, continue to return the empty usage block
Do we also include a runtime log for debugging as well?

**Comment by gcapizzi** [comment]
Pretty sure this was fixed in https://github.com/cloudfoundry/korifi/pull/2081!
