### ISSUE TITLE
User-Provided Service Intances and Bindings

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#776]
**Proposal:** [User Provided Service Instance Support in CF on K8s](https://docs.google.com/document/d/1pi7u2zH07oeKS6TalWhzsnFPwbCy44SrvPGRMfomops/edit)

* Support creating, listing, updating, and deleting user-provided service instances (UPSIs) within a space.
* Support binding and unbinding an UPSI to an app, so that the credentials appear to the app instances in the `VCAP_SERVICES` env var in the [expected JSON format](https://docs.cloudfoundry.org/devguide/deploy-apps/environment-variable.html#VCAP-SERVICES).
* Out of scope: We will only be supporting credential service bindings. Other types of user-provided service instances such as route services and syslog drains will not be supported at this time.

**Comment by tcdowney** [comment]
The user-provided service instance work in the proposal has been completed. There's still more work to be done, but that will be tackled in a future service management epic.
