### ISSUE TITLE
[Feature]: Developers can test ImageFetching

### ISSUE THREAD

**Issue by gnovv** [cloudfoundry/korifi#83]
### Background

As a Developer
I want to be able to test CFBuild ImageFetching
So that I can confidently make changes to the CFBuild Controller

Currently the [ImageFetcher code](https://github.com/cloudfoundry/cf-k8s-controllers/blob/main/controllers/workloads/imageprocessfetcher/image_process_fetcher.go) is hand-tested due it the difficulty in working with image registries in tests, this story is to either introduce a test with a private image registry as an integration, or end to end test.

### Acceptance Criteria

GIVEN I pull this or the E2E test repo
WHEN I `make test`
THEN I see that the ImageFetcher tests are run

### Dev Notes

- This can be implemented as E2E level or as an integration level test with a private image registry
- Be mindful to not commit credentials into the code

**Comment by tcdowney** [comment]
Closing this. Registry interactions are integration tested via e2e tests, smoke tests, and (in the future) CATS.
