### ISSUE TITLE
[Bug]: CFApp finalizer will never be removed if a related domain is deleted

### ISSUE THREAD

**Issue by kieron-dev** [cloudfoundry/korifi#880]
### What happened?

When replacing deletion of subnamespace anchors with a call to the delete org API endpoint, we noticed that some test code was causing the org namespaces to never be deleted. This turned out to be due to the finalizer on CFApp.

The code was as follows:
```golang
AfterEach(func() {
    deleteOrg(orgGUID)
    deleteDomain(domainGUID)
})
```

The test had created a CFApp, and it was including in the destinations for a CFRoute pointing to a domain with the `domainGUID` above.

Since the API call to delete an org is async (relying on polling a job afterwards for completion which is not implemented), the delete domain code might run before all contents of the org's spaces have been removed. The org deletion eventually cascades to the space's namespace deletion. K8s attempts to remove all namespace resources which triggers the CFApp deletion. Finally, that triggers the CFApp finalizer code which attempts to update related routes by removing the app from the route's destination list. But the route's validation webhook fails because the domain cannot be looked up. So the finalizer can never be removed from the CFApp, and this blocks the namespace deletion.

Note that this code only alerted us to this issue. Making `deleteOrg()` synchronous here would only fix the test not the underlying problem.

### What you expected to happen

Either the CFRoute validation webhook should deal gracefully with CFDomain deletion, or the CFApp finalizer should be able to cope with such a permanent error. Or maybe both.

### Acceptance Criteria

GIVEN a CFDomain
AND a CFRoute associated with that domain
AND a CFApp with a destination on that route
WHEN I delete the domain and then delete the app
THEN I see the app is successfully deleted

### How to reproduce it (as minimally and precisely as possible)

```bash
# deploy CF locally on kind
cd ~/workspace/cf-k8s-controllers
./scripts/deploy-on-kind.sh -l -d cf-env
./scripts/create-new-user.sh cf-admin

# create a domain
cat <<EOF | kubectl apply -f-
apiVersion: networking.cloudfoundry.org/v1alpha1
kind: CFDomain
metadata:
  name: bd67e962-0ded-4ba6-beb3-e5d6e3ed490f
  namespace: cf
spec:
  name: example.com
EOF

# login using the CF CLI
cf api https://localhost --skip-ssl-validation
cf login # and select the cf-admin entry from the list

# create and target and org and space
cf create-org org1
cf create-space -o org1 space1
cf target -o org1

# create a route
cf create-route example.com --hostname foo

# create an app and add it to the route's destinations
cf create-app app1
cf map-route app1 example.com --hostname foo

# delete the domain
kubectl delete -n cf cfdomain bd67e962-0ded-4ba6-beb3-e5d6e3ed490f

# attempt to delete the app
cf delete app1
```

Use k9s or kubectl to see the app is not deleted. There will be a log entry in the controllers pod saying 'failed to patch cfRoute to remove a destination'.

You can also try `cf delete-org org1`. This will leave the org and space namespaces in the terminating state as the app cannot be deleted from the space.

### Environment

Revision of codebase: main branch: fdbd22206cfa6ac7108565fb9a3ad60c231545dd
Kubernetes version (use `kubectl version`):
Cloud provider or hardware configuration:
Others:

**Comment by gcapizzi** [comment]
⚠️ We have decided to solve this by masking the `CFApp` finalizer more tolerant for now. Once we implement domain deletion, we will take care of deleting related routes and that should make it impossible for this to occur.

**Comment by kieron-dev** [comment]
We thought we could do this by setting an owner ref on the CFRoute to the CFDomain. However, since the domain is generally in the root CF namespace, and the route is not, the rule that owner refs cannot be across namespace breaks this idea.

It looks like we will have to delete routes in the domain finalizer instead.
