### ISSUE TITLE
Store environment for LRPs and kpack builds in secrets

### ISSUE THREAD

**Issue by danail-branekov** [cloudfoundry/korifi#925]
This depends on https://github.com/cloudfoundry/cf-k8s-controllers/issues/917

This is to adopt the fix from the issue above in Korifi. We should make sure that we inject environment in LRPs and kpack builds securely over secrets rather than a plain-text key-value pairs.

**Comment by gcapizzi** [comment]
I think this has already been done - @danail-branekov do you confirm?
