### ISSUE TITLE
[Chore]: Rename this project to `korifi`

### ISSUE THREAD

**Issue by gcapizzi** [cloudfoundry/korifi#931]
### Background

We have a new name! It's **Korifi**! Unfortunately this also means renaming everything 😬 

### Action to take

* Rename our repository to `cloudfoundry/korifi`
* Rename everything named after `cf-k8s-controllers` to use `korifi` instead (e.g. namespaces, secrets)
* Make sure that everything keeps working after all of this
* Switch concourse and vault to the `*.korifi.cf-app.com` domain. Ask @gcapizzi for assistance on that one, since this domain is owned by vmware. (Spawn this to its own chore, as it should not block the release)

### Dev Notes

* We don't need to support an incremental upgrades

**Comment by georgethebeatle** [comment]
Do we want to rename this field as well: https://github.com/cloudfoundry/korifi/blob/c219f840672d10b0ba4e1f7aa989932daa1db755/api/presenter/root.go#L14 ?

If yes, we will also need to PR the cli accordingly

**Comment by georgethebeatle** [comment]
Switching concourse and vault to the `*.korifi.cf-app.com` domain is not urgent and should not block the release, since these systems are not user facing. Furthermore changing the domain would mean re-deployment of these systems, which means we would have to export-import the vault secrets (they are not stored in a DB just yet) and to unseal the vault. Maybe it is better to split the domain switching to a separate chore that we do after #799 and #800.

**Comment by PureMunky** [comment]
> Do we want to rename this field as well:
> 
> https://github.com/cloudfoundry/korifi/blob/c219f840672d10b0ba4e1f7aa989932daa1db755/api/presenter/root.go#L14
> 
> ?
> If yes, we will also need to PR the cli accordingly

Since we talked about this during the SIG call I thought I'd add here that we decided not to rename that field because it still represents what the CLI is doing, connecting to CF on a K8s cluster. However unlikely, this could allow for alternate approaches to this beyond Korifi.

**Comment by PureMunky** [comment]
I noticed that the Code Climate links in the readme are pointing to Korifi but they're 404'd because Code Climate still knows the repo as cf-k8s-controllers. @georgethebeatle, do you know what we need to do to connect Code Climate up to the new name?
