### ISSUE TITLE
[Chore]: Create a release pipeline

### ISSUE THREAD

**Issue by georgethebeatle** [cloudfoundry/korifi#958]
We are almost ready to release our first beta. We can do so manually, but might as well take the time to automate it for next time. Let's borrow heavily from [eirini controller's release pipeline](https://github.com/cloudfoundry/eirini-ci/blob/master/pipelines/eirini-controller/pipeline.yml)

Here are the artifacts that we want to upload:
- Version tag in github
- GitHub draft release
- Images on DockerHub, built from the release tag and tagged as the version to be released
- Reference YAML files pointing to the tagged images, attached to the release.

**Comment by georgethebeatle** [comment]
Pipeline is done and tested, but is still on a [branch](https://github.com/cloudfoundry/korifi-ci/tree/release-pipeline) since it needs permissons to push to gcr io as the relint bot. Can anyone from AMER put its credentials in the vault, please? @tcdowney @matt-royal @davewalter @Birdrock

**Comment by tcdowney** [comment]
@georgethebeatle what is the pipeline using RelInt's GCR for? Shouldn't it be pushing the images to DockerHub?:
* https://hub.docker.com/r/cloudfoundry/korifi-controllers
* https://hub.docker.com/r/cloudfoundry/korifi-api

Or are we using GCR for dev builds or something? If so I'm wondering if we should switch to the working group's GCP account.

**Comment by georgethebeatle** [comment]
@tcdowney my bad, you are right, we should be pushing to docker hub, to the cloudfoundry org, but we do not have a technical user that can push there. However we noticed that the relint bot can: https://github.com/cloudfoundry/korifi/runs/6038314998?check_suite_focus=true#step:9:1

We do not have the credentials for this user though, so we cannot configure the release pipeline to push there. We used the eirini user for testing, but eventually we will need to push to `docker.io/cloudfoundry`

**Comment by tcdowney** [comment]
@georgethebeatle I added it to Vault.

**Comment by georgethebeatle** [comment]
Pipeline works, and pipieline config is now merged to main, closing
