### ISSUE TITLE
[Bug]: `cf push --no-start` shouldn't report "Droplet not found" errors and exit 1

### ISSUE THREAD

**Issue by tcdowney** [cloudfoundry/korifi#965]
### What happened?

When you push a new app with the `--no-start` flag the CLI will report print out the following error:

```
Droplet not found. Ensure it exists and you have access to it.
```

Full push output:
```
Pushing app node to org o / space s as cf-admin...
Packaging files to upload...
Uploading files...
 1017 B / 1017 B [=============================================================================================] 100.00% 1s

Waiting for API to complete processing files...
Droplet not found. Ensure it exists and you have access to it.
FAILED
```

The push actually succeeds so this is somewhat cosmetic, but it still isn't a great experience since the command appears to fail.

### What you expected to happen

I expected `cf push MY_APP --no-start` to succeed with no errors or warnings reported.

### Acceptance Criteria

GIVEN I have logged in and have an app to push
WHEN I run `cf push MY_APP --no-start`
THEN I see the push succeed with no errors reported

### How to reproduce it (as minimally and precisely as possible)

1. Grab your favorite app
2. Run `cf push MY_APP --no-start`
3. See the error reported

---

### Anything else we need to know?

This is happening because the `GET /v3/apps/<app-guid>/droplets/current` endpoint is returning a 404.

This CLI has [special handling](https://github.com/cloudfoundry/cli/commit/2afb1f1f1743dd7939143eaa65f1a6605eba25f9) for this to swallow the error and continue, but it is doing an exact string match on the error message being `"Droplet not found"`. Our error message is `"Droplet not found. Ensure it exists and you have access to it."` so the CLI isn't handling it correctly.

```json
RESPONSE: [2022-04-14T10:23:21-06:00]
HTTP/1.1 404 Not Found
Content-Type: application/json
Date: Thu, 14 Apr 2022 16:23:21 GMT
Server: envoy
Vary: Accept-Encoding
X-Envoy-Upstream-Service-Time: 12
{
  "errors": [
    {
      "code": 10010,
      "detail": "Droplet not found. Ensure it exists and you have access to it.",
      "title": "CF-ResourceNotFound"
    }
  ]
}
```

Our options here are either to make our error message match what Cloud Controller is doing or PR a change to the CLI. Quickest and easiest way that accounts for other clients that have codes against the existing Cloud Controller behavior is probably to just update our code.

#### Dev Notes 
We're not sure if `cf push --no-start` always behaved this way or not, but if it's new, @akrishna90 thinks this potentially could be related to the error handling refactoring and consolidation from https://github.com/cloudfoundry/cf-k8s-controllers/pull/781.

### Environment

Revision of codebase: ae56a5cd5d97b99a92150e28cc439c63a96485e1
Kubernetes version (use `kubectl version`): N/A
Cloud provider or hardware configuration: GKE
Others:

**Comment by gnovv** [comment]
We accidentally changed GET droplet before, but now we have it working on the branch:
```
$ cf push node3  --no-start
Pushing app node3 to org o / space s as cf-admin...
Packaging files to upload...
Uploading files...
 623 B / 623 B [==================================================================================================================================================================================================================================================] 100.00% 1s

Waiting for API to complete processing files...

name:              node3
requested state:   stopped
routes:            node3.vcap.me
last uploaded:
stack:
buildpacks:
```
